return {
   [0] = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAAAAADRE4smAAAgAElEQVR4nO2dX4gfy3Xnv7/78pP3Ys9k7YzWcRgFx4zWJEayA44Ug5dIwSEJUjBszNWDk5eVaIEXHDQPG2ixmCvIPrTYQAIaWnmx89AiCSxpkTUJaYUs2C0bkttDErw9eI17uBunJ/7T4+C4fk9nH+rfqer+/X4z+nPjbM7nQZrqX/+prjpdderUqVOAoSRSqU0gycFoiSgFACICBqJMH8+oA4CKKv3b4C8piBqfyjpFfQHkxMjBU/qW0QMAIqI+qahmB8IzmuC55tnB081Z/aoDjaLOvn5SD6SGit9Q5UDSRzetB+pzAFmtWH7G6fFbjHPIshO9UHhtnJW0GYiGvs4mbxUVlqIaKIgSc1ui1l2V2jq278Zzt0wAQFQBuU6vEIBCPy09vQDk1KLxP0+cARSk5ZA/uozKt4olIjowmAyyBKnVtzSn6aLj+YnT47cY366Kiqs74bWVK7966lZRYeXs1FgAhjDLRLwJWCoApb5NZ35bIgAJWQGAOqUAlFQAxaBKlrNYAJAq9iLIJz7XgsjfYeJASX2Cxt6lLRKgDopgolFpaciIKEXalUUgAFF69BbjHEbZ4S80KgGelcKXXz11q9H31BENpf2JC0Ab5riinrePTgBGFD2RaSyXC0BNRBVQp1oGE56/AtASEjSZbzUNlUAatLw1z+gECVGF1pRgHuU/Tr8slC5ZFJ1vAU5O7wWgjDKs6owfWC4AjOUC0LMmrePN2w+MAIQtANATUbc6RxVvIf6ZBCDx33Berj51ip6oxSsAgOuz2S77pZxf3j36FZ8+P5vN7j17PreAL9q/fxPYzlecO2pr+YHGN3WZl7cXcMn1o60HdGHx33lONt5j/kh5T+WahfcBf7XyrQOqXtFQJ6dOlk4XsZ8r1/reB+Db+ppb1/W7up50iJMAgLJTREO97mtWDZCPvnmt8gBAR0b8y55UmxREVOqnFD2pNkHQAiRBs18x7WqiBWiJAvUrOJCEWSheziUun0ZQpwXA3RZY2wIkVvUpTpssyRa1EYBA62MiDZxAADKngqX+lhPVWlACYNCNS+0uaVwebWG1+qfGCYDJXhYIQB6UFQavsEwIgApKOT7QkO7zgld/cZcEIu9e4PkFwKu+2SmTJZH58nVtRVofEZFXD9cJQOYv9gLwyj4AXa3bwOIWAPzCwR6Az+9EStCfAfgZmNP/N4BqR/9wwZ6xcUX//ylejHQTvqoB/D5waWkTlM4BAL+45MAegI8AwK8A+PwLv+TDOtHlCeDNAPdmhgWAxZ4+mAGLZS8RU8+Bw9uzpwA+edokAOz4W30cwJPZbPboEACwD2B+jZqTKRyfAnB0fza7u8+PZmTUsoKMzBfmS1ANwFsADEbqOyNCWg6TjmwLQJTpZqZ0LYAXOisAaJ2hYtwClESq5cPT6IBubJCyr/kFXqLVU/fFRx9Aw98i93dzH1Y2nXaNbK/L7TRJPc4uYT7XkdbXmUf1Kda2AKUvgZx1AaNqRd/ZUmFVRqnufwp3P+RkatILQAktSN0qAUjIDlXHAtARdRWx1jU6kBCR0hkqps941kva0h3ImoFoaBIked07KcmIiA/PJwRAnz+Vbs01VJ8uqQVgsLWVEUXjvWLw0rZGAAYKrTtcrWDVitxJrrLPssNAIup0DVfsQrROAOzjFNcBBtMJOyp2ZiQARFRlxHrj+EBDREVCTPl5kZdwe27VKiKmGQ48gSo2Lcfn+3RlygspEXWnS5ZE1BClTAAiuzdyrYmptQLgKshiBxZhtcKbgCp7vhWAjoj0vwnY8yorAPrlFRFxAeBfP+wZNf/FCYCuBPISMzqQENHQsFu+hEvSojHfVV/nth+oKfiAKmbPiM+P0pHyfKpkSUQpUc1VdjUa8tdERMUaAcgollkrAGG1ZuwtbQlZAchtTff8KEpyw0Bz31gAQiUlJ29ZDgVAtw3McDQ6oHti9h280Et6wDbpQ1NwVTUl4koDan91fH6cdqMr/Q2eKlkSEQZStrbMq8Ran7Z2rBaAInwBeEPQnwAosQ0c7QEY8F1/yvfC59xaAD9dAPiSPbIJAK/a1BkAwEZ4UQZgNzjyCWB/2q70k8Ax8DVge9kBGC388y/lki0A2F0cPLk/27x4417nv/ldAIvzPqdvA2xjb87/8s+kNLT59PWsTE+dxF9ibrNxUWv/F+70wUDqKzpHK3kVwPfHh1+Jq/XeoTMBVovr0dlvAFtXAFwHtA3qPQDwo/bnuf2Xj5Deg4hyA7g4nckt4OvA16HFZuoA9vYB4PjGy7kkB4Az56/uAkDlRAjVBoDPhZl1pXnm/NVdFDe359jYuVlNXv9cXAV+3v597tGxzvLrGZBaJW0LwLdOdjM9M+eVmVcQVSv+YNsK10e+EF/9x/phBwB0gV0B+Di1hLYS8L5mCzgObvIx4Ml05nIAXwH+AmboPj4A8z1//iVd8gGWm/SKk+PkCoCDW+zHt41KfP/+bPaQPZRfj3eE554qCRz61gw3Nh/q4v8UgEvU5ADKKwDeiK+K+B6WthJm4Gs7CDvyKeJhIHT/7to1otgOoEZ2AKCJputr3xvHOoC1ObgOe3TA5oHf7eVcAgyU21ftKTIUo4snmO2D/Gn2+udVAoGcqOx5D260Pm6j7NeNAowSyFoANxl07wiA/gIA4I+MCfAXno5f8EuAtRcCTwFcogesoZvfoTtzIOg6fgj4Dksml4Dfnyg6AHi//3Nj+sBbeEm78cjO9pRbiDuAM7YdDCi2/Gnu+m/BKBcpgP50Sc2tBT4aPOfyPoAf40eOzkY9/CJO7uo7781mQfv7ChBVK24d/xoA5BufHb/hdUCbgQHgstZI4CyLx0ZkfodfchY4ZMlfB454W8rhNVZMHnjrLil29q3SkFxD1AEAG7FmCwDFa3hsT/PXvwGjJn0YwN+dLgl7i42t4Ela67t39/HB8QI4Pnh4FsA/wWhcCQAVJ3EMo+MEvAJE1Qp8/hIA/PL+3uhsXZd/ZhPnHh9hcXjX1+/lR8dYHNwOimYO/L1PZTvAb0/cF9CF/2g2m81uQ3+WowNv3SXJa8dOUf0NhCMA/VZHoztXr+GRbfvY9bswatJPA/jj0yUN9o9Y67t3/fzmmds4Pn8LAP4PgA8BepLj7+Ik/heAT0yVCPRQlQ0tVQVkbG6MOYSosSkKNREVyxxCSgqM6j2fh490gMadqnQvNTpgb+E69Jd2ifNe7PSf7NMpaUiykXELaEn5MmTXoyaiLkGtO+FTJa19eiAiapGS0fqIV1hl1REiospMGWajJBTpSYOWSEUuYVG1lgromNGgdUWUU2zXhZ23mBCARruBhoeZOTISAF/+5oGjA+5x9g4v7RJWgX4KXksCEVXN6DNIBuqZoHMBeM7pYMBNC0dan6GxWnYd/hol+XRwJACjalVlyifH7XwR0oGVKpKuSIGkJSI16RJmDKJMXeZOoXUkAGyqS9sWRwdGtfkSLzHn5hgJwEBEpGKHQTsvR6PrgTR0+ThF0s1QjQSg96/jG9XW/jokE0nmEFIHAhBWKwBUqmVD+VrXsBFq34Jbb19dbEsFgA0CA7fwWABY8adE1I4PaFhtvsRLfAXGApB0pKJVB1gtAM/nEgZA12ULpGU7KNIWR/Nqiucmbwci1ZXTSe0SpvqKV/aoWgEwt3BfW+ZMVsleABpMCkDaKuuFHDxsWgCEt5ZGd32jagXAFoaYyrJnhqKf1b0iGvTUxIQAPFuuaGiYhLZeMRutAfJrYLiXJ8UrB6p+pLpWrs+rFbXB4xL3XN0km7UPGQAk4Ux3Wg+KBj9BH33JNe+oqz5oIupoaq5wfXDZuyINSO17Rj+NfQSAIfTJVtHPKIgqLgDjFs0tDdPi8QxO5xNk9otHpkLfhKwZFA1tZqe7WI6ZAMRrgPwamGC5TCwA/YSI91YAutHjTP2ltqq4APSBkbOxX4dWl5w3p30zVskZU37i38wbVDy3PvdVr2hoUvT6hGJUnYqf7cqMe65EplgAA5FrAU5JQ1ShdA+oaUiBTDHdydksk4ECZSlRNLjldwNFw0zz1qZQK/6bz2awBsivgQmX2kQCYHTfUADsI3JSKfiqCicAaE09MwHQpW8FwH3SzA8iqLw6UtWIgGqNAFThPRLr8ONcacuoOhuifAjfrmT1n2hfp3DMmhPVgQCEbvJRAYYNbyQAqInKmuvOrau9gYa8ZxIwBDlv/S99WHLFhMg+B9VEE1nYF6ipYkuC0lYRUa/d5jPSmrF3FTO+TUYAWiKqUyDr9f2j8Tx4JVsJXy8APZHKkORtZp9osUVSBiOVnChHonh/m/Li66kfr3Lqo3S0VjFuQoOGNxYA/cn6HNXOGjJQA6C2Q5DlVOaTTxtyb92vueYU1BRo5gBYBx8IQOkKOwEApYvEC0Chf9ECkPsvXZHCyLkTvJJ96z8pAEk9EFFfIey9ddEYofJVVvHGU7e9Ke8E+IdW6Vdrgy8qi/SzeK1iLADR4ssXDpHtNrWzKjrb5rihFRlfmdMmAC2hE4/Uf/AugA2yE8BJjheATleaFoDet6sVURJ7c3KDRxIJQPgbE7xW93j+i1Hm2UQTlsdnpluz7PEl0LNXLqNUQfEH/9IFIPNPZEpgQ0RZR2ladIk5i3IuAGRWYhI1tp0telJ1QZTF3pynEADf8LRGY+HOiy2MSe+ZBlVTpEZSM6LSTAadmLDqAK6/h6nxmct4P5iL2VvDR4C/MX+e21/g4NMAgHcDB7sK37x349weoCdxPsyuKsC8Lj4M/AlQv7aF+aVfAIB3Anp+6B6As9EDj7Gc5BqAR4/x5O6TbwO7TwC81uvy3AHwJpBdMtkD9KhAeTvQmnRWdwOR6rmd95PA7wHAO4AfxsiLwN7DDGejX0fVyvT3MLXqmx+nwpVCHS3z5XiWRDtuAYbJxc490cBGAcDg1lPAlgVgWoCWiBvXs9ibE+D9vP3Ip3SAmojy0SigtU8srCaogGiKYX3aG9589JfE/qg1uXELkKgrW3NsXHpwgk6n31meirELrK5HqQ3or8bznaW+HM/C2dEirmQDC/3E4AP5BrDR8W+3D/Pxbn6jTRwDPwcc3J7dd0djb07H9cNlvwDvB46dr0F+Bbj78BjYUYn24PpHNBs4gHa4zG7aE7c7nCDtmbsp+gT4AwDAq9qnd9QCBMPZiRaA3TXU34NUeOaqFFH8hZZEPmDPc7YASUPcKtKX+v66Qw0/EPs9d1by9TyxawECc+JAnbGnAIVtAVxJjTX9amkLQESNGwa2fkjZmln6nGiw9xyIqE6Q9qa5WZfOujJLgJRP97sHm/F9LADhcHa1ABBx/T1IPY8A8Dbv+QSg5c1f0pmm0Xlrs6mJAUwbY41zGgiAV1YVdYDSEpGu7QIAIGuXCkDtBKAz0lqTWQtAuTKLVrRvoBFm/Sbr0v7Z5DQxH/pGG4JGXcAlAOf2cPkI2FoTR6CAc++6dS9KnZyJRbab++Njz87Rp3V29rahlwJsAzqf3z18fP/2bHb3ENjIgOt3jZvflh/1fnPJTRXOAEp3ET8BaL/Ht9tfpxYO7y4fSntn3S8COzWAvzYPAT4xx1PbfH8A1nPzCNhenwaSqldEdAda4QNwiXU4wFgAMhhvxy8B+KWlWQYQ6+/Pqs0rmIkOT39h8sxnZOu3zO0Pj46AHJlzUtw9d313D7j3B9Aa973zs0McAtBusZETtbILHwBggTnwdaBNkH0ciFw/V2n9McdOwQdwYx+4pMrkE8Abumg2cHzZnvcjAG4SEZH2EFyXRvHgypbNs36bivnHAxgLwAcBvAkAXzY3XMG7zWlTqTGmeW3j1NcRjra0E+7R/dmZ1U8/Cedntw+AuVlof+7sHwEfxkeAr5rfxx+Iwm8+gvGlexvcqiIAWJilTwVRg29gA/gzYOcB3ZkDkevn106Rx68AW96Md/EJML/2YAP7l234l2yJUMXGnHE6fW30tI9gcSM4EAvAyuEsAF51of4+1ubDKl/GV6A9ID3bAP7r2Of2mdg7vwDO2dQt4N/j/cCf6+T4AwF0I/p2ADgblvo3eAvwFaDErvaCXgCR6+doRU2AIqJLwBYRUYLPAvhUDiAtawBXbx8CwOFF6G8DT+9pofrqstst55cA4NHt2ey+PVLO8afRSZGaF+kyy+0Abay+hanwzFWpSVOwCm70XIk2+sVPqAaxXxq0bZGio4xHRWyYHaAw+dSmYK03Fj2pRgeEYdqzuX804VMusQT6sC/WQ89Gf4vnF3xtxHU3ne7sfVzwD8VKdokSiBXD2efCDPzPj1JPANysgLS5uWlPfoaJ6mUE6yP+Bvi484CPPpAzO6+9Ttu4swMc3YNWh3ifdgPAj7vUATZq4MbZ2ZmLt2azXeDyAth+QJcwWkS4hhuPogO3zhyZRXcA0CWot3SWvgy+9Gx9GjDre+3Nivm4cZpoAdhwduUwUK1InXwYOJoOfsGWwGAuQI/1zTgo+kD8LIJfMYalk0EpxbPMzpvT2l2XtQDj36qezGygxsTT5PMaKaDLuEkBpEVbrU/XRKRS7bZLDZzhwhWM9Yo/VRfg7zAQN6mGqdMIQGRQfpkCoPUS83dHZnTc6/LJm16xihhNB+fEpoN1yJ0yAZLSmO6t29eERxCwUgC8P0Dd5Im2WAAlkfs2RoYLqtenoz7OOIJETKwojNYqLhWAhvhET5g6lQCYqDx2SinwB3huAQj9AVryJpLRBwKgc3MB6xxCuLcwq8ueuM3l1ALQsFs21GtXAe9nyGq4PkHaZrEkO4XNhwoNkcIr0RLCaHFi9GtIqL+PtfmTs3tx8yl+/7zW/IuNF6oD/BMA5vIFv5bxjwHMX6cH01MYvwK4xXHmM/h80MVefegKhGX37BGLm/fsLH4buHj7LPYub85mm5dtRm7NHh8ugOOjp/cvnyB99f7BAov921qVybYwsdzPhXpKiKiL/RqiX1+GKdiiFOC+AOaxaXhmf4DQJzAIWxp9IPqR3ilUV+typ1CgaAcKJmMBwM0lPEsLoG/5grxw19C45R6sxqORR/Tr80wGWeLpYEOqpSfwCn4hAhB5BQcOlFmrSDVJOiEAJ3ELf6swHXGltKTVAw0VapMposiBS59js8yj+fLVcnBaoKk2u4Qw8m0Mf42rLtTfeerk/gD2DX3oMbcu4MUIwNS6gBdC0Vm9v8S4JrJBVUAShiDXWrI1TfhlqQB06IzEvHfoIzUQqZpMP68f2lv1bLUABNF8pwUgXkIYejeHv74MhxAAKAei/sU5vZ2MiqhBbsu6cll3FJ3SHzyPgujHSXX0FlFNEBF1Sen0buZ8Ni0AVaCeBvP5Wp1vEncfltmVAsCXtS0TgHgJYbRWMfh10iWMApcwOq1L2BShM2vs2hqvdTHbHfVT3uSuKQTyVgW96zoBqHWNaQGIRkfmjxUCEG/1UhNVufIB9oBIAEo+Riu4BT2plS/GVP+pFwwsX09n3puIR/FZIgCjJYThCqfRAsPnIKg6s3Qy55lKSCuAoTt7mIrXurjtjoYJWfMCYL8c5xy1TgCIC8A4pLINvFhMi3i01UtBKgOSnlpMC0Ae+v2m3tW/JFK1q7vKPD89iQBE0XyXCcDpyImJ6tRX5/YfG/0YVV1FlBrfVMtgBgDhgpYgNVrr4pu/CV8/JwC+wV6uDQS29KiCB1NpLqSyLYclArCKJTrAEpK+gHdHaW0ehxMIQBTNdywAQVkURBXyaRWXbSoXCMDEV8f2H4t+HFVdTypTXEgad+tQVngqXuvCtzsaApF2RhUbhbvUEy1Li00LQKLDpIXvOQqp7IIqvHQB0GTmcTaiq5UE84Y+p3yM4CS6CgSg1S8RxzvWhuJ42RCAcFO5qGBGX90QVAj/cbRMSS+Z84/Lw7Zl0nQQKwTBdkfJwCefuQCkVoLKFdXVEFFmF+DGUTMoCKns1mwxAah6oqFxL7w8OSEAK6/NWkXKFJUriWZaAHTGzBghiuZrBKAm5wLHp+pz16KNrRC8UiMBiL66aP8x/uPEMqWSeIOQvIQBds2qs0awh9DIpR4Naet7HSzKMxUchlQeC4CzwmqpWZUcCcDqa70gt2tbgHCM4PoL3gJU5OLCB+VtP/1gxkgTVGosAOFXF+0/Fv74lhKaS3SuE0VEbTSxEix8JCJl/WtDAQgjZY8EIA3PXpmMBWD1tXwol0zpAKxGojFCTWMdoLD1jzRo4tyKwXIUBireVO6lw0bYlMGOLrsq8ZPOAxnPiulE1BTaQvKblfCISWFYcZ0aCwAUUc86/EgHGMi5j9jHL01aAbB98upriYjqBJmuxIlRABOA6Fe37I6cALB9Q0L8ikH1TIOD9ZjC5IpVr0j1dhMzn4oEwCdPLgCxuUQXEvkeJ3ahB3T/6rI3UvJq0h3E5O8uGn9NRNWapP2KBy0Aq092ExU6glFKRFQEdgAmAHH7oAuc2wGIQiXPegSl2zgwM0VfwHypmhRXYrj2LPp1XOMBmbqyNcd869Lr41Rw3qVluVlOug3g8ez22D3X+MvmG8DB5T3cOwsbiztTW1jlzhdEyo75IIxP9GcBvG9NEgA+maDcAPChddduw4TmvAdgE/cOAbxGD6bXTp2BcR40Dd04mi/Ad8vyAmBXDAK4CnzMnzC1vNCR37m0vQHMt66oeAC+luzOfFnqsvYXewLgaBc/B+DxbDa7+2QcnHMZPwtg/zr2oq5rAVzRTcDYhb4O8jNBFFI55J0worEH4OyaJABsPaBrAHCzXXPy28AcQufAOT0JfTS5duKMuczO44+i+QIArukmQPsD6EPJDg6dS+9TzJ1qftIqnq/34p3NZg9Z8j9Bb2J2+/HRKAUAKK4Ai7PAD0EHs713ddJLeZIfhf5s7oVNwBcAvFYDYxf6pL+01p0/DKkc8jYAumtdAPM1Scvx/gmu/T6Ad9krFgDOPD3G4unZic0ftGNCsKZhFM33+CF08FuDFQC7YhAALgO/ML73fBejSoyW1kS/RsmQfAM4PrsL7F0/G6cAANlrAD4NveZGVadrYeKm0HD1AMCl8YxBgndt4fj211ffNAqpHPB9mO1T9H4Zq5MA8OgYh5sXD3H8V2tO/hbM2qMUwDcA4PLm7Mzl6WwomC7GfSvXz87OnLv3w7Dbv2S3DoLde40AXMAR+4T3sWHPiKo4Il5acwo+AB2+eCoFAMkdAPf3APwhgPmV1/2izRMQN4WW808AbE+MTO893d+cCo4dEETKDvkWTAkksFHflycB4Mbm7BxwbrZ5Y83Jb8B49f5HaLerVbwJ4OcApJGK8F4AfwsA+CbOA/hV94sWgBr4I3b6HvDL5s81VTxeWnNSfgTc6TpMAcBvAXi0CwD3jNv09msnjxw0agotVx8C2EnwHQD37Rr12R5w+eLkljoBZ4HjJV3dGzAOcb8G4Ktrkqe6dvcY2KqB8gLiVT1j/hzAhQKJzaWN5rsFuyIewBNg3gC4OHOrryYiMNrP3VSxV+e5IcivaeArrpnavzzpLFoTKegRmdc7y87mwA72FB/5jRMjc4l/sjaOxOYsANZexvIa2vpD4/ALsANYVl/LLBa8DdQmLuIUo+FvGM3X2h0UeRP9K8DEisE9vdUulq2eMkysPTsV71qa6raAg6suef3c7O4T6AGTJtDYx4llTSH0wttXcWsBXOIu9YAOuP+xpTav9BPgmlJEBuAC0TUAj9cmT3Xtrls48mRdA7BijLDPdnH5HKLtLsamn9aISOxZjuArromICmPKOGULUPOvLUqhoYlp5paIuO1kVWJkLsmJqM7rFImx/MQu9aYgNB3iL3wcUjluIZ5hLiC41/JrjW94E+rB0y0AUCsaamcCD6L5uungsH2dmiBLfaCCFVU8Xnt2cgEINxIIU6G5suzKFCbaKloianQtrkpMWwJtjxWG22E5tCcsEwDeUY67iDqc0VuenAhbtPral8yU7ddYhldXcby0BqcQAL1/RQYkRR+nuCE+45MhLYupRrQiMXKdDATAtPJlp4iGvmaNfqb9PKcFYCJI/FvPQNyTLwnbaP19Z62KLHd5q5hTl37v2olXMbEJiJ0bWl3FE0trltd4kNEi0G0QpZYJwAD7WzOwE6cScVOoM1J06mX43Fc9kTJ+ka6VseWta8hNedgXZSH/89a9sGLbFwzEKqbuTfy9wdazWiYAdurEW+7sfHIN8LjV9veJ+V/Y2eGoiqNKjDSE6NfVSd4GI0qFAmCt0aZEG0VDZef8lidOCBvH5Gh9kWekP7RyIBVLTKFf1+KihKfRDVWkRnVcAMhNTHL/WSYAXA9yN0112bjp5wkBKNnNoqvr8PnexWvqm8inlhcGDyvipTXRr6uTgJv/c04xPPXcpL6ItYrJfEH8Nuze2YJypL7UjCzon6Pp05aXLlM3YgHQ56RhmlWA37ubnWEFwE/b83umdvsoU8+ssJR5gCKiQk8AuqjdRE2CfKjh+9q0sQIw6QMG2zCsrOJoac36Gn9GKFxBZHIe1kzi69u47zlP7kSfmRBx3/7CFY4TAPT8EgIy4yYZfiEqLHsyUeZaJwAFTJSHHG4fmnwgFwu2AZLa3CMloj5Fb6vLCEBK5Nto0jWYNloAlNZyVSAAjSllt3+ELx73VxHo17nrk6Z1G6MajFdPvQAoXszQEaVITBWmXdTs9nwC2tViKAAsPoG1KhFTl+yys8rewxcO8111btRmGU5lVtAHJkjzSTuRpMC1zgoASvM0uxFRomvcDafMcLTWFR0LwMA+mppc5M8UA1GrN2kLfHwz0zCgJFOsnS2PYEuRgcKtOk5NrvSCpwajGgC0uJANm+cPE9GAoidldmcZCYDdiaGGLWBur2+Z8BXLBMBvbmj3gTPxm51Lf2IlwjcAOVHHnZet4dB8npMCUBIpvicH36CQCYAdRbidqLy7RwO45fSmoCIB6CiyTrBdF6hSVKW6UeaH/Uu7sWbGM2ILLdSQXrEqiD/E6xhxZd2cz6/0yXRCsOAAACAASURBVC8uMZvnd3aWTqrXr21hvvNg0tCWAh3wfj1fexOHs4fYYSd+W88JAwBeXTZr28LMmiVzoAOAqwvgCvBJAA8BvY38vNTeImYz+Q+w/VkBPSF1Te+CfrAHvIF5hexCGPXrAtC/yWZG3gDmE94S/w4Idxf9a1hnEMf3gLOY2oN0GziyE37JHDgOJqp6vO9nQ8+UOtjefhPQ82HvYQ8CoI2M4eMmYgStquMcB7P9rQfX/K6mAb88eRQAsGH8ej4FALPZDNiczaw98meBFvgxbaDcxkPcOmBmX/wDC9o7EgArKF+G2fj1Q9DSoEukKbaAfRMqEsDHtEQY0/d7bUxGw/UFsJPgo9D+Mbv7uEJ3TKS+wmx9sQ189Q344IaXAVwZqVHZx+K5m79CEHft3QD+FphPBEM4bzwhACChBwA2iMg3mPvY/kkcsuYvvQS7u/ERTBCDbQCvxnd+D6yvgWPUArhFbeYFgxag0AueXAyr6GZeORp1AURua/kxgQpAlAItt03kRApm3/mG7w42AB1XlVz/7RVc4rGLGiIqEpZv+3J+WRwR1U4VYMNAt8orI2OCrdhNfSfBh4G2MyF9NhFRoASa5detr4bKj+L43cn3igNRlRKZf43cuQ4AdnMJ7QZY8bW+NhruhCoXxHcK6nglkwJgSmIsAHZsE9v4uQWPiFJ0Ok5FBgBZW8Du4KVv6fckIqIhV/6G9pHs0akrfE1CRIMbHQAZkWKhie0QrY8uA3K3yA8VEfFlb2YYZ3/2AqD1nSkBsDViNNVpAXAqQE1cbxuIKhARZV4AKmKntP4BSwUgsW9sCAN8nZiRACQUFEtwJtk/VOS/OxIArwSWA6nCXJZAkdEuC39TYsqYVX8odvRmmWx8WZhL2gkB8MWnYdVvthXwkYcqIqqMmkZmmQCvw+UCUNq3mBYAp+BNCEBHZsIrscXOlGYzsh30I0IBKPSZTABOt2NIR0TIexbN3ev2LdEDANtEfkE2O3Nh/13jegncu3uIxdPzaUPXjh+esd3ouzAHsIMzwP/lZz8+b/96A8CHtR+I87m4CART3UaXskfeZ7UFze5sNpsdAsBiNpvNzHR0Pvzq/zrjJ1O3gK/rIJ4ZAFwBnl79HIDP+Ps8mmkfqksVMLsL4MDdjPHRKP3EP/JwHzb0a0KXoN0XmVb81UCV+wyC7e03nxwBx09+F8D3gDOzh9BOtZvQRbeJEUELELkBB8mOiConn0Q0GMNzFjY9ehhYBmcCMCvboiUcdvI5+FTznqjmg5w8I1LUQrlPg4j8RoTmQBNtrpkFXzLiJkG3GUOgmCRE3G4VfP3Qg6pCn1XDhY7TizaIBj8MtMNDNwzUo1CtAyQDeXtNh2gYqLfi1oqM0wFaVxTmfWwLUBJNje0Le4ecQqOFa7mmu4Bol5EwycyWbTC9o6YEIDjTb644FgBFFJqkKxUGDOmIypJUo7dO0MdaCsbfGDXO5hAFls6ger2V1ut3jArIe139ubNhsEUrtlO1L1YTtUwAzEJyJwA52ShcDTNLmmXfsSGo9lXOldYJAYg6AIebcw4EwBmCqvVdQOTpbZOL+7PH8AGY78/uL4B5ifOz2W0Ah7OZHd4FZ87tv+NY+ukch8AH7IgsbelKd/8sH0J9B3h1G90hNmxdpsMO4gHU14AN4L2seSy0z/ev+3P2jqCDvgJxkPIpfvxLZ64DKG9uYb7zWwnMSFNjh6YZ9Ijz0njRAG9ug4jPe0+ho9cdT++PcxnAjm7e9hbw7z3mNxB0AMh0Y5DtxKsBAGhDxyf4gZEARG7AY6/gL+ziuu/KH+9i939gOjReeGYJvcXE2LPzw8BXgffabRw2zz2ZnQ+F71vAO9+NN78M/AdtBshenyi1vwaQYYtFa/84gGNXkiPOR+nd2Ww2mx3BhDK+ClzVff81HMzuLua/gbC2CuDvob3nbh0AbsMMzVkEY+7kArhH2WehN+f4GjCfyt4TAGYHoDdgZTgfn5lvIwxO/I6bTQqUdxDEurdcXwAbfWpC21umRgEZBT2jTtrwGFrHd/2JbYyjUUB4pnJ2gKALCFtd3ZRVA/UZgGKgIQf05qVEuTaAd/pau8qdQURlSr5DrIiockvtNDzugHJL9Hg3Pw5jmNt5VmbpTXRTDkVEXWomd3J/QtKY4pmeDHIL1TOanAzSN87de1HtJ4OCLoCvHY583SpEY6weQTe3ZBgYuQEHSTvNov+noGcfC0BwJnvqOgHQ3WxmMl+4XJsuXa+UzCfMEIMOQeLehZxy4hUKVr2Jz8eJBcCu6HY6Hh/22QgSDj+14UrcCUCqXymcDiYvACU5wY2mg08oAJW9i6MHuEOIn3DjAhB5eodJbmtJIt1+LADhmX68EDhwB/m302YFtL5XoSZlbmyMgV6pp5EANNrMY4+aWUA3BxRXb2FOHcLymAhkStQiNftEcY8Bp4RbiqDAOlfRPumdK+2MPXcIYQJgJvbDSjmBACBvB+9XMRYA7RKm+iryJYC/K6vxKDmq1pUtQCQqxWA0ab4jLuwkoF+eXhgTaW7iWBrjjvu87Nc8FoCCiJSzdTqPkJpJDa9eO8m4XgB0MaoECTmN29VUUg9Eqs21O4lzCeu1J+6US1jj/iLARIcdC0DgGlv3LBrfC4cJQOQGHCVH1bpSBwjOZHUVOHADDVFuJoQBAAUNiAXA7KGREPlBPpdNazQhJiE+Midv4Vj1KnPqegFww0BfPX5499YT5bAcSLXOSSY2CdSh7b1oANOxe+9I5kY3sYlClLRnJWML/wkFIHTg1q5HmS/NiS7Ahef0lT0lAIGvTuEryLs0L4tU/RywRja0lBCC2CZAHBHDCV3RDioIxdhFmSyD6orewTwyN7e0AmDiTEUxnzJdQ0bmFbth4u/G3IAnkvasJNLtcWIBiBy4iXqgYorYWAl0uhcvmQkBiLz11mCN5p17Q0vJJ+GoBZKyVcQn0vw22asEgMc24eqXe4EaYOZ6bqFkH3Jiq8u2faEAEFGfJb5XzYFg1QMfdydK/96WKTe9NUSkt0yP3YCj5FgADLrQTygAoQN3rAJgYhj47FCsKDh9Kuf+gMVqAbCqkBMAFhV5hQCs8Hw3eQsFgKsX49kdCma5/Rs1QwmgtU5azhExqBq4K5lhvLXC4bJWnlYJZLo9Ti4Ap3bgDrKRAtFqqaRk4WzDu8ZPXiIAo/DWqwWAx0UvR6pAEMqvBJBWvclYnwFJGWwaC/R1lphvlt/e3q4moi7RMezC+ElhqHEb+t0GOWvMyUm0JoNSALWbAgXgBbocbaIQJqd0+95pICcXgDGly03vP4ROkeqsQ0CQ/3Cw635S6WkFAEA20HgzDLuiSJMOde7V93BnhBUCEHTl+SgrEe6yUJd1uvZAROkKAWApa/waTEZHAmAbHdc8lL0VgNgN+KV4BQf59hs356YcWoD1mPHyhDRY9WxVQ1ckawQAgK5eJwDGJLNKAABv+gPvovN0XQvgYptE619HuFim2gTkPqVoz45lAtBwrcGsc9f9UTcWgFJP07fPEg8ubYZgQV2koLJI49EAGMibnqKlHylxAWgBJwC+x6zD0+0eBzVcGDyiJjOe+E2k2p1EAHBKAXDR93QBLBcAK7ddARZl2hG8W0ZEKrHXt9752QUt8BISZDVtFfUFem7u1LlviGpiX7lvWxvbUSg2nNVDXP/iFG0Vqh/qDU+1ywu5dWhulVTYbnf81OBD6AMBIJZNs5wlqbgAmIpHZ6q10de0vgyHSLV7GQLQBK9QEqkh2PXP38n1N/1EDIxAAFj9J6SnPUyF6ry6GgkfABREfYK2VLwFaIkoqUi7TzATjy2KkqhB0tLpBYAZOmuAKb3eJKjJxpoouxefreECYLahaX1QZiBh7ab1kO9ZnsMSpUi1O4kAnLYL8BYmmwf9klOjNB/bZLIFsFKTKFf/xumws9+N8+/3llf2AOsVYsrcFG5LRDVRz65Bzp/vdYDTuYTh49CuS4903LFsGzi6PTswnvH1HDi8PXsK7XoN4GA2e3gMzPU3evBQTyxb9/H0ChaBe4D3kvoZYKH9o/a8N1Y+B472AHzDOFhvjxYJ6NvNZrP7x3BhTlaT7cJuKG+KxbQod7hsM8bbZAMA5ncmpnV9bJO/Q+SAkMJ7Lvz6HLhnZm9/CjgAvmjCF+L7AN5hrxnl5ZPA4R70e/vgQ28CuITjs2bzPxAR3QTwOpEWg08fLHD0aB9Y1wIA4ALHTOF5Cf2dGFO9HYTYC9J4TRSsLuBbpZ6oGJi7ql0k1bptO0PcvJ7Zt9XHZtBZIqI2+q7XtQC+rWANVBt4Yyv/7o0tGdZWlG2eAMVAwXLfUb7HowB+GvneQPcAfkFkTWwCuo+vtD8q4sPAjEi3KGYahAJCOT2VAATLzPxjzbKsaM/BaE3U+MUrsy7LCkBKVFsBIKIy7xQNXAx8ybuuiP+s13WFPfsJBSA0BJ1KAFhZuB1uzO9BbJMoIkYwS52wvytyA+jevmoNaPluwgcAtrrMb0Q+CnGXBPGmuQC4UdSpuwAEPlGYGwefNwH8BD5o/sKXoQO/GaI1URum3U6uAL/J73zv2C0HSgH89M3tOTYu+DgHJZyX0w0TgfLpRX95uwEcrA9YOmJx+GRmnMTCHc5NGLkzowsmb/MF6EVJjFe3r71ORHfmwAHwOwC27hA9eG0LQLvDgj69C8A/mr9/yiz6+iKwlUD7r70X0LEUw1B6Gtvy/6EutsWuyeL2AxdnanYfwF0bFC/ovk4nALsANryXbAYdxxNHALbwTvMX7iFYBBWsiUrbuXHL/gzwOHRa+kvMjXq4CRfW2TtMfVS/JQA0xlvqkv+8qx3gmDl5nSzAzmw2O3Nu7LK9EjV59yMAb192yfF5YJeHTW13gKdTz003jGfhDZiozvvAVgrgg8DxLZcBozEaFagEDu5pHeNPAdRb7n5PrgPAp4CHrN73rCycOW0LsA9gfo3MVPc7AHw/GVT+jwD+DX4IXo65+/+eSw5Er+8Aj24AKLdwxEKXAcBVG7jbvNxd7XBqGsd0AzjWb1FdAJ7MZo8W2LAD8uIKsPgv/mKm2r1ovo4pf9ItsLfXXL3/9PAYWBw+3gSAW7MnRwssjp7eRrEDPPXhXu/NZjPjTvhLsL6RhyZe5MUF8J+1hv27+pzvwAnA53Wz81Et+9vA4jqQX8L+7MkRcLx/9yoAVHM8Gcc41t1yYGRbpwP4cV9vDbJ1SdR5bwF3LbEJc9dpDu5St4kv0wGATg/HWr8dgu/4uCmNd4s+Zr4eR51+GDh+y9MYgqx2M4x1AHMdn5BPdZF4z7KYIZgScha1whsGmAaUAA0Nif5HP7kEkHTx+rtqIj7y0MHe/RQCoNVdUz0FEdXJoPJTCYAux8YohoEA5ERlT9SyaB7kbKJ+9JDyB5WAsaOk/BlEKwxBemz9rAIQmoJpKICkGHxGo1FAFViAayrgty5Kyz4zL5SPq4OossppafQ2BO+YACh6ot59GCe27eYmu6dWAm9sPtQL0z9lWry9zTO33gEbaPcdSy8EgM3Z7O4BcKEF3gZcISLaADZced1aGFOAHdoCC73SXRsBzJL4YHHTDwNIPwXgXqDcLA4fW9XOU5quO/LYPi1PANysgLS5uQlsvEb04LUNAL+pW8gtBCOFdwY+8/8WH4IOOX2JiF6/thXe+pfC5E9NZ2DzyZHTRG+cnc3Omr50QmMFYFupCoVXqG8CfwIYATiYzWaziRCm09w6P3sKYF7guzDxY98O4J/wHTA1iKnKCU/eO3+43FEfb2BDl8gxW0qipfrn4cKsfhVmDXwB4B+AJJ0Dd1n9z2azM+ciBQMAfvj1NgeSZokpxw2X4kmbivTCxwu6Xq8eAbhC9HqwGuL47tgPPyGiC1pRhv68d/BtALtPlxTAB8PkxpKCunr2jAly7bNuTtWVXLALk+F9AFL1Prz6uulFmms4vn0LeIYWAABweR/Aj2EXJnTHFoAjfMv8Ze1Plg+FyS9i+ZocF3fiK9CDjBx2nLNtRjjQa2UuVUDxcQD/E/hvc+D+VIUCsMEVTIO5c5PowQVMrpo5OWdZdI7bj7Wi92hzIgd7Rwss9u1Y9ZtHwGL/MgBcvn+wAI4Pn9wNB65nZiH3cHY2m81m143irs/KrDGmGM8v6kp2VQ3kDzYA5K/PAbtdRnkBBzY6fmQIsoEV+Vr/CTc642V3MkNQQ+Fa+yAZ6ABwUdBSIhpSbUNJ7T3dVcwLpw33VaPxdLAjYXOpdrbcnzl2CPE6QPgEIN40+4WjPWbg1Q0bVjLpACTKL2bMgKaCaQGKzm5C7beiLokoR0WkMiSDiyTlZjAjAXC7zTLnDi8AqZU8E3/pNKbg3AprQ3zmMhIANy3s15q29jymN7ua7HAaAUBW9wMZL5OXBfP8XLbfHafo0VbhHcykqgkgYmZ3cvPLoH9vBh3qIkNKpEoQZflAVCDRWvTgv74hQWvCUaAl6hN7FMBIACL3AwCBABA1ufmRMuN5krgIm8Z5yUQ/idZEFTSUKQuQZ4gEAK7K7RfZu2wGw6lmIFJtAawWgBPiX1Ffbm5mCkBPgeSdoj6PgyRwB40Moecn9wmdFoC0MVnmG5jqIBiVs+LnWiJy+P/tMEClALKOSBEpoqEwlazrvE/Mt86++NJHk/PjDiYAIF2ZhX2hWAAcvcmqyQmA1dPB0ZIjSywArc0PCucR9qIIduQNAh/EDd+EAJjaTKIgCZEAcM/PwAt0SgCMH5bu95RbqpNYjwjlWoBUEVGeusVCJVGBTNlqzToiW/36185U9TIBcMPAkQCwF7KK26QAhIFuzRg8XeEQwgQgmsE5+YAsDI4ZbP6rSCUd9SlaHdW7IqafdOaVNVWQIpWyQb6ZYBwLgH2zJAp9EAkA9/wMfEJHApCZ+aahQmFu2blNbY2tgLn5KpOH3BS7iU6xTgBMY9/wLsC81DAtAL7ztZ1E4H9QtoMKQl2f3CUsrbpBkepPFAY/bQZSLdOGTC0zAQg3/1WkFBGpzlZcr6vaxf+NduRljvODrhcnLv72TACImhQojQCojLmxAlre+sjzM/AJjQSgNF65pnCSyqYToNDVHLh5Wr3AlPtAuc4XMNkF6H65B6aVQJNn2HIJBEBHL+frVF74YpoRoeMR1fYTHHr+IYYCEG3+q/gNBrgYHD2xBWAN24mnK7MESI350saWU+4LiQVA/50lbrVUvKTWOiu6ggt8QgMBMB9/wwcRaW1VP94CeHJeErwFWK0E2sY+J+om9oV+XpKqR1cHgyHFx0+swgLnyaIn6jKUg26vlwmAhd3b3W+gYPNfZY3RSW4uKIiocUpttCOvw8RBSP1/5sdYANwVYegDdxO3csk1cIFPaCAAA0Vqn7lNo4go0AF8SQctgNUBdKSB6WGgD443dADSoUO5LGh36Nma6A1LslVHACCt7duoxr9NF4X2nnqG0aEa+7mOBaAvEq1QZ+gmwxu7mjWzBYooR2n94Gx/R245t3OutePbKA6CDjhYeQmLBMBbssLQB/Z3H6HZt9vcJ/QkAqAbAeg3rgI5TQIdIBwFmFJIbTkX7l9X3ubfYlnvGwhAMMZecgTITIvlvDDtC9VMyctZwfFnhPVdwPW9QUAjaL/GYrLd8tHzdA+lzHbpnY39BdstaLENZrnUeFDS2KK3XXgkAP7VwzUv9jmF+40X8pL97rTkq+CLsmpAP2UHYKOA3NkBlHcYXmkKPgG8clqiOgWSUtmyGB/JG/vxtAVLdAVgKkFTMWFgzyiIhsRoaeaUSQEobe/V8KUgWmaiwBpcAJQtjIx8JQbBxGm8HZqLAGu72UgA/AcyEgCjbgKTqz9SPR6JgiJUoRJoR4QmnTRWs9YCENkBEuW3FzuBLbIlUu6bmz6fVU7ttf/WdprREesvN7jOP7WSTh1SG8ujB1pWHOwZDVGpSxhmcfBYAErXQNMJBCCZFADoU+0zeQsQBT7Qh6uM/Ad8YgHo2K+T67/G+90BQGaGW0OF3A4Dxz20FgDXDWpLoJ8LKF3xjgqIiEyM51MJQGJiGdJQAZ0OiaiAvNNG+Y4Ka6+PM2saAugn61Lq2QOZAOjXSa0AKIwFIKzf9tkEoCNyQ7VIB4gCH+gc9DUb2Z1UABri/QP3/Fy+350tkqWGII03BIVzAVOsE4BlvDIQEV0DdnRefg2fA7CY3T5zJcc5XAF+DZ9DffPs78xuP/2mPgJMO0aapxwDKbYBpNgCdm3e3DMKnAG+C3wTRlgmKLejA3vhJNmN8ea/y24y10U2sX3v9wDY9wH+Ath6/9LdwZdSXgCOz7kk9/wMfEJbABfoQTD9f/3sXTspefDwzNXJlzCcNx5de/pRFLGyIzi/zE0AQOhBRYRBARkpJEqHfwUGhdQ/oWUm7r5yGwyzLgAtUZESDVQm5EM8ceHso31tMWoBWqI2Mf3INPHmv+MWICH9TbNd2LwdIAp84As183+6/K5qAUIPtGD3sxX73TEmJoPWcyoBWEnsD7BxDABzeqDu7wJvIsXGMT7st5p9Eykuzx7uLwBsXbmj2gJZox5c2waAg0ezc8CbwNZP4Pjr2H7fVFjIE7EJ/N4e4FyDDcwOMLn5b8BnAPze5QVwLQHiHXn/GMD8dXrAdkTXHqTP4FcewDw/Q5/Qzf0Fjp9cHF1w4yzOr3FLfnHVvQzfP1OvW4COagAVpaBeR8jTVFZJWjoMRE7UNtQUNJT8I12mA2hYC1DpM2o92m0TpLXVN7ghKNr8d9QCmGi73oMznAuI4iDADAy9E+MztgCnw185/mvVkReNrxzXBZgg2FNdgIUbgrjViKjvqUiIGj7xPzkKcMYQJgCjKX4/lJieC5gUAGec44O0YDbwpQQ+SJTZ9cSs8HX/sq2YMq00Vmbnhx8sAagpR0YK6KnS7UFNOWoaMiRVoo/w9x2bgo1Y6w0ewlW0YzvAkCEpmR3ADM9tj9nmKwQAwea/sQAMtt6zMBtLSFvlfGttzCij1PY6uumASo/wWl1/pbXDJdT5HUTMDjYTAkBE1CeltnNXZgx/MgF4+cTDQKWj9S0ZBq6jJx8/fuoZcafWwc/CDUYA0ChStZ7peqG7/dZEvRn890Rk1qEbu6CqEqQtweiKNrRngcasW+3dJJ3fwFL7fQ9aTINwbfxfvhVT6d57SgD+OTidISgeOIRJPTJuo0iXk3MBhRoJQNLxSbYI0l+RMfgPAGpltuaBjaHj/mRZIjfRkywRgPgdEqK21B1YTx0S3Zqwo3qErWls6D0bfKeaEIBgK6aiJz7L/YPFelPwOgEofYGzKaap2cCkVW4zyRHKOtKk9j8nAJQWZsswci219onQf59eAPrc2+Ya/q3n2qzV23cw7UJr6j+xV5jZu6wnGoqpLuAHlVH1eQUs/mC5f+YqAXg+iFwQ5i4SAN0dJaRU3Q00ICeVmvGKNU70UzlcLwDma0wa7fbHevueCmRO87CuEaX3l1N6RhtIhn+u0LHPxUT1nXQ6eC3mM+mJErdf60BEWZxC0irq/LIyE1K6WiYAtaKKBtTa5WeACVdb01ijP5kA/OtlamHI3uWzs9nmxd1VR0ofcipplfZmG3WkO8AukG9hscrKCSB9sDPH9h3eUJZzbb6d5LPzxZ+HN3gNODh3+TFwYVUoNsvubDa7iLOz2Qw3ZlM7ev2rxsQdAwCUxjuvd4HR1eBi3GsBMK5Z1VgAGrcfUoPVLUBvQmECbr7U6ILkpsV7+BYAfZMEXYAyJqeCYj16sgUQOJWiLgWSVqkGzlNClWZERL5zNTWsgLZOrU+ynbVNYwEwO6tluqptlZvGPEgldghYuAUAZof3gtw+LNoL0ggAkHAl0IfAzXy0LU0sAEJMa6pPkS7z+DvuiwSJnr5pC+0InwOAEYDJaD0AXIA7G4rcf9JDnMqsR26lFe3MTaw3+mzz30gA0LBhoPBMmBa8r21LHo+IAAClN6ZZb2XFN/ihCT8IIqLEOVQmZO1fdt/FIAWYFsDsCpU7aSzg/hNeAg1RbjbAThJFQzwi0gnb3vdEVls/pQCY2Ke138PWpzB4HUD5WdXBmnswcXfhBdG7HSQAVNPj+GTg60TNApRxFzAefTMBaN1yjWKUslMAujEQHe0tZaAGzkxXEI1GAWBr0ACgCnWA5UpgKADK6vgKoxSQtq5lEd5aRi3A1LxIMBtjNAMVDgPLSZuS8ANPbQKLE3VIVRhtm/RoXhlVIO3yxLh625NaBFY84V8epvvtK/shR6MA18cX3pc+CQRA+JdNbXrwnkjv36UP21EAEwAT8KKRgff/X5SDjnXRKPUyNoURBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQfXF/jAAAADJJREFUBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQ3iL+HyK+xjjH2KXDAAAAAElFTkSuQmCC",
   ["fnt"] = {
      ["char"] = {
         {
            ["xoffset"] = -1,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 32,
            ["width"] = 3,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 30,
            ["x"] = 502,
            ["height"] = 1,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 46,
            ["page"] = 0,
            ["id"] = 33,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 507,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 133,
            ["page"] = 0,
            ["id"] = 34,
            ["width"] = 11,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 228,
            ["height"] = 7,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 76,
            ["page"] = 0,
            ["id"] = 35,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 128,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 36,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 266,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 73,
            ["page"] = 0,
            ["id"] = 37,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 285,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 38,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 319,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 132,
            ["page"] = 0,
            ["id"] = 39,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 240,
            ["height"] = 7,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 40,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 298,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 41,
            ["width"] = 8,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 280,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 111,
            ["page"] = 0,
            ["id"] = 42,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 450,
            ["height"] = 12,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 43,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 99,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 134,
            ["page"] = 0,
            ["id"] = 44,
            ["width"] = 6,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 20,
            ["x"] = 165,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 129,
            ["page"] = 0,
            ["id"] = 45,
            ["width"] = 9,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 15,
            ["x"] = 392,
            ["height"] = 4,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 46,
            ["width"] = 5,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 20,
            ["x"] = 348,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 55,
            ["page"] = 0,
            ["id"] = 47,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 0,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 99,
            ["page"] = 0,
            ["id"] = 48,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 60,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 94,
            ["page"] = 0,
            ["id"] = 49,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 293,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 96,
            ["page"] = 0,
            ["id"] = 50,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 195,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 99,
            ["page"] = 0,
            ["id"] = 51,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 105,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 98,
            ["page"] = 0,
            ["id"] = 52,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 120,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 53,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 321,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 97,
            ["page"] = 0,
            ["id"] = 54,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 150,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 96,
            ["page"] = 0,
            ["id"] = 55,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 165,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 96,
            ["page"] = 0,
            ["id"] = 56,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 180,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 71,
            ["page"] = 0,
            ["id"] = 57,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 464,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 113,
            ["page"] = 0,
            ["id"] = 58,
            ["width"] = 5,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 415,
            ["height"] = 14,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 59,
            ["width"] = 6,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 461,
            ["height"] = 18,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 114,
            ["page"] = 0,
            ["id"] = 60,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 373,
            ["height"] = 14,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 137,
            ["page"] = 0,
            ["id"] = 61,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 12,
            ["x"] = 75,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 114,
            ["page"] = 0,
            ["id"] = 62,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 388,
            ["height"] = 14,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 63,
            ["width"] = 11,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 387,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 64,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
            ["x"] = 311,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 73,
            ["page"] = 0,
            ["id"] = 65,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 302,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 66,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 336,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 94,
            ["page"] = 0,
            ["id"] = 67,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 307,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 99,
            ["page"] = 0,
            ["id"] = 68,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 90,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 94,
            ["page"] = 0,
            ["id"] = 69,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 265,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 94,
            ["page"] = 0,
            ["id"] = 70,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 279,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 71,
            ["page"] = 0,
            ["id"] = 71,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 494,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 100,
            ["page"] = 0,
            ["id"] = 72,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 0,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 73,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 335,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 95,
            ["page"] = 0,
            ["id"] = 74,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 237,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 75,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 400,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 95,
            ["page"] = 0,
            ["id"] = 76,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 223,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 71,
            ["page"] = 0,
            ["id"] = 77,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 432,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 97,
            ["page"] = 0,
            ["id"] = 78,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 135,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 99,
            ["page"] = 0,
            ["id"] = 79,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 75,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 94,
            ["page"] = 0,
            ["id"] = 80,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 251,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 81,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 328,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 82,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 368,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 99,
            ["page"] = 0,
            ["id"] = 83,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 45,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 100,
            ["page"] = 0,
            ["id"] = 84,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 30,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 100,
            ["page"] = 0,
            ["id"] = 85,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 15,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 75,
            ["page"] = 0,
            ["id"] = 86,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 200,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 75,
            ["page"] = 0,
            ["id"] = 87,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 164,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 74,
            ["page"] = 0,
            ["id"] = 88,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 217,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 74,
            ["page"] = 0,
            ["id"] = 89,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 234,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 71,
            ["page"] = 0,
            ["id"] = 90,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 448,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 91,
            ["width"] = 8,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 289,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 55,
            ["page"] = 0,
            ["id"] = 92,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 15,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 93,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 504,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 133,
            ["page"] = 0,
            ["id"] = 94,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 197,
            ["height"] = 7,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 129,
            ["page"] = 0,
            ["id"] = 95,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 28,
            ["x"] = 402,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 96,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 327,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 116,
            ["page"] = 0,
            ["id"] = 97,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 247,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 77,
            ["page"] = 0,
            ["id"] = 98,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 59,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 114,
            ["page"] = 0,
            ["id"] = 99,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 334,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 100,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 462,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 117,
            ["page"] = 0,
            ["id"] = 101,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 184,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 77,
            ["page"] = 0,
            ["id"] = 102,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 73,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 103,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 477,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 77,
            ["page"] = 0,
            ["id"] = 104,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 87,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 54,
            ["page"] = 0,
            ["id"] = 105,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 45,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 106,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 31,
            ["height"] = 28,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 107,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 492,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 78,
            ["page"] = 0,
            ["id"] = 108,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 0,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 117,
            ["page"] = 0,
            ["id"] = 109,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 200,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 115,
            ["page"] = 0,
            ["id"] = 110,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 306,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 116,
            ["page"] = 0,
            ["id"] = 111,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 232,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 77,
            ["page"] = 0,
            ["id"] = 112,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 101,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 113,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 432,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 115,
            ["page"] = 0,
            ["id"] = 114,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 292,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 114,
            ["page"] = 0,
            ["id"] = 115,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 347,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 116,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
            ["x"] = 432,
            ["height"] = 19,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 114,
            ["page"] = 0,
            ["id"] = 117,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 360,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 115,
            ["page"] = 0,
            ["id"] = 118,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 262,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 119,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 81,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 117,
            ["page"] = 0,
            ["id"] = 120,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 216,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 51,
            ["page"] = 0,
            ["id"] = 121,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 295,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 115,
            ["page"] = 0,
            ["id"] = 122,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 320,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 123,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 221,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 124,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 87,
            ["height"] = 27,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 125,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 143,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 126,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 14,
            ["x"] = 262,
            ["height"] = 5,
         },
         {
            ["xoffset"] = -1,
            ["y"] = 123,
            ["page"] = 0,
            ["id"] = 160,
            ["width"] = 3,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 30,
            ["x"] = 498,
            ["height"] = 1,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 25,
            ["page"] = 0,
            ["id"] = 161,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 506,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 162,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
            ["x"] = 385,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 71,
            ["page"] = 0,
            ["id"] = 163,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 479,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 112,
            ["page"] = 0,
            ["id"] = 164,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 436,
            ["height"] = 13,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 73,
            ["page"] = 0,
            ["id"] = 165,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 268,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 166,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
            ["x"] = 306,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 167,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 398,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 124,
            ["page"] = 0,
            ["id"] = 168,
            ["width"] = 9,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 473,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 121,
            ["page"] = 0,
            ["id"] = 169,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
            ["x"] = 33,
            ["height"] = 16,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 170,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 501,
            ["height"] = 14,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 110,
            ["page"] = 0,
            ["id"] = 171,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 479,
            ["height"] = 12,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 133,
            ["page"] = 0,
            ["id"] = 172,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 13,
            ["x"] = 213,
            ["height"] = 7,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 129,
            ["page"] = 0,
            ["id"] = 173,
            ["width"] = 9,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 15,
            ["x"] = 382,
            ["height"] = 4,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 121,
            ["page"] = 0,
            ["id"] = 174,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
            ["x"] = 15,
            ["height"] = 16,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 123,
            ["page"] = 0,
            ["id"] = 175,
            ["width"] = 9,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 488,
            ["height"] = 2,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 136,
            ["page"] = 0,
            ["id"] = 176,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 132,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 121,
            ["page"] = 0,
            ["id"] = 177,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 8,
            ["x"] = 0,
            ["height"] = 17,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 138,
            ["page"] = 0,
            ["id"] = 178,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 32,
            ["height"] = 11,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 138,
            ["page"] = 0,
            ["id"] = 179,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 43,
            ["height"] = 11,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 180,
            ["width"] = 8,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 310,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 181,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 372,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 182,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 357,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 183,
            ["width"] = 5,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 13,
            ["x"] = 354,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 184,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 25,
            ["x"] = 319,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 137,
            ["page"] = 0,
            ["id"] = 185,
            ["width"] = 9,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 54,
            ["height"] = 11,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 113,
            ["page"] = 0,
            ["id"] = 186,
            ["width"] = 11,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 403,
            ["height"] = 14,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 111,
            ["page"] = 0,
            ["id"] = 187,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 465,
            ["height"] = 12,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 188,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 338,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 189,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 322,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 190,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 274,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 191,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 374,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 192,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 189,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 193,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 240,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 194,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 206,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 195,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 155,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 196,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 138,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 197,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 257,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 73,
            ["page"] = 0,
            ["id"] = 198,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 251,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 27,
            ["page"] = 0,
            ["id"] = 199,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 129,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 27,
            ["page"] = 0,
            ["id"] = 200,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 115,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 27,
            ["page"] = 0,
            ["id"] = 201,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 101,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 28,
            ["page"] = 0,
            ["id"] = 202,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 87,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 28,
            ["page"] = 0,
            ["id"] = 203,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 45,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 204,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 169,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 205,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 182,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 206,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 195,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 207,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 208,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 208,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 352,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 209,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 414,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 210,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 399,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 211,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 384,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 212,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 369,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 213,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 354,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 29,
            ["page"] = 0,
            ["id"] = 214,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 15,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 113,
            ["page"] = 0,
            ["id"] = 215,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 421,
            ["height"] = 13,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 216,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 411,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 29,
            ["page"] = 0,
            ["id"] = 217,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 30,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 218,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 459,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 29,
            ["page"] = 0,
            ["id"] = 219,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 0,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 220,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 474,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 221,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 223,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 96,
            ["page"] = 0,
            ["id"] = 222,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 209,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 223,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 231,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 54,
            ["page"] = 0,
            ["id"] = 224,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 60,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 55,
            ["page"] = 0,
            ["id"] = 225,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 30,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 226,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 476,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 78,
            ["page"] = 0,
            ["id"] = 227,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 15,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 78,
            ["page"] = 0,
            ["id"] = 228,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 30,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 229,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 1,
            ["x"] = 251,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 118,
            ["page"] = 0,
            ["id"] = 230,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 150,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 231,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 361,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 232,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 428,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 233,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 460,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 234,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 444,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 51,
            ["page"] = 0,
            ["id"] = 235,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 247,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 54,
            ["page"] = 0,
            ["id"] = 236,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 90,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 54,
            ["page"] = 0,
            ["id"] = 237,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 75,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 53,
            ["page"] = 0,
            ["id"] = 238,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 105,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 239,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 447,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 49,
            ["page"] = 0,
            ["id"] = 240,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 417,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 77,
            ["page"] = 0,
            ["id"] = 241,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 45,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 242,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 402,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 243,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 387,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 244,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 357,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 245,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 342,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 246,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 327,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 117,
            ["page"] = 0,
            ["id"] = 247,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 167,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 248,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 468,
            ["height"] = 17,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 249,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 201,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 250,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 188,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 251,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 175,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 76,
            ["page"] = 0,
            ["id"] = 252,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 115,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 253,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 0,
            ["height"] = 28,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 254,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 73,
            ["height"] = 27,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 255,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 42,
            ["height"] = 27,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 28,
            ["page"] = 0,
            ["id"] = 262,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 73,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 53,
            ["page"] = 0,
            ["id"] = 263,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 134,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 28,
            ["page"] = 0,
            ["id"] = 268,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 59,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 53,
            ["page"] = 0,
            ["id"] = 269,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 120,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 273,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 214,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 286,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 489,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 287,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 58,
            ["height"] = 27,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 304,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 156,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 115,
            ["page"] = 0,
            ["id"] = 305,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 277,
            ["height"] = 15,
         },
         {
            ["xoffset"] = -1,
            ["y"] = 75,
            ["page"] = 0,
            ["id"] = 321,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 182,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 51,
            ["page"] = 0,
            ["id"] = 322,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 263,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 338,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 384,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 339,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 116,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 350,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 444,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 351,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 348,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 352,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 429,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 353,
            ["width"] = 12,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 162,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 376,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 172,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 381,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
            ["x"] = 290,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 52,
            ["page"] = 0,
            ["id"] = 382,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 148,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 402,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 92,
            ["height"] = 26,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 710,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 277,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 711,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 299,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 728,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 371,
            ["height"] = 4,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 123,
            ["page"] = 0,
            ["id"] = 729,
            ["width"] = 4,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 483,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 133,
            ["page"] = 0,
            ["id"] = 730,
            ["width"] = 8,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 1,
            ["x"] = 188,
            ["height"] = 8,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 731,
            ["width"] = 6,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 25,
            ["x"] = 335,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 732,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 360,
            ["height"] = 4,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 131,
            ["page"] = 0,
            ["id"] = 733,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 288,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 937,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
            ["x"] = 417,
            ["height"] = 19,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 119,
            ["page"] = 0,
            ["id"] = 960,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 133,
            ["height"] = 15,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 128,
            ["page"] = 0,
            ["id"] = 8211,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 16,
            ["x"] = 420,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 126,
            ["page"] = 0,
            ["id"] = 8212,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 16,
            ["x"] = 438,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 134,
            ["page"] = 0,
            ["id"] = 8216,
            ["width"] = 6,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 151,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 135,
            ["page"] = 0,
            ["id"] = 8217,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 143,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 134,
            ["page"] = 0,
            ["id"] = 8218,
            ["width"] = 6,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 20,
            ["x"] = 158,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 136,
            ["page"] = 0,
            ["id"] = 8220,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 90,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 136,
            ["page"] = 0,
            ["id"] = 8221,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 104,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 136,
            ["page"] = 0,
            ["id"] = 8222,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 20,
            ["x"] = 118,
            ["height"] = 9,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 8224,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 343,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 8225,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 371,
            ["height"] = 23,
         },
         {
            ["xoffset"] = 3,
            ["y"] = 137,
            ["page"] = 0,
            ["id"] = 8226,
            ["width"] = 10,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
            ["x"] = 64,
            ["height"] = 10,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 132,
            ["page"] = 0,
            ["id"] = 8230,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 20,
            ["x"] = 245,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 76,
            ["page"] = 0,
            ["id"] = 8240,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 146,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 4,
            ["y"] = 107,
            ["page"] = 0,
            ["id"] = 8249,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 501,
            ["height"] = 12,
         },
         {
            ["xoffset"] = 5,
            ["y"] = 110,
            ["page"] = 0,
            ["id"] = 8250,
            ["width"] = 7,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 493,
            ["height"] = 12,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 72,
            ["page"] = 0,
            ["id"] = 8364,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 416,
            ["height"] = 20,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 133,
            ["page"] = 0,
            ["id"] = 8482,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 172,
            ["height"] = 8,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 8706,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
            ["x"] = 447,
            ["height"] = 18,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 93,
            ["page"] = 0,
            ["id"] = 8710,
            ["width"] = 17,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
            ["x"] = 399,
            ["height"] = 19,
         },
         {
            ["xoffset"] = 2,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 8719,
            ["width"] = 13,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 124,
            ["height"] = 26,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 8721,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 109,
            ["height"] = 26,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 124,
            ["page"] = 0,
            ["id"] = 8722,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 15,
            ["x"] = 456,
            ["height"] = 3,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 8725,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 491,
            ["height"] = 22,
         },
         {
            ["xoffset"] = 6,
            ["y"] = 130,
            ["page"] = 0,
            ["id"] = 8729,
            ["width"] = 5,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 13,
            ["x"] = 342,
            ["height"] = 5,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 26,
            ["page"] = 0,
            ["id"] = 8730,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 2,
            ["x"] = 234,
            ["height"] = 24,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 139,
            ["page"] = 0,
            ["id"] = 8734,
            ["width"] = 16,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 0,
            ["height"] = 11,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 8747,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
            ["x"] = 306,
            ["height"] = 25,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 138,
            ["page"] = 0,
            ["id"] = 8776,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
            ["x"] = 17,
            ["height"] = 11,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 92,
            ["page"] = 0,
            ["id"] = 8800,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 8,
            ["x"] = 485,
            ["height"] = 17,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 8804,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 51,
            ["height"] = 16,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 120,
            ["page"] = 0,
            ["id"] = 8805,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
            ["x"] = 66,
            ["height"] = 16,
         },
         {
            ["xoffset"] = 1,
            ["y"] = 0,
            ["page"] = 0,
            ["id"] = 9674,
            ["width"] = 14,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
            ["x"] = 16,
            ["height"] = 28,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 51,
            ["page"] = 0,
            ["id"] = 64257,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 279,
            ["height"] = 21,
         },
         {
            ["xoffset"] = 0,
            ["y"] = 50,
            ["page"] = 0,
            ["id"] = 64258,
            ["width"] = 15,
            ["chnl"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
            ["x"] = 311,
            ["height"] = 21,
         },
      },
      ["page"] = {
         {
            ["charscount"] = 256,
            ["id"] = 0,
            ["file"] = "BitstreamVeraSansMonoBold_0.png",
         },
      },
      ["common"] = {
         {
            ["scaleW"] = 512,
            ["scaleH"] = 512,
            ["redChnl"] = 0,
            ["pages"] = 1,
            ["lineHeight"] = 31,
            ["packed"] = 0,
            ["base"] = 25,
            ["greenChnl"] = 0,
            ["blueChnl"] = 0,
            ["alphaChnl"] = 0,
         },
      },
      ["info"] = {
         {
            ["bold"] = 1,
            ["face"] = "Bitstream Vera Sans Mono",
            ["italic"] = 0,
            ["stretchH"] = 100,
            ["spacing"] = "1,1",
            ["outline"] = 0,
            ["padding"] = "0,0,0,0",
            ["charset"] = "",
            ["size"] = 32,
            ["smooth"] = 1,
            ["aa"] = 1,
            ["unicode"] = 1,
         },
      },
   },
}
