return {
   [0] = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAAAAADRE4smAAAgAElEQVR4nO19TcguyXXec7W5MiZcGcwd7IiRsMzVwhj9LISdLELGoOBFZAIRWAs7Kw9lyCZ4Flm0MCFaZNHeBTK0vAlZtHEMwS2CwaQFDiQtAnF6CMb0YAX14CjU4OCagEjd1cmi/s451d/3fvdKMyM754GZ+1W9/VNdderUqfNXAMNKNJW/3QQNt8d4DOlvoln85gMAzDSKx0VQqwkUgIMIADHIUr16jXF38NQet9OMjXb+1oVoxCjaku47xX0EgYmiKNGEgWjN5TmXl3ZJoF3cUr6ZjnsvOelshVG3Qj0AY3c/67CMhcLJG5bbzz7/pE2/ZYvxHHhFpJ0C+NBkzGz8sQX9IBeJiFL1QCSeiYMW3bM46ORvITryRyHeJIA1l9f2OEd08C5FHtuFf8mS72Pd4El/ysrJaCVy/NO3XG7P9LRg0/0OF1iVpwWrvMQF3nhg5qPdPQDAoi9gHZYwUgCipJOFvOPloAYGnojEaHmasdPcE8AoajgxlBvjCLflr1H0PKoJDACRVvYWR7Tmj8IkvrU9y9erycPtFEUX7qSH8qSoZngMzu0x8mlAimoAHKyhB1GmgvJMAjb2zINmAEHNzzGGgV2yAPD8kiFGNRKb7NGBPyB/n7iAd1i6gwKASdCVYomAi7KPJjqdoK0zfU7oCMBFXrGS9/LJA79h62bV5IlOzVOu+AyA0qn1mvKXv77a8PJIq3Lo5kA/NJJi4zaq31c+5l6zq7twBwEIRmYE8D5iSBygkwzuHhoAwEKAl1RzcGZDcn27G/kta5MO0pLMV8SOAKa6aE3lDy4ncNrzHYPnNVu7ab6+RF0xVuFvS4tCV3H7GbcrHvIWdgu9bAWALE0Jbp6bnobmI7jEF98Cfv9VsUa9gv9d/3bAt90eKVTC2gKFtYkGSfJor/02Hue/5qf4XQBfeedZv80o+FkAXwAAfAr4GgCIa/+8/Tk9BZ6Ie0XNT7X6P7q+RF3xDHg7lX4Sz9+8qrj9jNsVD3nLT7Zb3nvZCgDA9wA8f6WVL/qsm56YyQEIgs1zqXAiymJ6GuMxifXnVsY8/bg3PlPvjnniuPbSjgOcdZqfWtYYiSKbiJ6CEke7mtCJK/oSdkUTKHM7u4rbz7hd8ZC30OWe4MUq8nu97JDS9MYBuumJX3z7TQB/8Ix1tQPeqYWfBV57+6uPfv0dPJ0BDL/x+N3fevTrb7/6c/hf6YJHjx494jfgOT4FAFgf4+sAgDe/8VjJrw2v5P+AVyBFUfePgX/ZJuL0FH8gb+1rnuA7Ny5hV/xEmTvuMb57WXH7GbcrHvAWB8jRfIkKAMD8BL8vKlTTPwLg9cpi/wHeeR3A/OTfAMBXnjMC+OnMjAEAPwm89emv4c1PAH8LwBt495U38Oan3+NjPlS2BgAeHwcAvIa38mO+9O5n7loEHuOtzKQeq2/6Z4/xjTda8Zfw9h8BfGnuagZBh1eX8CueFoL7PNJ4dRW3n3G74gFv+bzovZerAAD8It76Y9EhqukfAfrp+do7aZD+8DP5KiL6jcTXU/kVPP8sAOBdPAGWJ/hNAMB3gP9SX/QzABuq7+ITALABny1Vv4lf7dsLABPwH55jBDCqbzqe4u0vteL4FN94E/jp+2p+RndLdwm7YqgCxqfSat1V3H7G7YqHvOVTovdergIA5if4PdHS1vRHj+rlZ148KAn6U90fFIWKli7rJuCkAISy9qx8sUmqgiIDTEQouo2CopDTMsBKhJNW/UBg7cRZr5TSfc2mZIT+EnZFUwBmDWxXcfsZtyse8pZTK4ZfogIAAp2ypX0PAdjSraWNTQW0tq/gSuax7og8eQxVwBPqoURV5dMc0Qgcso35fZoADgpY6YS+fiR5ezICREZTfU3XLf0l7IqNCWP+suL2M25XPOQtUQt0L1GBbOgAU0pf9BD09ByZuN8ujExx3bYNkXamFj55E9JLKm0Trcpsg7UynlKTCCDQkc0KgT/QRaW6SH3qmX6ir1HC+9Ul7ApfPyxbE7qK28+4XfGQt3Rb+peoQNnVsZZ2Tf8IAPwxMAL/BM9/AQAC/k9r9/fKH4/ZmvbxIrO4x/hTfLLWv8pFtsf4Nu+Ad/Fx/Are+wqreg2fxhWe4M/xOh679FfFv3iM3+GL3Pgq/hBAxI/dXaOE96tL+BVPkUdprNKZqrj9jNsVD3gLI/TnL1sBYHqK/yhaypvOFEFvAp/D+Az/DgDwtXe+XB6wPi8i18gljFeQKfbLwFfwI+WFExd8JuCPeQ/8D7wyPcVvs5oD38AVRuDbwHN8Pv9VLn+Ctzj54MvAlwD8JT56d40S3q8uYVe4Kox9DviTq4rbz7hd8ZC3fC7tpB89evTooy9bAeCX8Dy1tCh++qYnTaCcnv+2qgD/9n8q1z1rZAU8wcfy72nEsxrh73Ei+ZRQnAHfwZNfxTtsBo/P3vsSrvAMeB048bN4xohofYZ3PssvG17FtwDg/9av62uU8H55Cbvi85XgPp42vV3F7WfcrnjIWz7Ou/slK4DxKf5baulH72x6wkZhYgusz5x8bovJzmSggSmfHbBkIXAWMlo23denDkTSh4CZfqUMkDwrFvJgPhbThSk4SaIrE0F0jRLeLy9hVzRhLGjpLLTvv/8Ztyse8pagRYiXqLhoqajgEtVMxKWWKQv5TdUvJJ6FiPwAtycThiOKUzI6MBEgJHGG2DAL0zUzUSsCSF8yEsHXNg2kPVAGJvO4O2ogBu6OS8TQNmFsv6y4/YzbFQ95C2nz3UtU9C2VFdwY9CdAUdECwOvv/SMAmJ7861r1lCm2XsU7bz395/SvPoNvfgnAm9/E418jeu1bz7nI1qlC32U6IABfvEMCBJ7guwDeAIanVXB6A/j618RVv8L+/uk7agA8KcrpOy9hVzwpGtkpa7S6itvPuF3xgLeMWoR4iQrg13RLr5qeCOBrQFXRAsAf/BwA/NJbdRV3XL77CXz3s998D8/f/uovAAB+4XfexfN3fuvnH6cVBwAwMKEp4Sm+yUr742sJEBiA/w4A7+Ef1m86n+Cbr8urnuGtJPF8Ffib1zXQGtmrS/gVH0VeZr4AvH5ZcfsZtyse8JZnwP8U979EBYZXVUsveyhDGYwQV2BkTHfiv2s9UoZwE1uqkicvAdJncuArulwC5syv9sZjt96r62j8N6sv+hpA+vZdXsKvKAY7V1hxV3H7GbcrHvCWzo/1JSr6lqoK5QEoVUNLBE62ou9swDqH0AyhBirum+Utg/Qx9PLlvLp8yVw1GnMnAMIRFyG2y5rUbrrvJnXFSrQ7YI6FWLuK28+4XfGAt3itR3yJikG3VDedE0Dv0hyXgQ8zJ5DOITSBbyPgiotLrpykZmy+xynUZ3FpqN4GnskueY4cjAiTCrSvYa7HuL6pu6K8KZSZ0lXcfsbtittv4R/8shVdS3UFG6+hdwFe45HF1nPAIFYI7RB6bgPgVr4HGCo9Eo1J+BT3cLfwSREA14YWYxHDDACOrwmB/B01BelLuku6K4DVE8WThxnIitvPuF1x+y1cWj9fsuKqpaqHKqZOcQ3mwsP6PeFURofy3ly7p1I1AYxYiPmOiVuuCMDwQSENUj89E2pgyOQpCn9vbUoa90AUjnJJIKIaQHS/6+mdcKvXG2kVGKTDObDFuDnmmu+IdkXXLjBNxLD5SPFc2Tq3S3vawQ1RWyDyIo5jOiObF2skX75UEXxssyOFrbQIhDk3lS/A8xkoHrrXppO9fG8tW8/MTet3iQV68URhH9VvOUopjU0/PfMn3+2z+QNBDAPcofYTOczJnfOiAx5UYNCRwzdKZxaP2NpNkSacgvqGGNs3HZUD1aqwHjIgrP09c+aakMaykM/Bud4u5xQRFRFqJ2rq0r1+Ymh0PJfVUXldn7w/QvlxqV9RWzYzanJBfmP5zXECeCgWzSbmIxD5LY3AGigeIkQJjiJcTF10MaNT23dVF9qA6lAsGRgUyOcgngQ6MRwskigtJpG9dOIxVIFodcDAdjcbqWie1j0z0TnAHXwlJGLf68g7TG0U3NlIc5Lu5JWI2UhtlfMcROcEuE0Pjui+Qi91tR2aFnBjVOopzsCwHfq3RLmddZ3rgmXAZHobL42FuCIArGNS3gtsdMbU1MsZvQQKi7qBW/bfT2lgr67Frvac4MNuC0TRbyMADGWCMaeQRXDakWYAZ3vC1JjDKndYWUUOx5avie1TpnKXELRm3vlDpqilzu+5USZz3Bk0FdXf0riIn2UoY7fCptvb9JgpTaGFUU0nSXCOfDGj70W83Gr+oEB9aybO39fKWh0Yo2EWHRmmqjkA3yqrgNbSqSJ0OA/FwjZqOs62/OA2TxTPCXUvFYGdb/AqLXT79fqbl8466EIZdcCkxlT3rK705HB2W0mOF53RHTUpoU1LZS9Uni6+jE+5hWgf9tONawAw1JWK+fUpSVjIAKhOdulKLmIVb7qJpJolW9VaF8oZULujkuZQd34HeBQ9e+6gAwXqbynK6+UE9Nw61YORVJRyf4eqSAN6tC8WMsWg/duU0Kalshcrzxe6TC5lEa1M0trq1Xv9bKc1J3wXALFVlleWpUM4uyFtT7JUuAaKm4wCH5nOcR/87mafAuiyuEgeQuGQ6eWsHaB+2y72/TcgZtB2wUJX/UwxoN2M3ktzMlOSMoVc89AJbU0qW/AS5ZG6TWZdm1GW5Dpusbb9YPL0/UtUE5/GSxlwkrPP52C9/KlEdIoWFha/Es1A7rNCABMc7aycuQIwRSKKM/rfuETPHTVXormvyB/MZtCl4kDOcTWgekZ7omMExiJXaJlCxdIroU1LZS9ahieiXYnZjeRmImAonzM0y0LbdexXPdDAGITybM90pkLePPniJe/Jj3C73CDF0otJp18mVRFT5jYfWQjvTMGNkT2o/SZse00rOKaLuwo9g5YLBgAE/qF6QNWM9pXI1tIgKVOccolRL9RS2YuWU/QhxZ29hITr9I6lsOCFLniB8L5wyxEihb0tK0ObRJ0MOKu3AdkH5qSxzc3INSRDtYBEMD+tvcywjZsaa0+lbz2IqRuqwMYJoMl6+fu6Cj2Dziv+50jsudWAyhm9agqSMkVe79sUUEKblspetAwA4x7z+plBIuELUdUa7dyImp4zStNbZa5chCvpP8KVDKiFkEhHHrBQNwkDgGXLzS4RthuArXb0kZnyeSUDFperpi0T6XouLH1VedFVqBmkV9BzAiaRm6YTEuWM1g+4kikAwE2bP9H1l5bKXrScMe4kEthwXWsa0Oy0X7p3IlpyMpyTfc50LoMDpsioYgyUP/JSBtTmYqIVA3k0y6inxKYA1PQ02WbnG0UN60kb0LLCsFRUNVI7K2NEmirRqrNO/Pm6Qs2gQXufTWekwNmpGlA9ozctQl/JFON6RDrXKTedU4yWyl603N7R9kmD8nKZKWRZKjDdLbm0EYtX9MpzLG0xf3AnA3oAUHrRkWjCSGczCzgKQPRp8+xy1+WtowqumYEmYLE0LlMZplj1Rq2XPR+gNL/GNkK6Qs2g6Y752mbspZDYfo/K+0DLFMO8B/L73HpOCG1aKnvRMkNT7WmL+EAuG9Ab+dQV8bzeQbdHnHVxkRrD5ior9KIrUU6c5TK95E1p2v6t+bmJAJyiKMfTRvE0LkdiVEsz0x7sNz6HiTYZ+6Yq1AyaL13C2Iy9FBLb74M2AahhGcKxZIKr+hQutGmp7EXLDM2VelRjusQiy1eZuBG+62w1uTY3mynR75IBBQ/15EvmtEDeYTirP02K7KptnISvPpLovTbaFZnnViJa1jqMnjV6E7uynSJOzqpkhZ5Bi+bgesbqeaZ+XzQBXezKE+amyWFCm5DKjhcvNzixXRdi2XGUgNYq8DHJT1L4dCirG9MYdjLgkO7nBOSybOFRNuwxZHI8yDEOT3QCm6Qony9SuRcBAEMgRmoynSLv8pHoFIMqK/QM0hygm7FqQOvvq6e4N99EIiJaLmSK1gzPfylCm5bKXrQ81Gf6O212CGsZx7IA8q2L0KKH2u/Npc+3K3lfNVdZmesvW2eB5H6x1z31TAuW+oiV6Bj8NiyVBkbai4zIxr+xuVNIOe2Vk7ZQqTEQFXoGjZqFV6QZe9eA7rPDTGcZkKSdHHCnTOGiXySpjTl3ppTKXrQ8U1wHAHNgo9NUI6NfBoCmIce9DEQhRcGwbm996YjCnNftNlO3diWnqxJfJe0DsWw3LlZW8nyTVxTizCi5AK1hayd8NernjgLKbaRLvCAr9Aximzw50HnG3i0kAojEFuKkJbuWKYAQuYYj3+2lVObx4uWWTY05iLTuaZbAPE3L9W314F6RNYVBW0+YGbaTAdPUEWkWi65wVrIxAOAkx6WI+SSKzDlop6EZCoCjSxEwt7ES0ogkTG34lRV6BmFOGma3Rrmi5hl714ACaZvTiCttijqZIuGkUeR8Tk05e6nsRcuYdh+JwiGZc+2e9DOFrS4PZyRB1Hz8uG/4WJ5Vm73LmdXyBrLqmnmhd4MDFjrkdJIyoCewJQKhE06bOOLFb1Lm3bTeRlToGcQmiVw38oy9Y0BzK2bxvB13EcxGa5cYOU2yU0llL1rO75bca1PmXT2ThDtYFJbDqi0vXc1M/VIGrBEVfA1pNOIixcUB4976w5GSqDdJUUE4A3Ank3NycGsbIzkqQWXOvC/K4GIfNOyBYjjEONcZew8HOGhjCkbUvJm9TDEm+9iJXmhjUtkMvHg5YZP9evQyoIDY2gZq3hNJkBh2qnTNJ8C1DMgn4MDnmu9Wm44tnLyvhiQTlaJjz9ILl5OT/FT8QJlyRcX1DNoVzbQZe7eQmNQPc1Wp55G5kimqu2MvtDWpbM+98GJlYFrgfJs3nhZE2QO9oocnnd+YyJ/TpNPsWzRKfVby2ZjzA5h8vteJGcTEnPZAwqykk9BDKCFnWri7oDDyLWfMnkP9bwpOi+2y4noGDVpArzP2TiGxnHUQiI4BmEKVfi5lCmCjARdCW1mBmIv4C5UTdVUCHojCFAUDGPrOGnjbFpYpeDgihc1l3QBRZH5I3HVYNGEspLBfqZQ+aHQ8e1ZDrWcQDodVEg2bsXcMqCvKjeatXB5xLVNUFVgntCXjQ5ukL1z2wod5iySP1PghwFb6aOEVS1VBab1F7Liu20Pz+HdEY03uvNeRKs++Vwa8mEGJmntJb2uOK92ATmzdxOIjxeotdC1T/FBh0k5kZUVw13veWtvnYW5Sn9Y+tttcU+uNvGJ0pUL5GvdursWFJ5b2t+TOOpN3b9/XFXoG4YzkLwS96pt4MaD+co7fRtCkvSrS80xeuefio9ORBGEcEb/qiwdSSuTmsXW5e28i98QUMbmuNnLR/V53CQfFMd9T3tdVCKGlo6WByKcd2QakZfQY4M7C28X2JOr9Z1fxPqPZh0/9Zk+ql7TOgs/Ney+Oap07xcXqV1l0kUZ+fJXY3p8Xqzgbjy5Nepush/7YMrzVo2xrfEZxR6lL1I5nzecsv+NsgbbFq+9OXc0DkOIQpB/4VBVhaSEIYhURBiDVeJ49QX/pQfsimJu22vF5fP/Fs5zVO+3cT00px+XFniZxVM/KR86pvj/l+lf8x9dCE01P2PGrMt5snh+yokINYMfflMoptp1cADoVdYPs3Mpd9ZjGUA5KKmDnrLm0OeWPmvi4+j7jKzdT8S9Z6ZDaIHmwEVQIzv0Xi0DEhQ55EJRSuPGLUxBnizudJfudJT3X5bt4N4o8zHwwu1lYrq0MplDPrnmFZvlB6YDzyjMXY5BM7nyx+rjNE/l5FN/SOleP6UrTLsjX8UyyJw1eUwcPy9zEPB1IxKScrFdSrM3Cfe30UVzty29fzIgjXTzzEVBax3i1tD8UbIVWeZiZIaHPtBJpYfupLfPDFgHaRO+FCBOTxAq5+XzBRhFwnnyyU8nkzujcFNo7lJGwkpUeU1K6I6FZHJWwJ2biRjt3YoNTw+Tud7hWmO9iZR8ScpAsM/d2adKrIYHNwnrbyCImpnzvLgggfe5BIVfn9M40AhirL+pJJ49eksmdoVXUWJLX90l3MIB+TNWaoyyZQVMHX4kPAOsPKvSzW0bfB8xi13Rfacjsn8ueXZr0ulbW2IJy29JkQLnXYxWZZgIRbQ5j1rktRf9S+j3Syp0+6oR31SWJi1rF61slYxLrykUeyg8A8xl5sgRVVAxgOiLLTHFvUXnyd4794kWbUILcV4oUC8tubVRp0utgttyb7ba6aU8/lHHrKkD5gdk8s+cDNOtsIJqwc5uUPNFh1IYByg3hDf8AuGtlgmkyqCJcsY2kzlNFQDKAU/56b1GtqKp48SKpZ7mjVIwmu1hKPR3ckDAxGXDRt5WwqHx72S7VisK5W9hnYsw++dnUVk1EjitMqEmVB6DVSMWD55THS93DXeczUvSru6+Y9UZycqkhrhvhNBlUESH5yhWTgSpC0mhIyRCKqfHeovLk1479/Yuc2HzeUarTfBJaI5WHuUqD5chjfluJx6ijO+mKudw7lJoNANEZOVdfc5BJppexzOyi4pUy4J6ettDM4yZY5za9ZACYE1x2kpbFpujPDeSTSw1xpbHiuSGKxXdwvCymhlUarcF2aZLcXyxQSoVcvHiR3IffUdqZgXAVv/MkXNUYHvN9/LYp/7KWCqcrhnxP4ShEa00R1thSU/8cQJfcuXdJCwAcnSJuIvAFpSCHOsTFAcO6oS8i5GJyXlWTSw0xizwZu2IL1SDau2L+LtbLmVx38reKDUrtRDRdvkhlxrujVC+Xob8qTXok8tkUWnxj220OYMowJhTKiiY+FE9xooMb60s/b5Tjzk++Z1Dfnd30fRQJYy8kgINoBJz0H1TF3mpSG3o5xDU2GF2xbTRymkNRTH9UOg5yrO4v8sYPXfHiRSoz3nWpEY7Sy5LwjyBKYxGOJGT0t02NpfjrCm5ryo7Lq+A79ZlpwfG0pZ1m/lppSkxa2o0mETfRmxf3RDYqukonxu9UTLVJUzfE9dpNyoDlvLHmzLR3RfkqniaRzhtFdJ78oti/SOcDuS410u9iv1mXjERYAsUdLulZ+W1poVibyLfLijLxXR3g9Iz0/2bCG5kGj4Ze5chlwI/gVeCPMP7cW6/DPcZ3cvXyWOR2B7B/Bl9/HXDPRNJvVQS+p71A8nXAO8AXyoEYn8R7AF7Fu+nXn4LviiVpOADgHV0EgC+m0y8A4O/yd/3ljSKG8GvP8okZz6GLFy+C43nQ7yr9DeAvUtWr8rhTkSb9c3gXX/rYo49+Fm++8ugT6raUHL+eyPQEfyornuaKvwP8KABgfIr/DCCl1f967fpn9XiTHwf+os/c/nF+tnAi0BAAzFy8UsO4ZSrqT/KT1yESEfO3FZNrbzLgAbaSJeYliy0ieCIadBGS16h8DfcXlSe/KvYv0u5Ud5Rmpq3hu0SZh/nQnJXflrottr3ecF2xlQ1jKLlh5vRsuY1G3kB2piRpcw0UsmNpY+cdI6+tU/baznwLl3bceV2UUTNqxEtHZVOBLC51nTpygB8vQjJiZVi9VRSe/KrYv0hvm+8olTV4IC0DSm9c5bjBbyu+Y+mGOm5dxUlEGzCGlDilUGoNuvR0TMcI5NgWndwZMiFmJJ9NnU2e0wygEbUyO2krFABgOfJaq6Nm5BBXEWwt6nJerDPRSYZQtOpiGFS28/uLypNfFbsXQXtf3FWKVSLnMVgqD3MfV6xvq5u/Mo9rRR3ISFvamofirJnqW9DdUhwp0yZYDVJ2ZK3KoZgSajZPQM0AltYXSjjsZcUEnwV5MbnUEFfmmSJPVLFG2CYtmioqSYwp3/ebReXJr4rdi/S77ixlJ6yzcY4+D/PQLZnstjQg3V6vq3BEkztizdlV2XA+EWAgGrH66l6skzsD4xGpEr6npi27/ETMbIOhTkPqDkdqt6CbXP2ID0Bd0VQxO9xPIVerovKJiykl0bgX/4d7isqTXzv2yxfxmFt3bwkYTyK/sE1nn4d5uXAg6277gFHUQyvbkCrvGLYg7FUyWi6KFWfeyYnJpYZ4IPIObo/p+apYN2+xHjnCi8oJciyDkXK33FtUnvyqqF7ExpjuL70PyHy8ePc31eSWE3XU5WSXGg3mtZ7b17K5Ny/7lgHOD3DbXbveSegxhuSd75a4XhRd2EaXaHpEN7n0ECdxMRZ3IVWE2yN3shdF7RQLbCIx+r1F6cmvi/q9L4Pm5FY0/hOVIRKqsumIJf3iEkiFq7GjUg7+rGw/4lltpHvGRHXlYRkiV/3QLFrUijLMsnN1nE/xHTmvinN9dsntIyaXHuItUNiYkCOLP5xgLvNJaBrObuCY/09JB7VRoS+2c66bpL24fUhxvSR8zCFRLbVUTPmEKhdcdd7JoDenLHQRqMdUpXvH5PXNIgwvMjzVQcWwB2JO4bI47Smjb/lRTa7vf4hZfi3PYm72WhX5ZyeH+prp4qyrdkvszpovFGblRZzPHxCbg5htFKRz8rKjIIsoedaLmp5wJKLVwW20YKQ4wkkP4/qqfNqLZ9M62QAL4Uk37omo7hgrKQpvej6pu4MhuvTmimO8v+iFO/ny5ny6l/EaiZrSPA1t/ewxVo/DkctsSnInB+2RnPc3PMdquqsOw5mTJi5w+qibyJbgo35I2b5kanG1bdNY8vzogawu5YE9q5yrwa1iMgTjqKGglRS5X+5AWhvx/WALFFaubUrh9PltTs6OMcQVQCFdVYS2VLclpYuvWSr9L0TZgzM06aL61sRGOWHiswZIKUcGYCzS38h/kTNjLI8qZrL8b1Z4iG2TyBWR/iJqLKWGBbD3XRFAW0gCeZ56KqfyrEqYIJaOkWis+oZKbjz3+6y1EVp3SSRWjCHEDXWY3BYoHmXE87w6W8qDTd6+Ek2Yz2rAI9pa3lBVhFZBBZr0qQe58WNj4wf5FLUxU1FY5xm4sEU1bVhVOkBBbmJl2pSU6SI7B2tF4xdXBNBmW1FBTERjLD/Ke8kAACAASURBVA2v2xomXI0URrhyokPxAyltoKykHkuzKf1eGR//KE++LmeNFLlCalO7FqdFCCJh5E3DtFYvNCKisFfBfoQ72jLcZQgKFOsqO9OCvck6qthhotArsiMdgIt8aPekyo5xqsx8BVOZo/rQzHK7JBSzoxST5K6cOVztmfWnzzxpgcunISyhBoHUvCxUanIIUae2Qy2Wnhh8CZuvp8skjW6TAbNvd8htUwxgrju5TIpuju00Hk5Z9flQ4J4zMy3YChceqWSzLmnt8vWNsUnV107sKIGdAGyx5NFVxQ6ell6RvREBgfUe0bIm68Gcezd99sFXn6CEg1LLZm51wp67OSGeNRC55nJbhUC31yOLuAwYa6+khPpHcY2pyJeWbaA7SqxymUouZktKYwgb+xjF1U5udqlhukFqL6WHr2Z3kALxlodpTPfyEV+a3rrMLKlECBQ3/7Li40B0och2ROshJZphphWIoZh9ViIH4eReOum8x0xUtJc0d7JoS5qVGODqmuyftoHTSaF2GRc3i9nuyNFnoWhr+daCYaPQ4kpnAFhi8abJlxYvwqwjPvS2fUE1UdQ9XGA00uWDUJGmKMvhxcRcmmGCxt7duAvu25MbyINiTaWPPbLptFdkn1yMT+M20I6VpsK4T4ouCMe80j5luxDOW3NOgkgzs1sCSAJgexARhbRM1m5cAp3ss/nOYcs1K0DkWpCWDnLNbYgtA0hLVxZTxmAmAw75Ea4LUM9uIVUJfgLVLNi+WjqIdMb/RFvbRQBpDQ9Yibipc6PQ9D5EcqWt4i7RhDVQqJ17j/9982bR/TTLabNTAMiDiT6RYiRls4v5kW1WAnPkBLek2PmTFmW0YwIggPSdbF1yW9pL8N/H2tSiEZuASFPbXeiE4QAwCp/VPHvjUZ2Ga6R7tRsO2tY51OUhZ4/cSge01+nDoFw3LjjoHMpYc8futtwoT4MzHUTSLWyYz5Y1ZySaQpN1bvnf73RWouINHmQEm08xoTuNLBOrvqno1NIPa3kB7VXvnA69GcivtKig/6BnTKCWUWY4NUNlur6iNlyycXQrLLSp1xrluJPE0YsqSF9tClG4rcw6WpyOUxtaQAo/kEy78U1qXAAEalJdbarw0jjp5G1iMiCfeM0hJDcqHg6upKG94X/PIiM71ZQY27VYP/KiOBJRnBUzWVu31B6NQ5FZd9qw0YGNloUWiHM62Zkb4vClLBWHTqdyMBmQu34v5Mt8jeIZ+Ro/IB2nWJYNsVzxTWH1q5mVTxZ3f3R82PnWX5tw9bgAoCa5C8funY34yrhPW0sFExtiShbU/En33It3OPrz/UhiYrsWkpII0F5SYu8SNwz5g4IT6a8L++RblJGvoJ5mbLQhEhZaIVU08kTNhrIahnRg2Byy/BaYHrCIzGd6Y4u416NwhuLWRemuUfEdnq1vKo9f1PrNFPe5W9pXsG2T3OKqcQHXsjWMRGOj7dSISg8nIwzW6qKhyhOwKqyUP/S1/33M9ygZcCdaudybaGblToZHYX/1Owvn4g5Mnu+liICd1pl2zLTybBFTr6aQ+64t9/ZaV7Pae67JgFv6Z2BuGErTlN8WRqRA7EUKUk2nt7O1YJs1A2jqmJmrCNnrOkVwFOOCREboQDQ1ivKFw0xACn5J9SJxQR/AtJYW3Pa/z+z8IontISYH38PmLwvlWA6ujswX8EOCisvlnhLFHrScNGCmleU+aK56DWJoHIUBMwVQHDHFyKduEbeHuuZVA0a3EJevSV4Ivr+AzabSOk+7VFgx5VLed7RQdH4o2vWBadnpdIpE3b4wy+Rb88jNbnxxSvuVPuZdssKVEYdyF7r2v6+rpErgl516Kv9ke9iiNaZy3EZ9QwuK5eqD1h8xUeSaDm7YIl8v+92aEOBnmgBsNNEMYKGB0Yfcr2Ulu6uvza2TmeMrAQTFeVai3QEzO2/lUP3DDS9EW7UejAff7ej9hxqXneIo1hXu2N1SBlaNCxHRFptg3V7UwhcSb5GBHwOXONpJHKXnmxlINDZ/PZuDUZB2/qCaLiP/stQw+ia9M7Gl+E56mlPO89rFJ3VqCKV67QmgdXCZxKVGOIxGos3BrZFP4bIErP1KXR03mk53I6lHOhhrinTwbRmzxeh+leOypwPM2kSRjt17HfHs7OUpns32JFTozfUlyVsyKuCG/31+kIrl802jUN7D2rrV/DdjedxaG5DC6Bk51UmxZIaXnQlGEuH/F2kRRK+LJWCMkdNHYVQl3+9AbCaWtBA6NxER5QmitxerJ4onEz9WuT453tpAvoxW9FsLFCpo/XqIccEsQse64xAWT/GcVLBRk0R4PQ/JTN6XdffCtciX/vdTldr4NGgraB1KHuaW/Y64kMT+WlTi5T1l0huP0hu++iYyPc6FnUqp3johsNFHy822lQr+PVvQSeuBfHLwBwkVsQuhCL84DgHoklRV2U3kPZqZDJjiQObyqJv+9y23FuvrpXVfnR98G6w9Npg7M1dStnwOeYJkZ5lsYGJ6Js/vqiOnzv2t50bXbeD7gUCeb7a83JSLlAwDsRVkVIyE53KYZcSuY+bmOlEujkMAdODAxKdMq64ODGdx9K9ekfzXK//7cm3RayB/S+Nw5S7W1mqhbxy6ebq7ra1lhUbnMyaW6vPJImd+TJNOGXq9+G0MW2AnT6QDuIsdRyytyELfwXiWKFKyi/haPFm6WpmSYSaa6gxZxLjJXA5bGQg+LoAwmV0chwBUjcu5DYBbW4/LKLykQh19NcWn6u22/33RJ+Z++jDSEz0Ebjk8z1qURrhxypLfq2b6SQIUpMKmMuCDi/6ymMaTSz5bcwWWKRmS/rns9YTYo3I5nFk/KccFInRMR01k+JJ+MOFo9cqIlkg8NyWT1Xnb//7BqJM4Y9iSU2pL9yQOsc+/HzXWjoh4SuM0go1nSklMX9/0riv7nZjyhbYBGPaSys0PGLxePZsZlW/cVfE+3JGSobShjZvO5ZBYnh4XiNAx7didkftl3AMPOejCNdweKJYZwZJiZV/XB/rf1ww3jHFmzUXhaM07TBKROsS+pdybARYiUa2Dqqx0Jvr6mcI6pJeM6WI/MtWxCtYo/FvIgdPVNvMFcVdKhvw2nhGb1G8bLsYFInRMO3YD6P1lflDQLLW8rBu/9HqXONrgSy+GFAI2lJVoJnmIvSc6RmBMR3NnB+3xYFEN5wDHGKB0INLXL3NtYQp99aWVOQBJeEaU7YowAgSlEL5Glz5NZN6apeJeuFWwM0y78061seH7R2EXS34dERUGwOKR6hUJKX/fmFsrJnhCaFNO5bdkx517ANirldZtALpD7H0LfgPQVNBbGqqSLpHJWtJ5rnhSbVo7GMi3g1VKx0qe2aYifybPoa3yGnJXCZ0+rfZTSSrFUzIItwrudqJzOayVUGdWVUIk1FjwASwV0CguLDUWKiE4taHi/ONkD53PZUBy0xjYBRvbRguSrZ+ZJ1Vv5NDnXsgFiuVM2sGW48YqpfMca4dU0sWUmDVfOxTFN2dkzXWfu2Ywk79MZChdJdROXae1EykZ2HWQw6RzOZTPbCyp2s/4rrl4KLfxBHBx0Jh+bKav4WBLqu/0KifR5oBFyPn85MmNzspLVXZlPoAbdOojYFMDrj3TeNyF55Y07uawAkvTZ87sevGgjbUmbb13ihjPWLwxTyLAx1Fw/a19UJfXkLtKqGxqBYzGakqG0jM1GylPHSYlyjLwzVLMDz5TcmUnjt65Nwt1g14zG1Ui7J5yLQOxxWqh0HSG2ntZZdZULt9QaryOcbcPDxT4aNTleiSamnDcekXZaSKRY+SxZr/sfWUzhujERuQ59TDbjUpkKF0lVG4t/oXsi2SKN9VFqZmSbzGGVom0qm4Vf+9OxnGdqaI9tsRC1bMGymP7U9ev+UgTn0Yi11qjcv1gSeaUPUdYjXKK60Pso35X48WBAk+RdrBdx9K6bZfXVyR/isa2ItGIgeik1RWPsYFozQTAR52ZBnkiQ+UqcbFTB8ASbpRnlD/rdcL/V7mgOLYoFT+assJ2Z5hq7Wfb8mq1dVU91lc3htoZokG94wl4EGSkiTXcU/TilXMgoqY690TUIsLVwUdDR7I8gM/zgJazURw/X9gzJQ3rn5Vyos162gNR6qAiooUiAvg4Mt3s1N6oEhkqVwmVW6vLcldaHdqfLYiw8QiVy2Hk4zJIB5qur7pkYEwolItFlwGXEV4nOE4XxnY3h5L0PrsDcVMKEbVwvzH7T1XJ8CQiirvYGrCGqU2PdEhgAZax8ePGQQ/2ubx/5rLVCESbw3BET7Hm6EQmp8YGV2Y5LSxJJzJUrhIqt5Y00KqUDPkDMqfduFikcjmwU3GINiHY9JZIHUtUJonbtL2s8Mm6cLOO7Z7SUUQ6XbPZhnIMRZaMzzl/aXrlWlaAxkbGPRLlblLcpSVQovR5jURHSiFqzZmmntTDQ4vqnOMGlmYwzJJzHCPt3DR/JHezZsZp60uhSHZgOdHeuUp0ubVUWjshroPLgJILylwOW6PinaJwoexZddTSW2z6Q8kCWiwUAWkTsLWblODYUURaVqrneTHvD+oumsA6UAbZjTuVhESCinPHuzqN6ylO6a8mQ5U7D9KK4IldXyvbvDkihd2lYeKGO2XVqb4Z9U4l3ChXCZVbSxtoVUoGcKuO2q6o1A6tz4hOzowZf6+tljVNuFC5Ker3VTblOWGqFb+jCCTb0ZK6IRY/KnlF1m7Vm3Wgy1hiaUVtk/HyenawIYqcISde4ALJeJBdXl8e1Snr057kZALDzl5W8zRs7OFHt1pxVwmVW+vKQCs9CJo5vxfV58swveIUVT+QrTGA0AvUuPs6TXXQRomHz+PfflUD1VQLar1J31n5WCeRpi5oHHzQm4tIvkuawESC3N2Bico7J5A8bc5Zkp5nM68pDHohtpr7UjHNkLrYldeIvAkqkaFylVC5ta4MtPIo9POuqQEAl7u3VQpMt2XAlW2JddsnoC7cEzciqogkfTqquq6tbYVnF7jiUZTv0z4PyRn1bg4Qiz61DaOTbvf5cVJvVUes0vzR0S7qYC6tI3IOvCnfm1rNl1ydyLBPkchza2kDrToKHUwGXNXquQ2YymcK+UsGKvbH4R56reb0LebA1mTAAZByfucIvdAlP0r3SutBf1sbYGV1y/NGJ7dqPZ5urGST5+LZFFciLUNBHZU6d8+LPQzXpscp+fA6AIgUU1R9esgo+03lNZSuEiq3ljbQiqPQtVtFw1p+rcZZRt2Sj3ebfnQnRmUuKd2Nee/tjeUx9xzFy69d49XeQOv3WK6P1KjsKT7UDs3h6OoQ+5npuQc0DuJyoF9RBK58abmQAcv18Oq8wyVvUXIHF1tIqFpMorbSKsap8hqqnIgqt5Yy0Iqj0OWkYUkIUmhWbFssQd1SIdfbebqlrj230xAf+Yk9p+lWljvSjErRtWtN2Xf45Ce/ZL3ATHEdkJRDM5CiVWa0Q+xDiuGdsn49kWjZM3CP99LK5UIGbNfvrHMX1iV13UnOEJWERp6KTWspdV7DH0CqwhfCZSh1Q2c4Llve6m5cMDUGuNeau5bqO/SAh+SshVWtxzwAbmmRGtW/rYhIZd603Rqfdc1zbkvPFbe3y9nuuGHrruf2zQHAeDDnl/cJwtQ/EwGrj3WfJc/uEn6iGcPafAqVVCUXJMXwF70mdFvz0mmFlTAxgifzkjdJuvL75JAmsGAUjacovggsPlI8y4um3UfpZq0PsV98pFjcwzIJsx5K6RJbmQ/xfHH9AyGP3NK+HX1ofmpqJlp5oKEw9W8USmgBoP09lZ8oAIxbILav52OhBObOZNPtxLvFm2gd2Baeq5LqYtA9RcqAkqFWVAPSsPkrN/ofDjTvjZXH2J8A/7AdnW+HTpmQUcxh9Vae47F6tYcYZsDN+UHc31P5iWJKKtIahSQJoJMBlXDb2ez04j2Ib4RYuLemxpBupQwAMKxnIKnRug2eNWWpibsANAObS3kM3Z699wEsPsYDWENWOi7kR09+wBHjKiXpppOT/jqiB7n3RrPJKen1KOmThW/HRWg+AFeyVCrPD3A1L/GFW/l7Sj/ROe0GmKusIgCpMdYJRC48djtxblxP4R7KxIixiQXSrbThQRmEgHTEOWfSVUGR4tlPqc1KvsdpOI/YRjOnwfNlzLBTJCLygYhovCQAdQ6p7EHuvTEwJwP+vXud08K3ow/NT7fKLmGeH5XAnGAaR7dT5j8RxV1O6mt/1ctnSVvVmSveHwF15mFR3XBvtA2AWyITUWLxBUrstRFAcZ6JtCf5bqtWtXNOm7TD5YXYUxxxEp1wMdsfU3cxeVP460D0oPTeYGf8sXm0N72Q8O0QKROCoDzeMY0/VFO/0PJpTwvuJxqIYjdc93mS/wCw+Cg9BaQrS9BShmvKzUrX3XAfNSr2aKS/ZGecHBTY3rkVJ4csah0AZsYzjxKthMyN04CdeUsnCeDi4NHWg8p7I14dzrmVa7RvhwjNv5MAmOdHNfUL7WynqmV+orvkAJcvcdNWzw3J7U25jXzTHLCtwnLh2uUBlFW3vIP7IkhVcw0lOyOFY/RFB+MnTOnZ3XBvIe2l/Qqc7WmBjqE54u8oI5DHIf+TXrgIH/kNwJDz7jtgzYkHZnQEIP11dA8q742cXmhR4zO3BwAoK5QKzS+9W7le7/lR1bwit193dpfwEy0ywOJwTQCDekmLGUqrZWliGVBPmuC25PYUcxvj3CLC8h1MaBjK7VV4ElLnQQ7YQj5wpwy3oxEL7Q7DOgHMmZooNqXTXgJCc5qvsiIX3Q/3j0qxHL5ce+QkJsnhQxCA9NfRPai8N7aSoK8xOeaOrHw7Lpy92AGgKjQf4DKgyJ94dXaX8BPNu4DQMzAAmP02idhyStaUM697xbO/NUJrhnxK6FWis4fcKuZyIoN8c3LvJDwpctpohaMRA63AQmsa7s3DtRZujeA9MTvvDoSYnGi29KqS3zZhBpLypGIHtpz0dqppQyQBaH8d2YPaeyO9kmca5elZ1El5nbMXXNOdd6H54Kb+q9z2GvLM0rv1ALlFSi231O2G0gutFHZVlz0VMrtt7tGTTKwmb8rC00o63v7A5pEIAHSk4Q5ryaieHl0vZzlcFjow0hIPlHT5B7OXEBENgJNC/oKcxDlbmHKAAScA5a+jelB5b2RXu9hmyMzGX/l2qE2h4i1Xofn8lEImY96hVNdexMPanBQ0AWjraUO34Afa1JkfAwUAsRhZyk+RDplYTZBY3h/OdBT6XQOFFTudCCsKB1jScNOc1oYEV9vvqW0jFzpwEsKZJ3XNMXawbwsURuTEzeUDpzJue7EUcwLQzsj5p6bWl4kuUrKIeosI3FK+HXVT6HLiXUEAV54fdeWXYp/y90S9+qLlsvn4SP73k+x8WSHAjIAkgOEJ/v0bz/FlVvUFfAfAY3wNwKt4/mZ5P14BXn/06NG38N6jR48ePfp5/py/j+dfAcZffvfTwI8AgH/t+a9/DNuP4aN48i4AvEb0xW98Cfizq6zF+RVPn/8Onubh/R7gXv0W3nuCz+EbAIAn+DYAfKJ92/QE//QN4OP4s1LjgNeBZ3gHwE+U04I5fgTP73p9eumPp+c8w39NVc/wGn63vO+X8Zb47GS4eAKf/k4N+zzwBvCxR28BX32UgdwtmD8DvJHvfqW0++Oipb8HDMnf80fB/ERfxW/fIfb34MogQfLZ7cDV3/eUSoit7+IFzIGnUqm/WqKINsDFUPRK2ZPCE51IeQRXHJTSJA9pCajScVkCzpS8sG6Nz52AI05tdz2CJQQDsBX9LBMjtQzYcYD7Aji7RBeetnZ6hvJKUL4dOmWC9MtQnh/S1K/CJIW/p/QTvSSAfgngyiAmU1br98x8DnjKN+W5E7jvQCWAK8VREoNCdOXnzPF2or0tASkel+4QAo8iZSy5t30S6s6W5jaNYFs89qwRaC1Kq0HIuSvZbYVMlL+OhvLewE6+sWx95Jb07VCh+Uqdozw/5DDqFVv4e/Z+orfBKJXFNQ/1oIna1qm4W3CtWxMBOAcoG4fLaPIpueKORXiamp19aULgRlMa7roNdEvdBpacUSVX5EhEQxLa8ks8eYeVkqPFvCO7ak0xGRXH5ArEZMCQO6MQwAF0/joK2ntjJSbtsumX+lH4dujQ/Fkttleh+S+FgR00u+DiqCZurHfNHMyy8lSucJT8Mo0vrrQDLlcwwaPY/6QwmpNxLUTuyCmEeaaSg8i1bSAo5OHeImqw5VmSFNaJvgHVSYiJXSU7ePpnBwonzSa4iJTEPcuAxVWeh8Ru2l+nY6nKe6MdEfk+oaklst58TUlck+ozukSTLnX0TERlgYirw3DQ1VFN3MXyMnixiaTttPM6q7kWgFt9Cy3IkLbMDWeis5y+xHUiaUezxUwAG01Z76d1gwvfHJWjgkbIKOE5+UuNZx0id0Q6R2CPOXtTTnrrkY6oSU1MXeNKKnhulnigUHWNhXGHLdknNzqTHrJ78JiY5ImNBgCBsitafWtyBs5LVKQZmEo6JsodvRGdCH6qcVS04+qopjpss4iG6m16VS0aOXEAONsFY61PRCNOfXFUs7ElSs76orEGbozApeZ/LdaBB+TN+aCx524r/zqiK0qZiOpMSuMx3EMAgeakoXYpYVTqGNoXWpgzcDEVzhQKkWxEJ2cDRZu/J/ehq6Oa2Gl8rXuZTFLdec6mdy3hFQwilK8aMfXhLYmDJT1gE56SDFHTw18Md28OBrD64uYw53CsJaRTl/aYzzcWCyAREfmUxrbsH2IWa3LAUADygXNpKk1E1FgHgD3mc52GsraXLDXt3+2CAAaio7gDDnQ6zHQ2AmBwREm/ntXrJw2ZO63peIzmDOxqYuMjGxQ9Y/6gB+aByeM+8vHnXP7oBPpsBJN6tRFMOijOL/pEzljuzytT9Rn0jitoLoe7wz47zHQA2LckxK9ERNEls/9Wtyl1AUTYAUc+AORDauhZ/58t9PmUsBSLseboYSK+scq8NuZuqS48WXl44fCe1Lw5YmCiCYAPdxLAQCcQqES+p2k10Qlgoak6A8fmmxwjRl+PLnshDJVw2ZaXy26hcQhXq2rmnjELgqWc29py5jDHu0INIQ6bcJuFO+JV4Nol1sB8oRHLbiMAoDhipWOh0zlPg14ACwEscdrOI0/zsTUsFq3sCuSTx06iPXmbzBSravhEyyVcQgTzv8N1erdQFdPDAzhAiGhyWueY/wPGXAn40qjQfrhQ8yQVkReJ2BcVutWeWuWB/WGS8pKDcApZT94BWMcit6UWJOqckup5BbBTDqrpFsBCAPMWaDpC9aaKVRQJKOliHeVoPHLphFCsNPK0RiWbkW8rQd4oXDAupsZNqiclAzC4F5Yuv0+UHXs7FV4Oz1AXrrYlLX/POWItV5fOCXVNKIvhgLZZfAiGCcCZxvakffTk54WJriwhYyK+NVkPkvIwkd/VTMwEAIo4AnASzcDZQoLHqn1PWWWSNf+KAIqdpxB7NW/kEwKFDMAMaMlUoHcBHybOZqBdAbfE5ChTJ24R7WW8Vmr0QUvxCAEuCcAlY7R+qTuroJ/ny86pY8lOcyXjel7Kyz3DWXjO0eTqsdw2MAIY2NKyoBHAseII2RpdbNLyYHbKHibpOJq1+OLXJaDww5LZ9hBbge9rv/gBgo9n0T6GUbrtl12iFPmKTtAB+0skvDzLaLaULIwAith5liPn/AB3lNfEFnfcPAFD2jwv6ZFJibzdJQTOAHCEJvVHoLhzrCUzQQT3LSFKXRLytxebaGFr5V/fOdb/MIOFfm9JEMupdHlo6Z1J4W4hdcTCROJ2CFexM3iiEdOBTADrBmAI9WAMn2V0AEAI7TnpMWdblPKJbHHARudKB1ygUQqBBzQBJHl/p5L9uG0I8867LDDDQWobeLxPvrF/NTBs6bAQAOkYiSaUTynYbgIQUqg90zmtQlMeh3wKyEJxxh4xhrxVanJjoLWO/N5YaSQAQ2jilmO2sLINPNALgQaBc9MCayBam9jdY055WUdXzzk/44Qx1mBcAspa7HNC6kYB4hi+QLGazg7yZ0ynJ25ce5EksY4DIFDLIgIAmPJaMIektN/jB3z0xl9NhC5qgIhGBKLjar4MOxdoppwNIzlYliC+AJ6HNFnc7hByAzH/ak/5yA2WZtf5pCkqMkBluo58lbO2tpK92McbgDV1You5S067SyCiuCl91uKJ+JE2A+3AWI93ATBGOsUSnmxX/g5FxjUBuGpsnoppku8CzgmYwvtrcvv/CsJvvArEwx6JiB3GkASpwhfWNCQrsNfYL2DNTtltCXcxS85XynG+BOxtCSgROs1H+qB98hSWhUIJ471KLmJ4WSSf4S5B6ElEMSUBWAOxwzRcDMmlZar6aiRH1lEt4Umnsl6FPrlrIXBH3cevxVCgNIGG9wEjcxtvWJJ9aVcLgi9JrV2xpWGkM/sJsaAVl9J+niyqH+y3O7eBGJOTwA/yAw334JoDAMgm0aB8uqtyBJUD7DRjSKFY1Wcl5doc4+WDmSKonAjCtA3j+3ImieEKVQa4+G3xjQOsjQMUD96AogV0xQ42NyFuLtnOGfGwbWBVBZ9XqmDDB4PFq10Aw3QQUdwvZICTVrijOk1OGPMOPYcDJU6whwHAEvl+cu0ijQwfKno9QMb9u4A9UliXJKO7naUfS4coD7ShKoLFYwUBxCoQGj4saE1gcdq91gMEYolmrpHiGccHaV3z+H+4plCDAFW3p3s0gdUqCIi/FbpoRyIiGtofhg8fapCKm+NNW8AlxLNW/eya1IxlNzN82FCDNL/AwMioMKKgCcDwVxv1AOuBaLkYbuUf9JBzbg0/bPiIz3GpY/aFnogoe8I/gQdewXv4AvA2Pqnu9Pj5RxKf/uCbb/i+kV36shdjPttsI/LsAOsuyafhrw+yIX1EdgTITvB3+Ycb/tphRk+K6AAAAnZJREFU8tnXbSgS+pKjIwwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGw18v/D+z/p0CRYpQlQAAAABJRU5ErkJggg==",
   ["fnt"] = {
      ["common"] = {
         {
            ["base"] = 25,
            ["scaleW"] = 512,
            ["pages"] = 1,
            ["alphaChnl"] = 0,
            ["scaleH"] = 512,
            ["greenChnl"] = 0,
            ["packed"] = 0,
            ["lineHeight"] = 31,
            ["blueChnl"] = 0,
            ["redChnl"] = 0,
         },
      },
      ["info"] = {
         {
            ["size"] = 32,
            ["smooth"] = 1,
            ["aa"] = 1,
            ["unicode"] = 1,
            ["face"] = "Bitstream Vera Sans Mono",
            ["bold"] = 0,
            ["spacing"] = "1,1",
            ["italic"] = 1,
            ["stretchH"] = 100,
            ["padding"] = "0,0,0,0",
            ["outline"] = 0,
            ["charset"] = "",
         },
      },
      ["page"] = {
         {
            ["charscount"] = 256,
            ["file"] = "BitstreamVeraSansMonoItalic_0.png",
            ["id"] = 0,
         },
      },
      ["char"] = {
         {
            ["height"] = 1,
            ["id"] = 32,
            ["x"] = 134,
            ["y"] = 151,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 3,
            ["xadvance"] = 16,
            ["yoffset"] = 30,
         },
         {
            ["height"] = 20,
            ["id"] = 33,
            ["x"] = 504,
            ["y"] = 93,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 7,
            ["id"] = 34,
            ["x"] = 385,
            ["y"] = 131,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 19,
            ["id"] = 35,
            ["x"] = 63,
            ["y"] = 121,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 24,
            ["id"] = 36,
            ["x"] = 273,
            ["y"] = 26,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 37,
            ["x"] = 391,
            ["y"] = 73,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 38,
            ["x"] = 248,
            ["y"] = 75,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 7,
            ["id"] = 39,
            ["x"] = 507,
            ["y"] = 25,
            ["xoffset"] = 7,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 3,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 40,
            ["x"] = 373,
            ["y"] = 26,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 24,
            ["id"] = 41,
            ["x"] = 383,
            ["y"] = 26,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 12,
            ["id"] = 42,
            ["x"] = 135,
            ["y"] = 138,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 14,
            ["id"] = 43,
            ["x"] = 496,
            ["y"] = 114,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 8,
            ["id"] = 44,
            ["x"] = 331,
            ["y"] = 132,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 21,
         },
         {
            ["height"] = 2,
            ["id"] = 45,
            ["x"] = 107,
            ["y"] = 153,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 17,
         },
         {
            ["height"] = 4,
            ["id"] = 46,
            ["x"] = 10,
            ["y"] = 157,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 5,
            ["xadvance"] = 16,
            ["yoffset"] = 21,
         },
         {
            ["height"] = 22,
            ["id"] = 47,
            ["x"] = 17,
            ["y"] = 55,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 48,
            ["x"] = 358,
            ["y"] = 94,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 49,
            ["x"] = 0,
            ["y"] = 121,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 50,
            ["x"] = 312,
            ["y"] = 95,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 51,
            ["x"] = 136,
            ["y"] = 98,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 52,
            ["x"] = 152,
            ["y"] = 97,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 53,
            ["x"] = 168,
            ["y"] = 97,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 54,
            ["x"] = 343,
            ["y"] = 94,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 55,
            ["x"] = 373,
            ["y"] = 94,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 56,
            ["x"] = 184,
            ["y"] = 96,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 57,
            ["x"] = 328,
            ["y"] = 95,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 14,
            ["id"] = 58,
            ["x"] = 15,
            ["y"] = 142,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 18,
            ["id"] = 59,
            ["x"] = 110,
            ["y"] = 120,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 13,
            ["id"] = 60,
            ["x"] = 38,
            ["y"] = 142,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 7,
            ["id"] = 61,
            ["x"] = 346,
            ["y"] = 132,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 13,
         },
         {
            ["height"] = 13,
            ["id"] = 62,
            ["x"] = 23,
            ["y"] = 142,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 20,
            ["id"] = 63,
            ["x"] = 25,
            ["y"] = 121,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 23,
            ["id"] = 64,
            ["x"] = 393,
            ["y"] = 26,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
         },
         {
            ["height"] = 20,
            ["id"] = 65,
            ["x"] = 459,
            ["y"] = 72,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 66,
            ["x"] = 476,
            ["y"] = 72,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 67,
            ["x"] = 216,
            ["y"] = 96,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 68,
            ["x"] = 248,
            ["y"] = 96,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 69,
            ["x"] = 34,
            ["y"] = 100,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 70,
            ["x"] = 17,
            ["y"] = 100,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 71,
            ["x"] = 232,
            ["y"] = 96,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 72,
            ["x"] = 338,
            ["y"] = 73,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 73,
            ["x"] = 493,
            ["y"] = 72,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 74,
            ["x"] = 68,
            ["y"] = 99,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 75,
            ["x"] = 210,
            ["y"] = 75,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 18,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 76,
            ["x"] = 476,
            ["y"] = 93,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 77,
            ["x"] = 191,
            ["y"] = 75,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 18,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 78,
            ["x"] = 356,
            ["y"] = 73,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 79,
            ["x"] = 264,
            ["y"] = 96,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 80,
            ["x"] = 408,
            ["y"] = 72,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 81,
            ["x"] = 289,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 82,
            ["x"] = 85,
            ["y"] = 99,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 83,
            ["x"] = 200,
            ["y"] = 96,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 84,
            ["x"] = 102,
            ["y"] = 99,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 85,
            ["x"] = 425,
            ["y"] = 72,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 86,
            ["x"] = 442,
            ["y"] = 72,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 87,
            ["x"] = 266,
            ["y"] = 75,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 88,
            ["x"] = 170,
            ["y"] = 75,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 20,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 89,
            ["x"] = 0,
            ["y"] = 100,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 90,
            ["x"] = 284,
            ["y"] = 75,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 91,
            ["x"] = 349,
            ["y"] = 26,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 22,
            ["id"] = 92,
            ["x"] = 500,
            ["y"] = 26,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 6,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 93,
            ["x"] = 361,
            ["y"] = 26,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 7,
            ["id"] = 94,
            ["x"] = 361,
            ["y"] = 131,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 2,
            ["id"] = 95,
            ["x"] = 77,
            ["y"] = 154,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 29,
         },
         {
            ["height"] = 5,
            ["id"] = 96,
            ["x"] = 456,
            ["y"] = 130,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 5,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 15,
            ["id"] = 97,
            ["x"] = 410,
            ["y"] = 115,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 98,
            ["x"] = 435,
            ["y"] = 50,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 15,
            ["id"] = 99,
            ["x"] = 453,
            ["y"] = 114,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 100,
            ["x"] = 384,
            ["y"] = 51,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 15,
            ["id"] = 101,
            ["x"] = 290,
            ["y"] = 117,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 102,
            ["x"] = 75,
            ["y"] = 77,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 103,
            ["x"] = 60,
            ["y"] = 77,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 104,
            ["x"] = 0,
            ["y"] = 78,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 105,
            ["x"] = 135,
            ["y"] = 76,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 27,
            ["id"] = 106,
            ["x"] = 81,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 107,
            ["x"] = 451,
            ["y"] = 50,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 108,
            ["x"] = 499,
            ["y"] = 50,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 15,
            ["id"] = 109,
            ["x"] = 257,
            ["y"] = 117,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 110,
            ["x"] = 380,
            ["y"] = 115,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 111,
            ["x"] = 320,
            ["y"] = 116,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 112,
            ["x"] = 483,
            ["y"] = 50,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 113,
            ["x"] = 45,
            ["y"] = 78,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 114,
            ["x"] = 439,
            ["y"] = 114,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 115,
            ["x"] = 467,
            ["y"] = 114,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 19,
            ["id"] = 116,
            ["x"] = 96,
            ["y"] = 120,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 15,
            ["id"] = 117,
            ["x"] = 365,
            ["y"] = 115,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 118,
            ["x"] = 335,
            ["y"] = 116,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 119,
            ["x"] = 203,
            ["y"] = 117,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 120,
            ["x"] = 185,
            ["y"] = 117,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 21,
            ["id"] = 121,
            ["x"] = 348,
            ["y"] = 51,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 15,
            ["id"] = 122,
            ["x"] = 350,
            ["y"] = 115,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 24,
            ["id"] = 123,
            ["x"] = 305,
            ["y"] = 26,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 27,
            ["id"] = 124,
            ["x"] = 95,
            ["y"] = 0,
            ["xoffset"] = 7,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 3,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 24,
            ["id"] = 125,
            ["x"] = 335,
            ["y"] = 26,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 4,
            ["id"] = 126,
            ["x"] = 484,
            ["y"] = 129,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 15,
         },
         {
            ["height"] = 1,
            ["id"] = 160,
            ["x"] = 185,
            ["y"] = 133,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 3,
            ["xadvance"] = 16,
            ["yoffset"] = 30,
         },
         {
            ["height"] = 20,
            ["id"] = 161,
            ["x"] = 37,
            ["y"] = 121,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 23,
            ["id"] = 162,
            ["x"] = 427,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 20,
            ["id"] = 163,
            ["x"] = 119,
            ["y"] = 99,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 11,
            ["id"] = 164,
            ["x"] = 166,
            ["y"] = 136,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 20,
            ["id"] = 165,
            ["x"] = 302,
            ["y"] = 74,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 166,
            ["x"] = 506,
            ["y"] = 0,
            ["xoffset"] = 7,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 3,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 23,
            ["id"] = 167,
            ["x"] = 472,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 3,
            ["id"] = 168,
            ["x"] = 26,
            ["y"] = 156,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 16,
            ["id"] = 169,
            ["x"] = 167,
            ["y"] = 118,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
         },
         {
            ["height"] = 13,
            ["id"] = 170,
            ["x"] = 53,
            ["y"] = 141,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 12,
            ["id"] = 171,
            ["x"] = 77,
            ["y"] = 141,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 6,
            ["id"] = 172,
            ["x"] = 394,
            ["y"] = 131,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 14,
         },
         {
            ["height"] = 2,
            ["id"] = 173,
            ["x"] = 116,
            ["y"] = 153,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 17,
         },
         {
            ["height"] = 16,
            ["id"] = 174,
            ["x"] = 149,
            ["y"] = 119,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 7,
         },
         {
            ["height"] = 2,
            ["id"] = 175,
            ["x"] = 125,
            ["y"] = 151,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 8,
            ["id"] = 176,
            ["x"] = 296,
            ["y"] = 133,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 15,
            ["id"] = 177,
            ["x"] = 305,
            ["y"] = 117,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 11,
            ["id"] = 178,
            ["x"] = 189,
            ["y"] = 133,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 11,
            ["id"] = 179,
            ["x"] = 179,
            ["y"] = 135,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 5,
            ["id"] = 180,
            ["x"] = 448,
            ["y"] = 130,
            ["xoffset"] = 8,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 21,
            ["id"] = 181,
            ["x"] = 366,
            ["y"] = 51,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 23,
            ["id"] = 182,
            ["x"] = 442,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 4,
            ["id"] = 183,
            ["x"] = 21,
            ["y"] = 157,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 4,
            ["xadvance"] = 16,
            ["yoffset"] = 14,
         },
         {
            ["height"] = 5,
            ["id"] = 184,
            ["x"] = 440,
            ["y"] = 130,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 25,
         },
         {
            ["height"] = 11,
            ["id"] = 185,
            ["x"] = 199,
            ["y"] = 133,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 13,
            ["id"] = 186,
            ["x"] = 65,
            ["y"] = 141,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 12,
            ["id"] = 187,
            ["x"] = 92,
            ["y"] = 140,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 25,
            ["id"] = 188,
            ["x"] = 146,
            ["y"] = 26,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 25,
            ["id"] = 189,
            ["x"] = 98,
            ["y"] = 28,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 25,
            ["id"] = 190,
            ["x"] = 66,
            ["y"] = 28,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 20,
            ["id"] = 191,
            ["x"] = 13,
            ["y"] = 121,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 11,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 25,
            ["id"] = 192,
            ["x"] = 234,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 193,
            ["x"] = 302,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 194,
            ["x"] = 489,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 195,
            ["x"] = 199,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 196,
            ["x"] = 181,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 197,
            ["x"] = 472,
            ["y"] = 0,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 20,
            ["id"] = 198,
            ["x"] = 149,
            ["y"] = 76,
            ["xoffset"] = -2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 20,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 25,
            ["id"] = 199,
            ["x"] = 50,
            ["y"] = 28,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 25,
            ["id"] = 200,
            ["x"] = 455,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 201,
            ["x"] = 438,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 202,
            ["x"] = 421,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 203,
            ["x"] = 404,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 204,
            ["x"] = 353,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 205,
            ["x"] = 336,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 206,
            ["x"] = 319,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 207,
            ["x"] = 251,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 20,
            ["id"] = 208,
            ["x"] = 296,
            ["y"] = 96,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 25,
            ["id"] = 209,
            ["x"] = 145,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 210,
            ["x"] = 34,
            ["y"] = 28,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 211,
            ["x"] = 226,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 212,
            ["x"] = 210,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 213,
            ["x"] = 194,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 214,
            ["x"] = 178,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 12,
            ["id"] = 215,
            ["x"] = 122,
            ["y"] = 138,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 22,
            ["id"] = 216,
            ["x"] = 0,
            ["y"] = 55,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 25,
            ["id"] = 217,
            ["x"] = 387,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 218,
            ["x"] = 370,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 219,
            ["x"] = 285,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 220,
            ["x"] = 268,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 221,
            ["x"] = 0,
            ["y"] = 29,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 20,
            ["id"] = 222,
            ["x"] = 51,
            ["y"] = 100,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 21,
            ["id"] = 223,
            ["x"] = 467,
            ["y"] = 50,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 22,
            ["id"] = 224,
            ["x"] = 257,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 225,
            ["x"] = 92,
            ["y"] = 54,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 226,
            ["x"] = 242,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 21,
            ["id"] = 227,
            ["x"] = 30,
            ["y"] = 78,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 20,
            ["id"] = 228,
            ["x"] = 433,
            ["y"] = 93,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 24,
            ["id"] = 229,
            ["x"] = 320,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 1,
         },
         {
            ["height"] = 15,
            ["id"] = 230,
            ["x"] = 239,
            ["y"] = 117,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 20,
            ["id"] = 231,
            ["x"] = 490,
            ["y"] = 93,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 22,
            ["id"] = 232,
            ["x"] = 227,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 233,
            ["x"] = 212,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 234,
            ["x"] = 197,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 20,
            ["id"] = 235,
            ["x"] = 388,
            ["y"] = 94,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 22,
            ["id"] = 236,
            ["x"] = 315,
            ["y"] = 51,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 237,
            ["x"] = 301,
            ["y"] = 51,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 238,
            ["x"] = 287,
            ["y"] = 51,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 20,
            ["id"] = 239,
            ["x"] = 462,
            ["y"] = 93,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 21,
            ["id"] = 240,
            ["x"] = 90,
            ["y"] = 77,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 241,
            ["x"] = 105,
            ["y"] = 77,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 22,
            ["id"] = 242,
            ["x"] = 272,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 243,
            ["x"] = 167,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 244,
            ["x"] = 152,
            ["y"] = 52,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 21,
            ["id"] = 245,
            ["x"] = 120,
            ["y"] = 77,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 20,
            ["id"] = 246,
            ["x"] = 403,
            ["y"] = 94,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 12,
            ["id"] = 247,
            ["x"] = 107,
            ["y"] = 140,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 17,
            ["id"] = 248,
            ["x"] = 120,
            ["y"] = 120,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
         },
         {
            ["height"] = 22,
            ["id"] = 249,
            ["x"] = 137,
            ["y"] = 53,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 250,
            ["x"] = 122,
            ["y"] = 53,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 22,
            ["id"] = 251,
            ["x"] = 107,
            ["y"] = 54,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 20,
            ["id"] = 252,
            ["x"] = 418,
            ["y"] = 93,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 28,
            ["id"] = 253,
            ["x"] = 0,
            ["y"] = 0,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 27,
            ["id"] = 254,
            ["x"] = 50,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 26,
            ["id"] = 255,
            ["x"] = 99,
            ["y"] = 0,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 25,
            ["id"] = 262,
            ["x"] = 130,
            ["y"] = 27,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 22,
            ["id"] = 263,
            ["x"] = 62,
            ["y"] = 54,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 25,
            ["id"] = 268,
            ["x"] = 82,
            ["y"] = 28,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 22,
            ["id"] = 269,
            ["x"] = 47,
            ["y"] = 54,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 21,
            ["id"] = 273,
            ["x"] = 329,
            ["y"] = 51,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 18,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 25,
            ["id"] = 286,
            ["x"] = 114,
            ["y"] = 27,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 27,
            ["id"] = 287,
            ["x"] = 66,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 25,
            ["id"] = 304,
            ["x"] = 217,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 15,
            ["id"] = 305,
            ["x"] = 425,
            ["y"] = 114,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 20,
            ["id"] = 321,
            ["x"] = 280,
            ["y"] = 96,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 21,
            ["id"] = 322,
            ["x"] = 15,
            ["y"] = 78,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 20,
            ["id"] = 338,
            ["x"] = 229,
            ["y"] = 75,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 18,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 15,
            ["id"] = 339,
            ["x"] = 221,
            ["y"] = 117,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 25,
            ["id"] = 350,
            ["x"] = 242,
            ["y"] = 26,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 20,
            ["id"] = 351,
            ["x"] = 448,
            ["y"] = 93,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 25,
            ["id"] = 352,
            ["x"] = 162,
            ["y"] = 26,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 22,
            ["id"] = 353,
            ["x"] = 77,
            ["y"] = 54,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 25,
            ["id"] = 376,
            ["x"] = 17,
            ["y"] = 29,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 25,
            ["id"] = 381,
            ["x"] = 163,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 0,
         },
         {
            ["height"] = 22,
            ["id"] = 382,
            ["x"] = 32,
            ["y"] = 55,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 27,
            ["id"] = 402,
            ["x"] = 33,
            ["y"] = 0,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 5,
            ["id"] = 710,
            ["x"] = 430,
            ["y"] = 130,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 5,
            ["id"] = 711,
            ["x"] = 420,
            ["y"] = 131,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 4,
            ["id"] = 728,
            ["x"] = 0,
            ["y"] = 157,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 9,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 3,
            ["id"] = 729,
            ["x"] = 36,
            ["y"] = 156,
            ["xoffset"] = 8,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 4,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 7,
            ["id"] = 730,
            ["x"] = 376,
            ["y"] = 131,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 1,
         },
         {
            ["height"] = 5,
            ["id"] = 731,
            ["x"] = 462,
            ["y"] = 130,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 5,
            ["xadvance"] = 16,
            ["yoffset"] = 25,
         },
         {
            ["height"] = 4,
            ["id"] = 732,
            ["x"] = 499,
            ["y"] = 129,
            ["xoffset"] = 5,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 10,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 5,
            ["id"] = 733,
            ["x"] = 409,
            ["y"] = 131,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 10,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 19,
            ["id"] = 937,
            ["x"] = 80,
            ["y"] = 120,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 15,
            ["id"] = 960,
            ["x"] = 274,
            ["y"] = 117,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 10,
         },
         {
            ["height"] = 2,
            ["id"] = 8211,
            ["x"] = 41,
            ["y"] = 156,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 17,
         },
         {
            ["height"] = 2,
            ["id"] = 8212,
            ["x"] = 59,
            ["y"] = 155,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 17,
         },
         {
            ["height"] = 8,
            ["id"] = 8216,
            ["x"] = 339,
            ["y"] = 132,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 6,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 8,
            ["id"] = 8217,
            ["x"] = 315,
            ["y"] = 133,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 8,
            ["id"] = 8218,
            ["x"] = 323,
            ["y"] = 132,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 7,
            ["xadvance"] = 16,
            ["yoffset"] = 21,
         },
         {
            ["height"] = 8,
            ["id"] = 8220,
            ["x"] = 256,
            ["y"] = 133,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 8,
            ["id"] = 8221,
            ["x"] = 283,
            ["y"] = 133,
            ["xoffset"] = 3,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 8,
            ["id"] = 8222,
            ["x"] = 270,
            ["y"] = 133,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 21,
         },
         {
            ["height"] = 23,
            ["id"] = 8224,
            ["x"] = 486,
            ["y"] = 26,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 23,
            ["id"] = 8225,
            ["x"] = 457,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 8,
            ["id"] = 8226,
            ["x"] = 306,
            ["y"] = 133,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 4,
            ["id"] = 8230,
            ["x"] = 468,
            ["y"] = 130,
            ["xoffset"] = -1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 21,
         },
         {
            ["height"] = 20,
            ["id"] = 8240,
            ["x"] = 320,
            ["y"] = 74,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 12,
            ["id"] = 8249,
            ["x"] = 148,
            ["y"] = 137,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 12,
            ["id"] = 8250,
            ["x"] = 157,
            ["y"] = 136,
            ["xoffset"] = 4,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 8,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 20,
            ["id"] = 8364,
            ["x"] = 374,
            ["y"] = 73,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 8,
            ["id"] = 8482,
            ["x"] = 240,
            ["y"] = 133,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 17,
            ["id"] = 8706,
            ["x"] = 136,
            ["y"] = 119,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 12,
            ["xadvance"] = 16,
            ["yoffset"] = 8,
         },
         {
            ["height"] = 19,
            ["id"] = 8710,
            ["x"] = 45,
            ["y"] = 121,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 17,
            ["xadvance"] = 16,
            ["yoffset"] = 6,
         },
         {
            ["height"] = 26,
            ["id"] = 8719,
            ["x"] = 131,
            ["y"] = 0,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 26,
            ["id"] = 8721,
            ["x"] = 117,
            ["y"] = 0,
            ["xoffset"] = 2,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 13,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 2,
            ["id"] = 8722,
            ["x"] = 92,
            ["y"] = 153,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 16,
         },
         {
            ["height"] = 22,
            ["id"] = 8725,
            ["x"] = 182,
            ["y"] = 52,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 5,
         },
         {
            ["height"] = 4,
            ["id"] = 8729,
            ["x"] = 16,
            ["y"] = 157,
            ["xoffset"] = 6,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 4,
            ["xadvance"] = 16,
            ["yoffset"] = 14,
         },
         {
            ["height"] = 23,
            ["id"] = 8730,
            ["x"] = 411,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 15,
            ["xadvance"] = 16,
            ["yoffset"] = 2,
         },
         {
            ["height"] = 10,
            ["id"] = 8734,
            ["x"] = 208,
            ["y"] = 133,
            ["xoffset"] = 0,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 12,
         },
         {
            ["height"] = 25,
            ["id"] = 8747,
            ["x"] = 258,
            ["y"] = 26,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 9,
            ["id"] = 8776,
            ["x"] = 225,
            ["y"] = 133,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 12,
         },
         {
            ["height"] = 15,
            ["id"] = 8800,
            ["x"] = 395,
            ["y"] = 115,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 9,
         },
         {
            ["height"] = 14,
            ["id"] = 8804,
            ["x"] = 481,
            ["y"] = 114,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 14,
            ["id"] = 8805,
            ["x"] = 0,
            ["y"] = 142,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 11,
         },
         {
            ["height"] = 28,
            ["id"] = 9674,
            ["x"] = 18,
            ["y"] = 0,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 14,
            ["xadvance"] = 16,
            ["yoffset"] = 3,
         },
         {
            ["height"] = 21,
            ["id"] = 64257,
            ["x"] = 418,
            ["y"] = 50,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
         {
            ["height"] = 21,
            ["id"] = 64258,
            ["x"] = 401,
            ["y"] = 50,
            ["xoffset"] = 1,
            ["chnl"] = 15,
            ["page"] = 0,
            ["width"] = 16,
            ["xadvance"] = 16,
            ["yoffset"] = 4,
         },
      },
   },
}
