return {
   [0] = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAAAAADRE4smAAAgAElEQVR4nO29X4glWZXv/z3ND056Gz15/ZOlM8MpUcmyUclSQbNsuM1UDooOVUODStWD976YSRQ4MEPnwwhRDEMljA9ROHCFSqLmRX2IYrwgE4XK/TGR4g/ayGnQisSWNpJWjGTunV+kzu/G6aY1ztP6Pez/O+L8yapqx2bW56Hq7PiXEXuvvffae6+1NgAACGK4JESh+NVWAJBRYJ8OirYtQ2TUwocoBlEEADU1QEEkDhsiJyXvC6mtKHWflVNlJ4u2razXsB8vHtFQnSKhZOYVyKnuvLH5K0Fa2xd30kgqamv3JeOyobbOQ+siatRb+h9VUoyKZGY3TQQElc7ZrG6pqTL1pIZCNPqk9ymdT3Uzy/3MpKUqRqGe5T5Y3tA4SQSk3hIlpUDslnTQEhE1Dy8AbVcAel4rdcu/ISKyrugUr3pqMPMKIKfSe2Hrr1R52NoX++m4CBEUVNiXkP9HI1P+3Y9qqdS3p+JG+T6xzhCZ867weJ/S+VQvs+zPDOS1qoz7qpopb/Xi+gJ5e2KfrqmNEORnEwBzc4S4Uww5xUDQ2oIbu+WfUAlkVu77xRtQgbiiNpl5hfhDufOHvb/iFHhPGgjIqi0NUR4Aca2LImjN6e5HRWTdndQtNZn4HRI1SQAktS6KjKxXcz+l+6neZ9ifmVCKtKZGN1LOg+WR2mkZCzuTwqql2pGPUBZwrwAAUALgHjKfEgGlK1HLkFII1SO9fiwUgKCwak+ha04a4JGotGAkfnf8O6DNI7vIEl9APDL1sg8vAGj775xDKFqA7Kz3nY0FApA7jWFATnfwKNDr/WHzSAmoz1CzdDc2TwBS00HlRB0BSDqdQEH6aaGVsYnOmpzIa7usW5Z8xtxbgCVagNDqPzOtKmtcnTCtW2ryWWel2pcGQECdJtHTCb1HLZ0MtMgGRClKWxlTBdQWQNz5lNk0KjszapHU1Fai1YqUEkMU2TLdUtERAKMMQ19lsrM0L9eYTlMokDNuWfIZc2/BMjqA8yl+BXB1wkZrvX1nE5VqAPhtia8Teo9aPhkQySHBTAFIKADQlAD8egsgLFtqMpRW3dMdX0ZtLh5VAL4AlCrXYzHwM7kWiddxMy8iarXIBFo5To1+GhM1jgbn3LLcM+bfgqUEwKj15A8qXZ2wJkqBuFVf6p5NiJoYCNK2EefsCuHrhN6jzpAMSEl4QLbub6mjouiFGHj1VktiZQlAoKtMRkRlgKC0GjAtALESyJKarg4ApK7M59QUJj9149qav1tQndsauHfLUs9YcMsZWwDy+jFXJ4xlhqvOyD0bGOnJIZqDJtPtm6cTeo86SzLQ9dMVgEaXYqKyqQD8eouAqIlESetMjHQOZOojrLbQDANbWcJEWZ8AoHZkvqE8dsb0NQDkVvvcUh7bI1//lmWeseiW+QKQpwHCWmejrwN66Uo9V/zwzhbkT3qImibyxNMJvUedJRkQydGjIwAZ6cZUqX8pAX691a+ZKwEwHYh4injf2OSxEQDZhyREQa8AOJ1AIO7TDUkiHm1lWih6knTmLUs8Y8EthfiyEkFS1Fk3HeSNUHhE2hcATyfUdSYlimafNbfXpNRcXyf0HnWWZECUCJm1BSAwHUCsVZQ2B7x6azJvlgDoN0z1LyUA8itqqtArAM6sTkoE1FaT2pnEycQV1exbFj9j8S1AnFfUlmm0RNrrAlydMNR1LCJK/bMR+ZNxABDlrXimK1reo86UDIiShBq4AlCpev4E/ux0Vx58fhMAHmADABLgW0AIvCBOTuRFg8HgBIeDwWDgvfs7Ol+zf4pPAMEaftj9UgDAlvhTAIANnAK/wLo+8E2MkmADB/rAB3ECvIjx7FsWP2PBLVFatvQp/M/ByoWru0ukgVX7e9Z0LgHAGPiV+PUy8A7/7Dpw3M2R3Usrp1gPgAk2rP7Re9SZkgBwHSN3jJeMcSQ+4Ilo7R/V0S1kAL4OJAAu42QfGAMn4qT18ufUH3B4U/fQAcbA54DrPZcDQGblwRgvAs8D+rN3j/HslzHZ0les4WXggXVF55bFz5h/S/bF8Y/3Bucv7aj3W5DGKUbuF9kq6puB18SvfeCt/tl3uEnDN4FngO8B20Yn9B51piQA4Aifdf7Is5heFL+eaPCKOf4avHr7Zn3Kar6GfbKL33YPXQcyfBRHvR8K4DIuqJ8x8ADYBT6mz34VwzH+QScT4PvOFZ1bFj9jwS1bqxev7wEACmpMOixbatKe8/gFhlbNCtxMeBJ4FTPPvgn4dW+m7AJPAtfvA6PLz0md0HvUmZIAgP9htbUAyiG+IX8+sXfyOXU4m14F3HprnrSif0XALrr0tQpH+Gg4wj/1nAGAEvf172fEQ0/wfn1o/wA40ZUNHwH2nCs6tyx+xjK3AEDkZNf2D1YGP7pS9Zz/OryadXYaInImN0JRD68ODk4BjLcfy9rH3insKYB1HKtMeQLfGishfvp5AG69PYHqc01bt46p9ehY/dvXKvwTRn+OSZ+4AIjWJ1d14rzoal62q9T3YTce6+IvHOkrOrcsfsZStwD44rH9ied3gK2Tcdg9v3+su+o0wL7bD75mN6Dwz/4WeLv9J0s1Jvws8AMAwNa5we3DKcZl51FnSgoO8F+s18dUN71PYPf0C+JnMpR9pVVv93RraQRg7Cgzfyb/nfYV8+4Ea/hRzwkA+AL+Xv+OhqKcvg/8cf/VEVACwAvqis4tSzxjyVvy0Vd77l7tOX9hgm0xuXfFuwZ4FXhS/AqA/88/+xuZXJXa9Pk7ZQwgqjZwtK8uUjqh96gzJQXXpyM9jMlH+LZ+jyeAf1wXwvfpQ3nMrrdH2BDzAObV34V/tT5krQwQlGvWI21+BOBbvWeQrh0bmXkauEJEdAv4YP/l1hUf7b/lTM+Yd0u4ebDv3xqOjYTb51dPsXmHaHsN8HXCEz0yeh/wK//sA1hjEQDA+jYRPTfG8UX76DeBZ/xHnSmp/94V/fo4cdVysWwUm4mphvREVM9MINmrYc5agDytDULs+c7OPIAzxdaQM78g39QeKttXBL23nO0Zs29B0wCtp6I31iqUez4uW7XAl8+dCOqcLfWvHEBS1C1RU/gL6UTpI08EQczfi7yovSlIICEAqE0ZZmahSK0FlHotILBW5ORqoJq/lC9sCYCZZPMFwDarQKAFLrKmwEJ35spckfbdcsZnzL4lo7gjAJU1Mdc9XzT6Dyw/FWwWKy0lsOmYF4REyaNOBScAUFNBlAJpzwxUmwGRJZ6BvcqlVwON7ZqVF3NNwtypQnVBTREQOqs6qS0xWu0NnbbGu6Jzy+JnLHkLVfAFwC7/vvOqZMu5i0GlvxhUqb+tBSBWV2idUMzFP9piUALIxee0ZwUTQNoClT2p2bVOQK0+srCKrkcA5Iy9zNhWC70nADXZTV1lzlo/7cKr/Ss6tyx+xpK3qD7BNi2060z3fKizYcZysKzr7tmUqI6BILcEQK+QtiR1Qik83qPOkNTLCi1Je4Aew482De3Dmd0jqktUJtjrVD0CkBIFMAtK1hqRyc7Itwey5tSttXu78DpXLD7wEM+wPtcx/Oxaa5nzGZFVqepePSXqPZuqlDTXrMnoXsZsulQv4TzqTAYhQgByIkode2yr22tLu11oqdMVJUQBqhChYyjfFYCopVraBOZElmy7AmC/RozEehWrp7QKr3PF4gMP8Qw7CywBkO+Z9p+PG7K9FSydEMo0a9bZIKtbakv1EnlLrTHl9XVC71FLJ7UABHMEwDULd1qJIo8CICUqVE5YvYMrAHJAEBoBaEymuQJgv8W/gxEs42McQ9x6a8zYagBxTW1l991dAWjLEL1WwWd4F0eFy8xv485gLfMStZWjsESltq7yTTJDpXfblggVpbIxDkT1KDuvH1e6+4utg7Iy5d1zQNFSFVpXNqV1tnY9E8Rry/9lq+Bo5J7Wbry2mo5lbafxDvV7lbZmT5Q5uWtcw9x6CyCtGj+Pz0xOBCQmXxsqzat73lq2h4v9iraTjSMA5FjPxKZV8XtgIwDGrhkxNVgkAJUxiojNMUWfANTygYC2KrFOWwKgZDSSj8nUU23119XILK+toPW09YL8d7cMHmtTsTsC8HB0fIxy2/iuto87AlBQgpIsmbPk2PFwsV7RcbJxDD1ctaSiVlucuSaZtgAEehDeyCyMhADkQLcB059isr5S3V3UJwCxcGHI5TeUAYK47BMAJaOxdJMoiYpIjAzUiJFyz+nH8tpC6E7qRFQ5fku2pANobd24IwBFK8shptadKTIHPAsb3/PNcU+zi9UVgJhyAHVrne5pE5fHMRRs1bP8UTiymqitczU+EQcTJR5zBCDR+aSLRdo/zxIA24mpZ0ilBcCM18RfzLX0prIcA6qB3K7njteWaMA0TQsk9nnXYTDUBdlT+ZusVO2O+1DrNk8AfM83T1IfsViXJ7SVVt14etNjYes0rmo6q7bMp2YJQOnYOwIwLfUSLUDqCUBYNERNHsKR0cr/kEb8FL7DVmXxvbZs2+qcYud1vek2IFJtWVcAckLYtqF6f6v5DlrTIPQ5Wz5GjDME5csmMEsAvAnylpoopDBMpDojrjO3zhEA2zNFFnI+XwBsHSAgzwxdAiOjgezm7cqdd+fiHiNGAJ6QRzan2FtZEeYu2BmcM9fur6zota9zg1XgYscccAGJKTCKvJRfmI+NEPjf4tcxsI54iL/aBX69d/38dXl0A8AfY7q36EkRXoLsrYFtUbC/ca5wzwHAuaMpTm7uA8D+PawZL95iE0c3Tg9v3DsFMJb2dn8DMQrYwCUAQdlSHf8Sa4+WAUtAFCoBiNGdIF54t2x7EjH7Pzu1NDuDweAmcH8wGFxaNjELzzTyvZi6S7z/gjGADy7x3X+C73SOPVh008WVwXkpWp8AhtfkVFG0gcOL+8D+9XNAIGU0XzsBPgxEOAEQ3VkfYm37E/hPAITm0hS6DZ6fjMtW++ktTALAqhKA9yqbv3m19SGLFQBuDyS7XmqpwlzArz3jXAAdO8rXMHTPPwAiaWi6gPdP9wCsCkPou4PBYLCP3RP7CvccEGZVQ62ciSvHR4MDjO9kAHAFU/OZHxEyGm2e/C3wNmAd/xvAl3Byc3DjSBhihe3lNWC0cSdZIolqe32I4Xi7XCYJAHiLEoD39dl0vlHYBz6sfkfA/wugYxr5XcBVnnaBdYTA6aKnh8Of9Rw9f9JzUBLcujweYTjavBMDwfr0IrYGJ7hcAFiH9TApo1+anhfmYu/AL4F4ODm/h/2L4vm7w+m9weD2BNfCxcl6jPuDwY0DrGeLkr8GXkMAvFkJwMgSgJm19feWE1yWdSD6IqY7fZfsH2JMu/iMPcB9EqvA/+q5WHxsKpSSP+03aj1/17EbdDg9uD0YDG6fYDvER0Tbev4AGxECbWUv/j4AlENloPsmvAq8Fy8BgPClSEf42nVgdxXYXpxcw+2rwP7WAS4vTMr28UkjAK5a88bi/BGuCdXjudHJX4hjvmnkpftTjHDlTmM6r7fhLbOM84GKrmwCAJ7qtXYEdi6s9NnBAtg/t7ULYPf8FJ/FK9InY+sUT8v3sngVyfqRkVjfmPPjkF47hxgvTH4S0sZuC0gWJPeBV/F2SwDe4Fj9lxoxO6aRvwVwdeX2EYDR9nKjjXOnJ4gABKO+HmA5HuBd2J1gNwSAXwij4CfN6dcABNcmF9Un/BZPAj/HUwCATwDAGn4hLv2J1FjmJIMhfiwfPMG7FyQB5Q6iBcCVzDcWxSbuDwY7GAzuTte/Io45ppH/BgDY/R+4cfMEm2qQ/294pU99FKyc+xaeBvA55Rv3EPwGIyCajm5lAN6DF7APy7MNrwJv/rKQMuC3wK8wBnamoypEUIzFYTmS+THwhwuSHwGuSX19hDctSEI3fUIAHjHA0WKek3+86Uk9Ohs4kh4GO9+GNH/eA/5AHFu3R2175yGaYgCvoQH+sOd5YiJoF08B+CB6dYr5JGVDRHQZQ2Bv5QSXm7hYO9nxPFBeAT49PtiDMt99Ae8G8DWMb9GdjVP1joonFySd7uNNC5IYDOQgVQjA29/QLUAAU0t/oIv0RFW2DdeTaSL85SLgGHuYN91yPAqAtRkdvY0/EVRfW7ctwM/fnYy2N47PA/gWhmbmdhcYnW4BylN0bzoKgd0bx1Oc3pMOrabHeG1B8lXgplLYBxcWJA26CzBjptejtqqxxGpP6pF5O4x/477Olf8J4Q0Vjl3nxBH+BQA+DOwCp3jf7Of+GJ9BqrvO5anWcHhzMBgMlFfyzuqh7Gt2j7BRhkCQ1gAmwF8D0DL6PLYB7F9YGZy7fn1wCfu6G/sI8L8WJH/sdC8LkgYhAKuwXUTfgPSI584prqRAHAL7QFomAYC3RzWwBQB/hBMAL+Jc907FdXwcGzNdmy28iaAx7l/aAyDn8gDg0j2sZQBw8Qjrt9Y271xZA1ADHwGMjG5Nx+4SzSneI358SIrrnOT+1HKKxYJkdy3AysLXtbb+Djk3wRWi7SHu7gNPrl+7Q7dw67m16W0AwDqOAHzfcwp0OVkLxnMmfGZgYio8ZQ5eP5FtzcWbRxNgcngTiNaBbSGj0ln7a7jsjFFexJrQaDaluM5LPo8Npd4WC5MaIQBvmeWrvCSvLJ36XbJ6cAoA93YAbN0+PJkAOD1Y2QWAGLgKYO90nnvvEf5ytm/7TH4NfAAAkNqKgPau3ru4enq4emkP+OL07lTI6PRr4tzuPWw2aQiEwhh0a4ovJUDUAHcXJ0/xXBYAYU4bC5Ma3QJ0vOHm83vcYxjNaOvcYDDFswEA7F46v3oTN85JB9hPyZI98BzDHb6LdVydfXoG+xM8mwBBfmUKAHEZBwjytY4o5aOv7awcToDJ4YrSUq/fPB1duUV0a0MMVfamw2tEz41wb29x8twJLt8hurU5vbcouTcYbIl/hAC8GTOnNZeiWTr1evABu/2a4m3OyT0Mv9K9JRhLib8+Gc5ed98/XbxU0EOE4TWiO5vHwt1+ffsO3dnEiS9KX7+7C1xaHQxWrWWwvXO3D0+nmJ78RCRXDk6BydGN60skcf7u8QQ4vb9yfYkkcqIa+L8AAE+eeTW4wWQk3d2fBPbmpl5nwk/bS73V+kZsj9z3PnZllHQUub/UPtj/sP0skCrPWWwSjs0o6cXL//wQL7T36+D9w2n9w+sZAOy88ifvHuH0nztNyYw215t43jpLcucsSZtcGwgljjWMm2qsyJuWYZBrJtSTmvdMwHLeeBiLICLyA2CSZ6FteYo+nFn460kgLMTUVFxPXFagpKpr7x0ULTU5cmo7VmdB3RZASEnXIA1AWotpi9wyVSq1VeW8wnKLNRSO42FFlMxP2VYFuZd6mDL3BGC2X8CjYmWkyCVjepYaw8im92LoqLZeQOXWEVllXSqt8XrisqJfAEI5PVP0CEBFRCUyivoEQNqkGQGoKbWC8M8TALdYTTnkmJ9aWgBeJ+wot0VLRKExBSyUrWjYEybZykgAQEMtgrzN0CcA3YuNANhBFFwBaKmNgVhGs+6Ly4p+ARA3pkQ9AkCVPNEjAJ0I9yFRExuzz3mF5RUygrwhagrl6DYn9VA4bi+udaxt/tqxm7U8ZwSWAIjcNwJgPOXCbphkOyPFR7XUElUR+gTAv9gSgE5AZS0AKi6B3IKjE5fVfIAnACrsaNIjAAGlQNq2MXoEIOk2CZYT0wIBeBzF2tMpwXJgshyhHLcXzz7eMoDvWM4Hfg9gBCCXLZoSABXqVqS9MMlORgJAWJDuNjsC4F9s6AmorD9SP0Y4X3fispoP8ASgVi/S9rQAFp1Tc659NLpuat2qmFFreW7YaAcm2xHKcXtxPWRsFxjfd8b2nDHh8SPxdPclVVoIgBcm2acgKnUt7rYAM+kJqKwFQHqNZA21qe3H1ywSAN1jlmcUgFl7fNhl1XVHVLd5pexEH/bd1HqqYktZf/AB7cDkFqbjoeL6yNlOcP4ZW8BcAWg84VNp2SK4YZJ94hQmyPrZBED+snwWUiBuVL7Wsg02ElJJTxEzJlDvlhGlds6rUUBcE9WJejV5Yzeh8V7SKauOO6KuoV4pOxeGndhDjSdHMtO62asdmPzm3HZ78cTSqhHOmZ79jkwX4Lc+rSsATnhzoGN1La5srG8xAuBYAhe2VmsLgHYiScXuARm1QKHez9RC8cqyB64rIwC5jm6UqL/fIiXKjJqZEqnBRDcxSwDssuq6I5rPndMq+x5lXlWEzu7cb4SMA1NXoXsk3EF1TjahSSdKAJzw5pY3mY7g0OiC9QUg0A+OMUcAdBdfNNSEsgXQf8BrAUKiWo8JhADI8u+2AFSFCEoVBaotA4SV3LnJJMTbqNxNLI3VLquuO6Jdc6xS7lzobgHSqYpa/+wNlP46YFcgLCMAouh17WqoTYBItfrGuzDoEYA6iyBi+mjf/XktgPwpBUDmh6cDlLKAci0AxmnY1wGESlhRC6RKg2ypcBP6L6rsMT+tsuqphfbQwZTyWatrY8JMLXGPm8Om4MSbxmVLrYykldVETZV27nEqkMBr8jvphMgUmI4hJu9vRUFlRIX1p3yFUXdNvQIgSjog5QWcUWvF7vdGAZa8CAEwe86g8UYBQmRjWemVLlu7Cf0XIT922bJr/GnIh8E4cXvbYejCdMpvrgCoYEsp5C62RDLOg3WPU4EEiwQARJn+Wj3SEqqBGkKikdXMilVhoeMi2AKgRwERILpiPQpoxaSeuNaZB3Dbg5aKwglm6M4D6JCDmcmFws5GFdzNCEBOVGAps/B4tHix2On1PJVI8Gc4lk/ZP8anzfF6e32I4fqdud2CtEq5DbwMoFnD4Y3B4PbJFeDLQ9wbDAY3DzrLWevSFvQsLmd2eHPPCPspnIh1mh9JI5LPAEDo2xT+xt9CAPACKldXvLN7NyfYbAIA+8BXIiDbBLp7NWxsSGNxANiaIoyB9JpMy6x11kIdZ6+u59d7gIvAE2cputmarofjHCWI1vBN9fubGOnjdmEu5Es42QLyEe5e2gd2zx8AY9y/DmBv64J3bQiIJVUntvUCrDDJntU1RsqN8IE0+LiSAtGuDqNtWwL7WAGV43Z8esM7vbd6gNHfBcD+XYyeI7p8fIyevRqmhxjrarKH4TbRlcnZDVb0S+EI3RZgXtH1nNNcHAwGVkbbzlGCz+FELwzvncg64RXmIurh5DyAD+to91vATHvm3s1OFuGGN7etrgPtRviysDk5nVwhem50AIiAJ64lsMP0cP0O3VnH0XXgmeHBuW57unUTw78EsHPzeIrJwQWg7ezVMN27dIwrKj/3bhxNMT1cfWifzhi4COCJsxSdc867z8FxjgIAhGM7avhdZc3mF+ZcijVEAMKha6n76f6Z6d7NThbihDf3jLDhJlePpzi9u3WAyU96LIEdLt07BU7uXgRw4Wbvh+4diODhexdWBqtbWMVvO3s1/GwPF6bGXGD/4spgRXdvssEeSh+YJfiQMFHyW4B5Rdc9t5AHeJf4sY1Ty9Jh7wRinxK/MOeRbAjTpzHwU3P0AKNbTZl2haBvs5PFfAs4FRW0a4Qtu/v3qWdfWBmc28HWYHWn1xLY5vq5weC8kPQZBjI/d1IjnGAP+JBKKb6BUb8+/gwAtQPOclwaXATmKIEzis49txClEoVj/KN9/FsQG3C4hTmX8BoOrwPAmx0L1q37U4zWr9xqfO+mvs1OFrMPvceYZ4Q9US4EH+6xrem1BJ7Hk/6BD9mJZIjvAsfS693Ss3aOnN3EDMLj91P9+3b0Is0BZgrArKKzz83BU4m+gImTabun+ALgF2Yvap+VECeiwXvV3Wzl6srN+8fA6O+8e/oq0GIys8eZZ3X9EsYi+TS6puL9lsAzcfxRqiQAsk0cQ8dlvYajfeCrGNahGhNILk7wX/ueuFYFCMox/u9l/nwXe5FEFp2aLnYmOrxz3uKKldJRkcWV3c3R5axAbK8XOmPWxJtpqex94bt2nDlR4t3zMPMAzqJb684EOsnUC7ouZg2DnNpO3vRH1E71OTOP4cZl7V0L0BHFzIf3rAWoU/50iv02tkXYskXnnZstABVRrhbcgd65PzHd4hSmU36x+RsN/D2EuyvPkOZF1j0BUR2ebSbQDZPsrQU4SV8ApIUWlRmRs0V70rsAW8viyqgVceNqZSDgxGXtWQ1E5i6mqdXApCaq9GqgPPUQAjCv6PxzswXAWqogJ22QpW0XplN+SvJiosZE1FMPVeH6zPPULqnmHn8tAIsEwA+TPC8kky8ACIqW2irBcgIg1pUew/zqY2K5ovPPzRSA0FoREbOoPVkgMt8uTLf8GmlQ2gppsDNLbrwQVYSwzqIAiBuiwL0HPSa2CwWg+d0sU7nEed1SK9sAW3jkBG9Sy/V8ANI0NxUfINqdprRixxYNUVtGgL1CSWo9q2iorXuMHZYqOv8cZgpAYNnNiIDOPX9TNk5WYbrlpzYrykV/oPDWAkJ9IoZ7z2Onu5t13Tr2caEThi0uG7k1QNxvpSzfWQeTFpbBXQGQeoH6oq4AEJEKRKhX/At4AgCY+KadEdNyReefw+wuwFWJ+myAoI1MrIUdt/yiiqhO0CcAcgEphJye1ob11j2yDFQOwd4jSuS/blRM2Lusbqmp0sD2n1VuC54AxEolUE9RmS8ySUcTD2YIQKkEIC+TEAhSb3EukmUudpRJdI/tCUAGBGljYs62sbDbdqpcSxWAWCyPJj27Bi1XdHM0XbfXc1WifitAo46YwvTK71GxX6orANZu7qpUtQ1ss1gAIqImBpCozFSZL/xQ7O2BegUgptY7HLul1mgjlUK+W3fso19SbgVXGGtnOwflC6gvjp1HnaHo5mi63lMclejx2KHaBspEVNjxjoUljPCxMB1iTlQEqq4AvgDkxripFVUiEWUapG2vALg0fjUqbB8Ks3KfzhCAlvxtilxT4EybjMjXbLu2buYlpZhooS6dPJcDYq3hOg6OpnMAACAASURBVCanZym62Zruw2C2XFD5UJA92Ldb6HSeABTil3KyIWmarUfF/QJgtgqUx62ozvlCAXAmMACo4ap+YuFcK2XTFHhBWUcu7BFRoDp9bW+g2x4r4qt5SbFnQmkEwO5OxNuYDy58z7DXg8wa3HqlmanX8gWgJZOthamgVmWzqr3+qbZdi0yHKEbqanO2fgEw+S0vKRyr1h4BsAeFZSf3rC3ItLmGoKPBAJFQbBwBiGxBq4w5knysshhV9aZ0XlL8xcR0AZYAyu8zfy8nCrQAuJ5KYWVtXOXkknyHwDKN0T/TxrtLb4UhX6+0S7MxeVA4XVVEZG1w4pePeL+uAGRKuiK3Q5SVoCsAKtf96uJOsXUEwJ0Wal0tC45SaesXMDkfN2TsxWJPAILMrpGJZRyW69wRFquUiqsz+yWlilBSI5RAO19lljstQNy/FhDeGmO4ac+zTexAemvAPnBpii/Kl97E0S5QXBlhuOnobfkI9weDmwdyGfWrwF+KX+kI/yB+PY1fwuVpTH5mNnH+NtaFnH0SR3NczJPL3m7LwF8D/w1YnWEHUG3LbPixCg9zHj8DEGF+NBA3MO8QP0feuMG3zdL8Wu/f3lmdQkTnyEYnztJITXTn8uTAxCt6VgWNCYHfIGzaBA3wZE/EV8mrYrHywn1sE906d2iVWjgSFg67EBEigXdbi+VPrAys8P/buD+4cbpuOYT+q72U8jbxXd/ASLQYX8b0IhBtTG8PbpyM7CrxHhxdBfa2pFP8/gHWRWZ/EurT3yOD4hqewksvmLBt1+V6UT6cegVsE1/DiW8LtH+KDwNrvaEp4nasts6+DhE3KRziBahQbTNxA/MGAJrNkR9829A/jBEhyhFcxt92T1qr1uUQ39CJ1/Cno+GnAeDJTgBYzStyIfodKwAwfKvVmX1W2VqcytXFeAQAlwaDc/BbgPHJVez/tYm9DfybbeH0n4UA7JzgkwAQj/FtAB/GN3axf97Zs903TNia4s8BIB/irjy0hh+4GRCM8JMd67P+O9ZiINi08qJDvI3T852jL2IYwNTIW6Yvenp7eKCvPxX18WNiefcdnVK7LJr8WwD8wLxvBz4/OhgMbh7LWNzul/SZ4AHAb4C3APgyDl2joHODwY2D4WWtIaxrMxkAwHcm0+/JJ3civro0m+3dweDmyfodU4nfr1Yv/1GsLibbonkqiKrFRqE/t8OIjuQmHH+LYQ7g8/4+9IYJ/sg98G2sxQA2dXMe+zs44DPADk5F4DQA2DvE54EAJ7MjW0TbmPTEeTtVBhIdhhPLIOdFYTCwIWy93jR/ZdozEQVGB1vA3oVTXIYcdm3a2lQv/wl4BUjG066h6v7WTYxld/9FTK1W7UnsrYqwLq/1RHyVvAX4DVCO8Fc7wN75Cb6kziRDEXkc2DnA2i2ia9N/sMxlXAE4GacIviysStImA3ACvE/rJCNpJrl/iM0A2Ug0ZA/w+QhBJTNI9Ik/VE2+4vopPg8Uwg4NAD4Gf1i7gVPgF8IyCsiINjFKww2MqWcEDAD4o+dgDPgsXnUNLm4OBoMtAJ8DTlYtdeL7oijHeNG+uSGSiteBMEW+CXRNRKHa1QOz56NmH07hGER0ymfx7b6Te8cQK//5yFywp22MVoHXOhFfNW8GToF1Ffnmexgq5eQTxsJh6/bxFNOjvzixgny5AnAXV+jO+HgXQUGf/NGWeIE/BN4NaQMke8lLU3wZl3GwDwC7x6Pn6M54cglAWAtTwusT0eQbvolREmxocxu8HyUAjEiP/cd4EXjeaOkA8MntvqxSrAO4rGdznhONNoBXeixugPIy3P1B9qZioxZ8HwB+69qZdLFNRH+tTUR/CqwDFwYD4HAwGAyk1rPa84C4GeIIyIen/Q1nKVrbcNNtWd8q/vtD4KezI76uAT9FqMJi46fAe8WvwA6UunthZbBycX8M7ALvAn7oC8DezRNMDy/E1Z1331sREj7FGvAeYA0ITQZ+A+MGE9maXrg/wfRwFQjKW+3NPQCIR1hzB4a7x3j2y/oWBEN818se4AGwKzUzbA0Gg8F0OMbtwWDQ7eYF07tix6V+3FrYrHc08wrvAz4s9436jSy11Vl7YtkmovtaYfh1n7Cd+lZI20RE2yOcXgTeijUiItoGtv1J0rcD+HPYKuKpimX6FLA3O+Lr+4C9Xqn7HLobXnwMEwBrmFzv6AB75wcrv2q2cXdVyWCNtwFrOEGIsYlstXOCEf5e3XV1dbByCcjvnLsrdkpKtnGCTXee66sYjtUQEPiMVAEmg8FAqL/PiABZTjztbwNHc4zcpns7BzIEK7ByWzTaAN4CvIZTLz++d9hpqn+MMfBBuYvLA6jepw/PRNQMj3vjbP+iNwDp5PjunMC0wAVgD0jXcN/Sjl7ESLRx78dJJ+KrRtTzl6H8Qj6gW6iPSjcHmw38CIiA76kDtpt/TlTaL19QhZCqjFK9myWgbS4skrbV00lyeUAYfanpjczuy8XewfZEkJzrVpNoehNdewKtZyKo0XNMkTsrMnMiyEJshaX9LUt9OO9MBHUdxfTfivRNis5UcN9ysH9YGnt5M7TeYlBmZuEKKzukT6rODP0j6nyzWijIRN57E0HVnc3DwQV73uUEI3wALz/AGO+wogl+HpZ3D4CoufZgRYXC+wKOr+PCBH8D4BVtlv99e6ZlHd74ORqKs98H/th/43n8fU8nsAb8FKUYC87lFE/H2sb3GOtzbvBMRL+jzJEu9xni7h9r49100UtIk5YguwXcBUrgvzuPOsRGDiTXcHod/RFfg7QZ4/4egO8BX4mBsBopbfBPLDcHYX4a1eu4B+CDpgGwYhZ1LWJiIhQUg2qURsYzInu6M6iotD5USKlYAYh1vbIXVfTCjW4BLOdtZ5dz94V6poILdcgIeyVtGeYuBonPqM1+14FuafpaAN9EtBRzsXq/XZBnG7FgOVi3AMakpY1hh61Ss86eQYhaC2ittVttEKLbTdOYWSMo9Ww7T90WYHf1yYbqCEDSiOVu/BjAu7CDyRpW9eRtcBlH5zBU2VncWbl5YR9pQ00OIBS9+d49bCR4r1/VAcCeapJY9vRn2zLz4tSMBOTbCcX3EBvFgur3faw9pZul/fsY1zEQ9Ps7eoF5L5ziMtGtdRxdVXu/blp5v3qKzTtE24u/Ze/m/ZPJFNPTg5X+CY/z906nmBwojcaP+ApMjnVi6+bRBJge35UjhARqEgAA/uLwFJgc3ugELTUyIephJCUpESdDYQkRtrr7qaS1iMjfqkkAtbBcW7ZjBVFodhe3q3MtOjajA5jaGVnLy8u0AIhlmxFZHWJgXkiCHhMpd/3RMqhqwkWrgQCSqqVWrPA6T5YCH5ftfJOwGYf/PdDZHFATIqEG1EaQe9o3lFEJJGTMg2LVKIrmJZAHmwhhTallSFZbjZFTmtocTglAapQbV+dbLACyNfaXg+GYhM0QgMK1wwqyuqW2TJzH9xuEvM4EUolM7IXWIK+JmsIazbhHnCXKSFSDrG6pCpE11IpHJjVRFSKpdYQNSwASigHkFMsVdRGIsaYUCKnWAmAsaCwRzkUJUm1Z1wdkDXStjFQG4IXds6H7czkBQEsUdA1CXk/0orZoBpxGxOny0roV/aIk9kb+Ij5So5sh1co0Ov6D6f5zykMgSE1cV++IE2A2pRba4rTUz5GtnDhu4hbq8VNXAHLZStovIt/XiY5hCUDQEmWBELbe9ryQip58vdwxp7BMpZYUAGHm6JuEaSy9qvRi00ZZRbYYW6FnPBtQeY9ezxd256qFsfo2u4QDdd5s4OwJQEaFFbta2xw08o6M6ljp0aU25i0b9b97JLWbMzHQzrIAgfhG0eUQZaJzTBC26r1VWCy3C4haNZAmAKjIRFWU2eAMMlUXkNkfUlumIFZpKmNSLQC2yaM1iH48re9sAai84rEslJcSgJqKEEharUgEZIu8GjnURtHwBaCmGEiV9JuRhjNcKSkA8kYo/U0GVDUA5A0QVS3V6ogTw621sk6MUArKkYgXF91satncGJcP8pTASOpYyvLKNncp7b9omhmIpq8tY9uW8TH1pVbB6EafSgBJWbeWW5WJHdUxp9RvUlZZZOlito9C1w0ArtUPAORK/TF+gE1h/po20jX2gr4AEAGopMyoWZ6s4/+XIaAIIWVAShlACRBQhJSKAGEWiyMy4Jx4iq3dNrJFL1GIMhc1MNKvVWvpzlpvGIjABABXrmd2ZbV6vKxrGTaL3l3qpc/KDPN9pXHMEgCt79WAGztqtgDI7zKmcl2XM4dZ3lw6GxrKI1Mp7JFNbL+ufo6YJzUBpyr5Rq6Y5FQiryEEAFQCeQ3kNQLzZXkNoJIhvXNP0mrpNlOLK4BKNNSmKr8+rmp2JZKtq1Cx+wWAhP52JgEwDVBDZSymshsAMqR9mJXLC0Cv06mDfpnafaQ6HhKFRhdPbcPzsiMAdtxOssKVh1Tr+eWsoSZDQRWaDKoFSIGIgCZDZnqvSEzv1kBObQ2oCa6otHrAGqKLNiNkNRF0aXUwGKileuEek0nNj4ja2ooZZem1ge7wAqIUje4ASk+EDcP1a3Kir7tL/Y0DDLcXTt+eG6wCF7tLdr+8eWEH2L90iFEyJ3bUbJxoJWeIBQzkasXts5js4Wf4qDg8NjYvFc4Bu4PB4K6MeNZn5SbCEAXh9NxPpc1BfXl6YxX5f8YKRqcAcJnok/evAi8jxOgUf2Te+GWEwAOsAU9NfrYG/IFYuU2fW7dMuoboIAUgKBpq60JYD19eG2I0vnxLS9dwbfOOavabK2tDjDb1qN0xTZRbpfcvq00Gg8HgxiHWZtWz/a37ePhtjC/KFYxLcjfGM++Fe4ZoJS7ppjLUez9+BPyTyoV3GdPQf+mJUnF1MBgAg8HgBPcGci/fV4GvDPfUGnOxNj23j633jPV6ysHgeDjHcnEXCDF66QXEGAuznis4vjkYTMSmlvbmj9LaRQpAemdjhOHaxi0g3Mbk3o3B4J5cTjwUVRPXRInXI9wfDO5OtcnRmr10OBULObHchKynsu5fOp6z6np1Om8XNwDoC2PXYRWYGTtqNktEK9GsSeM4AEiuKLvUeIhvAbtT/CkAYLgwPFWCEwBjszvpm1GN7u4BQn43RCH+K/B/MJGTyhfwRQDvwx4ma/gXE2nkfdgDcIqPJXh+Bx+T0/Exps7SHlphYGQMUJ9Qn3B7MLh7CmAbk9Xr+8D1c/f0RftbdyGiOsVruH8V2NkzmyDb8aIq0fo9I5fYeyl7bKg0k75WymZeqDpN68eOGhuNcDavLjIJMhTAd9Tv+BpOpMHKM5jsA3gglzqmJp/7Q0fhIzgCYrV0vw+8uxjf31E2BzHwvLzwBC8pm9vDUQw8fQq89EF8S8bagjgC/ALjp7CLk3d/QLQ+7xQLuCt4p7zs/wgDoxX9Rk8AwDWcnN8Fds4dAmNtZXfdWpvYmQpLlE+JDTexdyIt3I9g70P52+NRAGB9+hIwK5Tkk4+2laAXxu5vWn/TqBg4mhM7ajYnKs7PQvINHOp69V+NXfK6yLvvYBgBQGukud9EEOfxAvAhbZM4webG4VWosFTvlHvIvQn4Lr6uAutdwueBzQPg62vR/v1xESBIY3EE+Ane/f4T4OXRJ8TC3Wui6xlCqUIvCQOjNSeYVWYp0140H11+tYoXIbXflChCQJTUlEIrgUVCGRBTkRB5AqBnDWui2XtTtdQuGgVAXVlYi8pWMesZ6zAticQeJWcfBfQrgXKobA+YLCfBxPhxloAziaBddWJ/ZsmMY63xv5qnEdcK17i8lcPAnGI5EdSKiSAzNYSASMzbm7DycuIvA8IstWYCiwBBmuMJAB9VofEA7M8IdCZDhkH1fcdK0zvAf7Euu46PAs9InbgvlGRQrEnD0L596dPhvM7D4QHeBRzfvTEY3D7GyGwOmq3hvvi1d/XC4BBzNgbtPnJ9wTwAAN8X6Z0m8t8nVD4+EHnzkunsxh0vmD5+DpxLzGbAUtsLRvgmgEtV8+vBFoBLg2dG5yCOBLvnVwarWyjFEexPgReAvSmE18X+MS4TrU/u4TLRrcvvAA5wmWgdh9i4Q3euCINTp5l2N91TpyIho7G1bki5aC6IQtMCoKIA1Jp4T43VhAiqGM48QKNbgCAjomDJFsCOvJObOyLyR+j50i2APRM4pwVwbbasEAp23P/Ezj1Euolz5mcqERDFWKQ0ajZLSG0rnVZL9afk0o9uqLpHpCGc8Q6Wy4CxnDKGWgaMqlaG1XAmJ0TRNJlZms0BBElLbQAnSgFRKQSgEMsZUgASymIq5glAk6KnC1AsngjyQ9WJnJKlFLSeokeULi8A1lpAJ8y6fpnYF0T1HqntASu3qNDup0pmYnvuighAYVZI2sC1OYioDpBZux4uWA5+KGIn86EnqITXo9tH2Qt1WgBCIksAQE0p5vZUVrg6QJCRsC7oEYClpoI7oeoAKx5CIwTVjR21vACYaCV+mEL1MrltueBSm5Yh0723mkVXekJI9uRdA1XNAaC7HV9QtnInqDMRlq2JOyfKsBbKnfyahiKoCWJrtzT9+iKThYmqFAchk30CgFoEaJMCUBG1mC0AsiBnKYHAPAGI+kLVAUbdqmX5u7GjziAAEKqVF7JOERGliHTD7k6d2w9Vv0MVusQUIlGjyjmn3JmPX45YbV2XNTpmXSO2HSvaNoOpT1mAsCQATQEEVDcA1Q1U6YhP7PMN3Do3uH04xbgExETQ3cn47wAAr8F1TgLgq4E/xAI97voUnzrbJ9v0B2WWo6xqDXtCDdu7eXAyASaHN+Zsmd3PJZQAfiy9VOMRgFSK59PAC9idYjMLEGTtBmDZh/8pcEVJ3S3g4wDRLeAK8EXgmhbxA4xuye72PXge+Fh/dmUoVS2I6wBIKhlILn3mB4cAgPy1vxr8/fvvBEB2ZYRxGKDeGA4v58CnT+8OBrePh5fv0K11Y4j9zytxftIAwKdxCuDP5ESlemlfEGuiQKkxatWvTwkEWopMCyAWI+e0AKiEkvgQLUDYF6oOUCZKpd+UNYU8e5YWIGhV+LpEhazLqYwBpGLIoluXBLAEwDHnJZF5oqMSOot6taRqaeHCW1OhoiKqqU5SaoC4CBEU8i5nX70coDZCRmVKVRDUFKoxTFC0VMcqHwJK8obiUujcYrmwkN8v8CdsIqHii8OZDktm9FodmTOn0hIA8ZVzBYDOIADunvU9oeqgNlMsvJIEYnHAEQDHIMRakEv1Y2WIOan75NQYk3Wxx3eQN0Qq3GJuC+LDUMialzgxaguj7eiNndVeqd7GijFlAAolnT0L8lIAQC3KBmiIIqAWWfnEjnJr9D2Wd22nty1gG8Ae8AfigB1O4etYX3YOFQBGZ9nCA79USwcfxwTYn+DZBAjyK1MAQtMLy8s4vYp8A/e89v6d/X5UczieYHoSAcDO7RPg9N4FALh07+h0Cpwe/sUeAOxfWh0Mzkkvx0vddUlRlImj0mXy36DSVlyeKvnkLXUgujU8ugh8E6c3BzeO8bycpAkC/D/+n/o4XsA78QDAvvD02sNbpRIohcS2wTl+HgDCEfAygjWz9tX4TSQAOZjVNV7aAWqDzcqujzUVy7cAEYlh4pItQOjuWe+EqtPVV1hVuOODmqh/C9jHRlSZOFi2GU8qAifZ39RUAIKmQqUqdEWEuIRsAbLcRO9TYbRKOZJQ1d7aLFS1ALmwK5BuOGLuoZylBArbfWFYFiAgMzTJHcMu9bOwdABtqBcb9bYwApCINnQZAQjSlijoblLuCoBdlP6e9VaouiivW1K2+b4A5K1rn9SJ6wYgzGpUuVMVy9kyk9SQlmZiRoVKextFIwCiKK1wjKJJD1sqEMiBai12+GsTFC2iRg6NM1j3yZIvVBcTVrKf0gIgbPoiSgFUoguIKEdTx0AkbT5KLBYAM8OfA61QeKJKznqpPCx1vUpFmNTA6pHbPgFwIwla4/cYZxGAx7FnvfhI7wlR3hARGqK2MMpDQ1R6qgQAiL3jgTwLEGRig1E556amj80cpIj5qQPiRUQF9PCxoTYU5Q+gpLpqC6pDc50WALcFEJ8AwAiA2nK5bUPkVGVUImgo6iqBC0mJqgiIa7KV2RK2AJj3F0SwBCBfWgDa6pFbZWPtGRKFSOu2rVNvn2zAMfEGfAGIi5aIqC2QiS8qVa1qiKj1zQ3SmshqUAqKkInijfr6z6iVRV5ACYKJj9hQW2uJD2tSxpdA0FJhroyoDhGU1oClUdtKinkAa89pojYQWbzIqq0f7VMIICnqVk8vWoMDNe4SJmEBYAlAMLMLmMecbQiN6FTetLxt7RkSRdKyO3T3yYZr4i0eqQUgEbIprN6stPDkDYuW1OYLAFRrarcLCWUo5bf3fqkoyqAVU8duh4DGan17BEAJTmcU4LYAuZl4TBoxU1e0yxrldgiLx9LMziSVL2aFOZ234fYcAbCtPUOimvIQiIrQ3yfbMfEWj5RfV4qq7zaOoj9QeRpXRNTKKceGbF0vreWLVjougDFIVpVoaQEonC5AbwvTUoGSirimJk2pAfI0kG53SgtWPg2PPdxroEshJkqQU5G0VCKoSMV/8Hwkray1pmcrp2WM5BDdDnM6b8Nt677MEwB7DkcvewPeptk9Jt72FFJrD470H2vIqs1pQ0Q1Cq9DqCgLgJhybczfJwCyC2jdLiBVf191AZYSWNidBNBU7kxg4AelfHy4E1ihGZMFMiNbIqKqIZJe/+5GOiILjF+MWSqw1jBk0+aGObVfQXYdHQFoqeruI24eHNoVwN0n2zbu8MqnWNwCABBdKxp3hkz2+Cnl83SAeUpgYCmB/cNAAAssEh4rHQFQ2wRVarOmGDlRE0iX7saNkwDYvWvtTNtpZLRnXUTeDhLdDbf14xp0BUAvprhTus4CrrMZVaeCun2+lbb+dlqbFiAzLuEqKEWu5uVKu9gESw8Dxeu26v0fZVH3UVDV1tmtXE3+CnsIEh4JtVWIluGFEQBdCDVV3Yw3tdK1O9O2HZ4ASM8qVwAyIlLWnqE9fHQu60Zz7x8FNLnq1Ev7jeKSiNqiqwNE4hOIcjkFoN3rzj4RJD+6Zyr4d0xHAEKiVFWuXK4KJ0BMrR8rqVO3SHeMSeesZW4oS3r+NoTK+sQzzklFm9UEViSKzmWJPbelPnOpeYAFo4CGYoS1aM1nzQTOmwqGngqu/r0qfIeOACAlUrU1l9MBMRBRa40LY6KoKwC16iMtbUpV09i+1h7n9AuAXnjqWGdpa8/ZArCwBZB/I2v8mcAZ8wANkYiwULTU5EnPkovv0fnGoSsAKK1YAAWAVvo2CsMPAI75sJW1qZov1CqYE7zNUC7chrA1LWqPdVYujZFmCEBIna65TwB6WDATaNCf0zf01i1bPPua3w/6g0WXmL1iZ0dM7XAVSIDARAIPvoRjuW7mhzmdv+F2NZye9/6gbVx/SQe/72VvaoJO+3jNlpesDwYX+oxI9i4O7p2auYsS19WnWMuov/fF3aVXAMIrwHiWL78dMbXLCT4BfA7THYicvjPEusxaL8xpOHfD7Xysra11YGsvzOavZrwggKVNvLtc2Jp56vo57HtxertTQIJVeRl2OkLye0avAOzi5ABX+lpMP2Jqhx/a0Ve9e90wp3M33I43ReRDwLPO0tae8GMNu1yaYFvMBCrvVel+aQpHFpGXdCCPyD3Ska3f++LupaMDlELdb4CODuBHTO17WhKYMa7T8bphTudtQ+iGWrWtsxxrz9k6AJy1gFYGoZU7JZl/dKyBkChbVNxLCMAbE18AEmWdX6IrAFnPPIBDSZUe13u+HKhF7KhQCM+cbQjdfbacDUXtnULnCoC1IWUptiVtcVYB+I+BEYAEMDGgxDDcFwA/YmqHmEhtN9kNzWqHOcWcbQi9jdYedUPRQD13vgD8R8UIgIwfJLO5ELvLeQLgrAX06UBW8M2kszgdl409efKQpBSIP5SIcgyIKPD9IRDUbQGElABhJW0jPAFgACMAFRHldrfdUNMVAGc1sE8AigVu+B1CoXKkqCgAUMttfnXsSvE+TaEthANRW30BkCa+2hSuIqIS2X+YlvyhUQIQVI99BFu0VIVyPjmjGr2zhxUlSKgGAhHiKIEVb1EvMMYUI2hluLMC6AqAYwpXAMKU4KyON4wiKFuS89WyHJGI7Mzl6nXb2wKkRj0UingwXwBCqlWs1JTyWHrGyx9oVEuQUqEiIcZEwufTFQDPFC6gFEjb30Hc2Dc4rVq4SZ3fUkePoRr6UAuAMuvsFYCYSDUkMZVARrkrABYBEVBRKIIfQld80xQU4lHaxDumBsLlmcv1cTFDACrKgYRabTBYKQEQg7ikv3ENiUoVeFTEGm6ruQIQUgG0jT4gTJylMqB8542Jd2pPEDCPgxkCoHbwifTYDcilqbi0FOkpiqAVxvIyMuUyLQDz7wzJhXwKnN99AlAbKTCheBykni73aenVASxYAH4P0JFlC/d3Lc3a7C6AqFBthf7t6ADaFFROBvaNApjfL0RsBeEdpn9DT9Sa6Z5ARhRohW8QEToCYAXKzh521o75HSMWYJTBp/mNsCRvGKgmhShVv5k3PqIb7v7LMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzD0CFP/QAAASFJREFUMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMMzvPf8/Yvf7RD61048AAAAASUVORK5CYII=",
   ["fnt"] = {
      ["char"] = {
         {
            ["width"] = 3,
            ["x"] = 217,
            ["y"] = 94,
            ["yoffset"] = 30,
            ["height"] = 1,
            ["page"] = 0,
            ["id"] = 32,
            ["chnl"] = 15,
            ["xoffset"] = -1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 502,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 33,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 100,
            ["y"] = 135,
            ["yoffset"] = 5,
            ["height"] = 7,
            ["page"] = 0,
            ["id"] = 34,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 377,
            ["y"] = 93,
            ["yoffset"] = 7,
            ["height"] = 18,
            ["page"] = 0,
            ["id"] = 35,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 231,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 36,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 66,
            ["y"] = 78,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 37,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 83,
            ["y"] = 77,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 38,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 3,
            ["x"] = 109,
            ["y"] = 135,
            ["yoffset"] = 5,
            ["height"] = 7,
            ["page"] = 0,
            ["id"] = 39,
            ["chnl"] = 15,
            ["xoffset"] = 7,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 253,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 40,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 245,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 41,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 380,
            ["y"] = 112,
            ["yoffset"] = 5,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 42,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 227,
            ["y"] = 115,
            ["yoffset"] = 10,
            ["height"] = 14,
            ["page"] = 0,
            ["id"] = 43,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 5,
            ["x"] = 55,
            ["y"] = 136,
            ["yoffset"] = 21,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 44,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 351,
            ["y"] = 126,
            ["yoffset"] = 17,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 45,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 238,
            ["y"] = 130,
            ["yoffset"] = 21,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 46,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 28,
            ["y"] = 55,
            ["yoffset"] = 5,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 47,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 415,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 48,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 253,
            ["y"] = 94,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 49,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 201,
            ["y"] = 96,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 50,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 385,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 51,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 370,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 52,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 188,
            ["y"] = 96,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 53,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 310,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 54,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 475,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 55,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 460,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 56,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 490,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 57,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 505,
            ["y"] = 66,
            ["yoffset"] = 11,
            ["height"] = 14,
            ["page"] = 0,
            ["id"] = 58,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 5,
            ["x"] = 505,
            ["y"] = 47,
            ["yoffset"] = 11,
            ["height"] = 18,
            ["page"] = 0,
            ["id"] = 59,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 287,
            ["y"] = 115,
            ["yoffset"] = 10,
            ["height"] = 13,
            ["page"] = 0,
            ["id"] = 60,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 61,
            ["y"] = 136,
            ["yoffset"] = 13,
            ["height"] = 7,
            ["page"] = 0,
            ["id"] = 61,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 272,
            ["y"] = 115,
            ["yoffset"] = 10,
            ["height"] = 13,
            ["page"] = 0,
            ["id"] = 62,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 317,
            ["y"] = 93,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 63,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 395,
            ["y"] = 26,
            ["yoffset"] = 7,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 64,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 134,
            ["y"] = 76,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 65,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 104,
            ["y"] = 98,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 66,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 340,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 67,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 445,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 68,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 118,
            ["y"] = 97,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 69,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 227,
            ["y"] = 94,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 70,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 265,
            ["y"] = 73,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 71,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 280,
            ["y"] = 73,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 72,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 240,
            ["y"] = 94,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 73,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 292,
            ["y"] = 94,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 74,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 185,
            ["y"] = 75,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 75,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 146,
            ["y"] = 97,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 76,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 75,
            ["y"] = 99,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 77,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 60,
            ["y"] = 99,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 78,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 45,
            ["y"] = 99,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 79,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 132,
            ["y"] = 97,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 80,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 216,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 81,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 30,
            ["y"] = 99,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 82,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 15,
            ["y"] = 99,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 83,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 168,
            ["y"] = 75,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 84,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 160,
            ["y"] = 97,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 85,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 249,
            ["y"] = 73,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 86,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 31,
            ["y"] = 78,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 87,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 49,
            ["y"] = 78,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 88,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 100,
            ["y"] = 77,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 89,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 400,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 90,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 6,
            ["x"] = 269,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 91,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 112,
            ["y"] = 53,
            ["yoffset"] = 5,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 92,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 261,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 93,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 76,
            ["y"] = 136,
            ["yoffset"] = 5,
            ["height"] = 7,
            ["page"] = 0,
            ["id"] = 94,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 303,
            ["y"] = 129,
            ["yoffset"] = 29,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 95,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 6,
            ["x"] = 172,
            ["y"] = 134,
            ["yoffset"] = 3,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 96,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 121,
            ["y"] = 118,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 97,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 452,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 98,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 214,
            ["y"] = 117,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 99,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 410,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 100,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 106,
            ["y"] = 119,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 101,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 492,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 102,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 396,
            ["y"] = 49,
            ["yoffset"] = 10,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 103,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 479,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 104,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 340,
            ["y"] = 50,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 105,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 9,
            ["x"] = 75,
            ["y"] = 0,
            ["yoffset"] = 4,
            ["height"] = 27,
            ["page"] = 0,
            ["id"] = 106,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 424,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 107,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 0,
            ["y"] = 78,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 108,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 31,
            ["y"] = 120,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 109,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 201,
            ["y"] = 117,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 110,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 46,
            ["y"] = 120,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 111,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 354,
            ["y"] = 50,
            ["yoffset"] = 10,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 112,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 438,
            ["y"] = 49,
            ["yoffset"] = 10,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 113,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 188,
            ["y"] = 117,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 114,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 175,
            ["y"] = 117,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 115,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 363,
            ["y"] = 93,
            ["yoffset"] = 6,
            ["height"] = 19,
            ["page"] = 0,
            ["id"] = 116,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 162,
            ["y"] = 118,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 117,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 76,
            ["y"] = 120,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 118,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 460,
            ["y"] = 92,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 119,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 16,
            ["y"] = 120,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 120,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 266,
            ["y"] = 51,
            ["yoffset"] = 10,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 121,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 149,
            ["y"] = 118,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 122,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 204,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 123,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 3,
            ["x"] = 85,
            ["y"] = 0,
            ["yoffset"] = 4,
            ["height"] = 27,
            ["page"] = 0,
            ["id"] = 124,
            ["chnl"] = 15,
            ["xoffset"] = 7,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 192,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 125,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 202,
            ["y"] = 133,
            ["yoffset"] = 15,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 126,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 3,
            ["x"] = 221,
            ["y"] = 94,
            ["yoffset"] = 30,
            ["height"] = 1,
            ["page"] = 0,
            ["id"] = 160,
            ["chnl"] = 15,
            ["xoffset"] = -1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 507,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 161,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 365,
            ["y"] = 26,
            ["yoffset"] = 6,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 162,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 325,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 163,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 409,
            ["y"] = 110,
            ["yoffset"] = 11,
            ["height"] = 11,
            ["page"] = 0,
            ["id"] = 164,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 151,
            ["y"] = 76,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 165,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 3,
            ["x"] = 276,
            ["y"] = 26,
            ["yoffset"] = 6,
            ["height"] = 24,
            ["page"] = 0,
            ["id"] = 166,
            ["chnl"] = 15,
            ["xoffset"] = 7,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 352,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 167,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 253,
            ["y"] = 130,
            ["yoffset"] = 5,
            ["height"] = 3,
            ["page"] = 0,
            ["id"] = 168,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 442,
            ["y"] = 92,
            ["yoffset"] = 7,
            ["height"] = 16,
            ["page"] = 0,
            ["id"] = 169,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 10,
            ["x"] = 302,
            ["y"] = 115,
            ["yoffset"] = 5,
            ["height"] = 13,
            ["page"] = 0,
            ["id"] = 170,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 353,
            ["y"] = 113,
            ["yoffset"] = 11,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 171,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 113,
            ["y"] = 135,
            ["yoffset"] = 14,
            ["height"] = 6,
            ["page"] = 0,
            ["id"] = 172,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 333,
            ["y"] = 127,
            ["yoffset"] = 17,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 173,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 424,
            ["y"] = 92,
            ["yoffset"] = 7,
            ["height"] = 16,
            ["page"] = 0,
            ["id"] = 174,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 342,
            ["y"] = 126,
            ["yoffset"] = 5,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 175,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 9,
            ["x"] = 24,
            ["y"] = 136,
            ["yoffset"] = 5,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 176,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 61,
            ["y"] = 120,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 177,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 441,
            ["y"] = 109,
            ["yoffset"] = 5,
            ["height"] = 11,
            ["page"] = 0,
            ["id"] = 178,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 9,
            ["x"] = 422,
            ["y"] = 110,
            ["yoffset"] = 5,
            ["height"] = 11,
            ["page"] = 0,
            ["id"] = 179,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 157,
            ["y"] = 134,
            ["yoffset"] = 3,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 180,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 311,
            ["y"] = 50,
            ["yoffset"] = 10,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 181,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 310,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 182,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 248,
            ["y"] = 130,
            ["yoffset"] = 14,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 183,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 6,
            ["x"] = 165,
            ["y"] = 134,
            ["yoffset"] = 25,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 184,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 432,
            ["y"] = 109,
            ["yoffset"] = 5,
            ["height"] = 11,
            ["page"] = 0,
            ["id"] = 185,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 10,
            ["x"] = 313,
            ["y"] = 114,
            ["yoffset"] = 5,
            ["height"] = 13,
            ["page"] = 0,
            ["id"] = 186,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 339,
            ["y"] = 113,
            ["yoffset"] = 11,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 187,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 268,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 188,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 284,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 189,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 300,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 190,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 305,
            ["y"] = 93,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 191,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 234,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 192,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 251,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 193,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 132,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 194,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 200,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 195,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 183,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 196,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 166,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 197,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 117,
            ["y"] = 76,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 198,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 316,
            ["y"] = 0,
            ["yoffset"] = 5,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 199,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 15,
            ["y"] = 29,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 200,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 29,
            ["y"] = 29,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 201,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 113,
            ["y"] = 27,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 202,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 99,
            ["y"] = 27,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 203,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 127,
            ["y"] = 27,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 204,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 140,
            ["y"] = 26,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 205,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 166,
            ["y"] = 26,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 206,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 179,
            ["y"] = 26,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 207,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 201,
            ["y"] = 75,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 208,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 481,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 209,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 466,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 210,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 451,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 211,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 346,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 212,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 436,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 213,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 421,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 214,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 367,
            ["y"] = 113,
            ["yoffset"] = 10,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 215,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 378,
            ["y"] = 26,
            ["yoffset"] = 4,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 216,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 85,
            ["y"] = 28,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 217,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 71,
            ["y"] = 28,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 218,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 57,
            ["y"] = 28,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 219,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 43,
            ["y"] = 29,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 220,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 149,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 221,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 355,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 222,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 382,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 223,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 42,
            ["y"] = 55,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 224,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 84,
            ["y"] = 54,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 225,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 14,
            ["y"] = 55,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 226,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 326,
            ["y"] = 50,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 227,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 174,
            ["y"] = 96,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 228,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 338,
            ["y"] = 26,
            ["yoffset"] = 2,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 229,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 478,
            ["y"] = 92,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 230,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 266,
            ["y"] = 94,
            ["yoffset"] = 10,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 231,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 487,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 232,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 472,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 233,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 457,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 234,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 430,
            ["y"] = 71,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 235,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 70,
            ["y"] = 54,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 236,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 0,
            ["y"] = 55,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 237,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 56,
            ["y"] = 55,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 238,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 90,
            ["y"] = 98,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 239,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 296,
            ["y"] = 50,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 240,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 466,
            ["y"] = 49,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 241,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 442,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 242,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 427,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 243,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 412,
            ["y"] = 26,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 244,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 281,
            ["y"] = 50,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 245,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 295,
            ["y"] = 72,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 246,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 324,
            ["y"] = 114,
            ["yoffset"] = 11,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 247,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 395,
            ["y"] = 92,
            ["yoffset"] = 9,
            ["height"] = 17,
            ["page"] = 0,
            ["id"] = 248,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 152,
            ["y"] = 52,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 249,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 204,
            ["y"] = 52,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 250,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 139,
            ["y"] = 53,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 251,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 279,
            ["y"] = 94,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 252,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 15,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 28,
            ["page"] = 0,
            ["id"] = 253,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 61,
            ["y"] = 0,
            ["yoffset"] = 4,
            ["height"] = 27,
            ["page"] = 0,
            ["id"] = 254,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 89,
            ["y"] = 0,
            ["yoffset"] = 5,
            ["height"] = 26,
            ["page"] = 0,
            ["id"] = 255,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 331,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 262,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 126,
            ["y"] = 53,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 263,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 361,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 268,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 178,
            ["y"] = 52,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 269,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 217,
            ["y"] = 51,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 273,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 376,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 286,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 30,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 28,
            ["page"] = 0,
            ["id"] = 287,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 153,
            ["y"] = 26,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 304,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 135,
            ["y"] = 118,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 305,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 233,
            ["y"] = 73,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 321,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 368,
            ["y"] = 50,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 322,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 217,
            ["y"] = 73,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 338,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 495,
            ["y"] = 92,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 339,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 391,
            ["y"] = 0,
            ["yoffset"] = 5,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 350,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 214,
            ["y"] = 96,
            ["yoffset"] = 10,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 351,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 406,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 352,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 191,
            ["y"] = 52,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 353,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 217,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 376,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 496,
            ["y"] = 0,
            ["yoffset"] = 0,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 381,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 165,
            ["y"] = 52,
            ["yoffset"] = 3,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 382,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 44,
            ["y"] = 0,
            ["yoffset"] = 4,
            ["height"] = 27,
            ["page"] = 0,
            ["id"] = 402,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 148,
            ["y"] = 134,
            ["yoffset"] = 3,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 710,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 139,
            ["y"] = 134,
            ["yoffset"] = 3,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 711,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 9,
            ["x"] = 228,
            ["y"] = 130,
            ["yoffset"] = 3,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 728,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 262,
            ["y"] = 130,
            ["yoffset"] = 5,
            ["height"] = 3,
            ["page"] = 0,
            ["id"] = 729,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 91,
            ["y"] = 135,
            ["yoffset"] = 2,
            ["height"] = 7,
            ["page"] = 0,
            ["id"] = 730,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 6,
            ["x"] = 179,
            ["y"] = 133,
            ["yoffset"] = 25,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 731,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 10,
            ["x"] = 217,
            ["y"] = 133,
            ["yoffset"] = 4,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 732,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 10,
            ["x"] = 128,
            ["y"] = 134,
            ["yoffset"] = 3,
            ["height"] = 5,
            ["page"] = 0,
            ["id"] = 733,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 347,
            ["y"] = 93,
            ["yoffset"] = 6,
            ["height"] = 19,
            ["page"] = 0,
            ["id"] = 937,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 0,
            ["y"] = 121,
            ["yoffset"] = 10,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 960,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 267,
            ["y"] = 130,
            ["yoffset"] = 17,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 8211,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 285,
            ["y"] = 129,
            ["yoffset"] = 17,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 8212,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 5,
            ["x"] = 49,
            ["y"] = 136,
            ["yoffset"] = 4,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8216,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 5,
            ["x"] = 505,
            ["y"] = 81,
            ["yoffset"] = 4,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8217,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 5,
            ["x"] = 43,
            ["y"] = 136,
            ["yoffset"] = 21,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8218,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 498,
            ["y"] = 108,
            ["yoffset"] = 4,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8220,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 12,
            ["y"] = 137,
            ["yoffset"] = 4,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8221,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 11,
            ["x"] = 0,
            ["y"] = 137,
            ["yoffset"] = 21,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8222,
            ["chnl"] = 15,
            ["xoffset"] = 3,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 296,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 8224,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 324,
            ["y"] = 26,
            ["yoffset"] = 5,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 8225,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 8,
            ["x"] = 34,
            ["y"] = 136,
            ["yoffset"] = 11,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8226,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 186,
            ["y"] = 133,
            ["yoffset"] = 21,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 8230,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 13,
            ["y"] = 78,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 8240,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 401,
            ["y"] = 110,
            ["yoffset"] = 11,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 8249,
            ["chnl"] = 15,
            ["xoffset"] = 4,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 7,
            ["x"] = 393,
            ["y"] = 112,
            ["yoffset"] = 11,
            ["height"] = 12,
            ["page"] = 0,
            ["id"] = 8250,
            ["chnl"] = 15,
            ["xoffset"] = 5,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 0,
            ["y"] = 100,
            ["yoffset"] = 5,
            ["height"] = 20,
            ["page"] = 0,
            ["id"] = 8364,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 482,
            ["y"] = 108,
            ["yoffset"] = 5,
            ["height"] = 8,
            ["page"] = 0,
            ["id"] = 8482,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 12,
            ["x"] = 411,
            ["y"] = 92,
            ["yoffset"] = 8,
            ["height"] = 17,
            ["page"] = 0,
            ["id"] = 8706,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 17,
            ["x"] = 329,
            ["y"] = 93,
            ["yoffset"] = 6,
            ["height"] = 19,
            ["page"] = 0,
            ["id"] = 8710,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 104,
            ["y"] = 0,
            ["yoffset"] = 5,
            ["height"] = 26,
            ["page"] = 0,
            ["id"] = 8719,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 118,
            ["y"] = 0,
            ["yoffset"] = 5,
            ["height"] = 26,
            ["page"] = 0,
            ["id"] = 8721,
            ["chnl"] = 15,
            ["xoffset"] = 2,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 318,
            ["y"] = 128,
            ["yoffset"] = 16,
            ["height"] = 2,
            ["page"] = 0,
            ["id"] = 8722,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 13,
            ["x"] = 98,
            ["y"] = 54,
            ["yoffset"] = 5,
            ["height"] = 22,
            ["page"] = 0,
            ["id"] = 8725,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 4,
            ["x"] = 243,
            ["y"] = 130,
            ["yoffset"] = 14,
            ["height"] = 4,
            ["page"] = 0,
            ["id"] = 8729,
            ["chnl"] = 15,
            ["xoffset"] = 6,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 280,
            ["y"] = 26,
            ["yoffset"] = 2,
            ["height"] = 23,
            ["page"] = 0,
            ["id"] = 8730,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 16,
            ["x"] = 450,
            ["y"] = 109,
            ["yoffset"] = 12,
            ["height"] = 10,
            ["page"] = 0,
            ["id"] = 8734,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 0,
            ["y"] = 29,
            ["yoffset"] = 4,
            ["height"] = 25,
            ["page"] = 0,
            ["id"] = 8747,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 467,
            ["y"] = 108,
            ["yoffset"] = 12,
            ["height"] = 9,
            ["page"] = 0,
            ["id"] = 8776,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 91,
            ["y"] = 119,
            ["yoffset"] = 9,
            ["height"] = 15,
            ["page"] = 0,
            ["id"] = 8800,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 242,
            ["y"] = 115,
            ["yoffset"] = 11,
            ["height"] = 14,
            ["page"] = 0,
            ["id"] = 8804,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 257,
            ["y"] = 115,
            ["yoffset"] = 11,
            ["height"] = 14,
            ["page"] = 0,
            ["id"] = 8805,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 14,
            ["x"] = 0,
            ["y"] = 0,
            ["yoffset"] = 3,
            ["height"] = 28,
            ["page"] = 0,
            ["id"] = 9674,
            ["chnl"] = 15,
            ["xoffset"] = 1,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 234,
            ["y"] = 51,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 64257,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
         {
            ["width"] = 15,
            ["x"] = 250,
            ["y"] = 51,
            ["yoffset"] = 4,
            ["height"] = 21,
            ["page"] = 0,
            ["id"] = 64258,
            ["chnl"] = 15,
            ["xoffset"] = 0,
            ["xadvance"] = 16,
         },
      },
      ["page"] = {
         {
            ["id"] = 0,
            ["charscount"] = 256,
            ["file"] = "BitstreamVeraSansMono_0.png",
         },
      },
      ["common"] = {
         {
            ["greenChnl"] = 0,
            ["scaleW"] = 512,
            ["alphaChnl"] = 0,
            ["scaleH"] = 512,
            ["pages"] = 1,
            ["redChnl"] = 0,
            ["packed"] = 0,
            ["base"] = 25,
            ["blueChnl"] = 0,
            ["lineHeight"] = 31,
         },
      },
      ["info"] = {
         {
            ["bold"] = 0,
            ["padding"] = "0,0,0,0",
            ["italic"] = 0,
            ["stretchH"] = 100,
            ["outline"] = 0,
            ["spacing"] = "1,1",
            ["charset"] = "",
            ["face"] = "Bitstream Vera Sans Mono",
            ["size"] = 32,
            ["smooth"] = 1,
            ["aa"] = 1,
            ["unicode"] = 1,
         },
      },
   },
}
